### ISSUE TITLE
Custom Locations

### ISSUE THREAD

**Issue by Richard-Payne** [nginx-proxy/nginx-proxy#1003]
#So, I can re-write the vhost config are I can and settings to the root location.  However, how can I add settings for additional locations?

The specific use case here is using Collabora CODE with Nextcloud.  The required config can be found here: https://icewind.nl/entry/collabora-online/

Is there a way to add addition location based settings without doing a completely custom vhost config?

**Comment by saesh** [comment]
Have you tried [custom configuration for your vhost](https://github.com/jwilder/nginx-proxy/blob/master/README.md#per-virtual_host)?

**Comment by teebszet** [comment]
I have a similar use case, where I want to have several location blocks to handle browser caching.
However, I need access to the $VIRTUAL_HOST env within each location {} block, as i still want to proxy_pass to that $VIRTUAL_HOST.

I imagine this is even more complicated when VIRTUAL_HOST=my.virtual.host, my.alias.virtual.host

Any idea whether this already exists, or if there is a more clever way to achieve setting cache headers based on content type?

```
# generated
upstream my.virtual.host {
     server 172.18.0.3:4020;
}
server {
        server_name my.virtual.host;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location ~ ^/resources/js {
                proxy_pass http://my.virtual.host;
                add_header Cache-Control public;
                expires    max;
        }
        location ~ ^/resources/ {
                proxy_pass http://my.virtual.host;
                add_header Cache-Control private;
                expires    $expires;
        }
        location / {
                proxy_pass http://my.virtual.host;
        }
}
```

**Comment by trathailoi** [comment]
Is there any WIP for this please ?
