### ISSUE TITLE
proxy not registering new hosts

### ISSUE THREAD

**Issue by jmls** [nginx-proxy/nginx-proxy#101]
Had an issue today when new docker containers were not accessible after startup. After a bit of poking around, I saw that the /etc/nginx/conf.d/default.conf file only held servers that had already started. No new containers were being added.

I stopped, removed and started a new proxy container, and all is well in the world again. New docker containers are appearing in the upstream list

Has anyone seen this behaviour before ? I know that it will be incredibly difficult to try and fix seeing as I have no further information, but just wanted to raise this just in case someone else has had the problem and has a fix / solution / comment to make 

thanks

julian

**Comment by jwilder** [comment]
I've seen it w/ docker-gen several months ago but not recently w/ newer versions of docker.  There was an issue in docker related to lost events but I'm not sure what the status of it is anymore.

What version of docker are you running.

**Comment by jmls** [comment]
thanks for the feedback. We're running 1.4.1

docker -v
Docker version 1.4.1, build 5bc2ff8

**Comment by tkw1536** [comment]
Resolved by newer versions of `docker-gen`. 
Which the repository is now using.
