### ISSUE TITLE
Tag / version for Raspeberry Pi 3 & Alpine. 

### ISSUE THREAD

**Issue by IoTPlay** [nginx-proxy/nginx-proxy#1017]
Hi, could you add a tag for raspberry Pi 3 on Alpine please?

Jéan Roux.

**Comment by buchdag** [comment]
Fixed as of #1470 + 4a1d5bfc58af35f5e90dcefb47b35a274c903150 + d120ce9fdebf09a6c7b90ecff7eda0b7d2760ef3

`arm64` and `arm/v7` images are availables from `jwilder/nginx-proxy` or the new registry `nginxproxy/nginx-proxy`
