### ISSUE TITLE
Colors and formatting

### ISSUE THREAD

**Issue by kytwb** [nginx-proxy/nginx-proxy#104]
I tried to look quickly at the code to eventually find where it comes from, but in vain. A picture's worth tousands word so I'll just leave this here:

![Colors and formatting](http://s18.postimg.org/c6cdnjfkp/color_issue.png)

**Comment by jwilder** [comment]
This is a bug in forego I believe.  It looks like it doesn't always reset the terminal colors after printing a line.  I have seen this is with other projects that use forego as well.

**Comment by kytwb** [comment]
Related to ddollar/forego/issues/17?

**Comment by tkw1536** [comment]
Related issue is closed, closing.
