### ISSUE TITLE
In single container, how to assign VIRTUAL_PORT per VIRTUAL_HOST

### ISSUE THREAD

**Issue by soulawaker** [nginx-proxy/nginx-proxy#1042]
I've used docker-compose to make my proxy group. I already know that single container can have multiple VIRTUAL_HOSTs. But I don't know and I can't find how to assign a VIRTUAL_PORT per VIRTUAL_HOST in single container. Does the way exist?

**Comment by Mactory** [comment]
As far as I understand it, you can only have one VIRTUAL_PORT per container. If a container has multiple VIRTUAL_HOSTs, they all point to the same port.

**Comment by soulawaker** [comment]
Thanks to reply. Really, does not exist another possible method?

**Comment by haster** [comment]
I don't think so. 

Wanting to expose different ports for different hosts suggests you have different processes running in the same container, whereas docker advises running a container per (functional) process. Maybe you could split your container in two?

**Comment by Mactory** [comment]
There is the possibility of customizing the nginx config for your container / hostnames and send the requests for different hostnames to different ports, but that basically means you are configuring nginx manually and you don't really have an advantage with using nginx-proxy. 
As @haster stated: different services should run in different Docker containers and that is what nginx-proxy is built for.
Maybe you can tell us some details about why you need this single-container, multi-port setup?

**Comment by soulawaker** [comment]
I have a Clojure backed container. It has a HTTP-server and a Network REPL server. They can be controlled by Clojure development tools. The NREPL enables to interactive development even on remote environments. Clojure and Clojurescript enable to develop server and client side interactively and simultaneously, especially with Figwheel. Figwheel watches client side code changing and change automatically rendered pages in a web browser. For this Figwheel needs a browser's web socket. I want to assign another URL for Figwheel. Surely I know some methods without Docker Nginx proxy settings. I've just wanted to know more convenient way exist in this Docker Nginx proxy. Thanks @haster and @Mactory .

**Comment by haster** [comment]
Ah, well, if this is only for development (ie, local) purposes, you might get somewhere by using the socat container (https://hub.docker.com/r/bortels/socat/) or something similar that forwards its port to the 2nd port of your main container. Then you can register the socat container under your 2nd url.

It's a bit of a hack but it might work for your purposes.

**Comment by jbq** [comment]
I have the same need to be able to assign multiple vhosts/ports pairs for a single container.  My usecase is Nexus OSS repository: it exposes a specific port for Docker registry, and another for Maven/NPM stuff.  Seems like I have to keep Traefik for this.

**Comment by lnryan** [comment]
I also have a scenario where I would like to have multiple ports either on the same virtual_host or separate ones.  This is basically because i was to provide a wrapper docker around node apps. The node app itself would always have PORT 80, but I was to be able to automatically provide a different PORT (eg 8001) for managing & monitoring the wrapped app.

**Comment by frederikbosch** [comment]
See PR #1157.

**Comment by soulawaker** [comment]
Good news! I'll see it later. :thumb-up.

2018년 7월 31일 (화) 오전 4:25, Frederik Bosch <notifications@github.com>님이 작성:
