### ISSUE TITLE
Changing worker_processes

### ISSUE THREAD

**Issue by davidbnk** [nginx-proxy/nginx-proxy#1043]
Is there any reason for `worker_processes` being set to `1`? Is it ok to change it to `auto`? If not, how to have multiple processes of nginx in the same server?

**Comment by davidbnk** [comment]
Anyone? Only one worker process sometimes get overloaded

**Comment by buchdag** [comment]
`worker_processes` shouldn't be set to `1`, it was changed to `auto` back in 2017 

#851 
1867228ccee886090bd24061c06080618fa952d3
a3cd96ead45911b27c3f20ab6cb0c092b466b366
