### ISSUE TITLE
Publish new docker-gen 0.7.4 and nginx-proxy to docker hub

### ISSUE THREAD

**Issue by lagivan** [nginx-proxy/nginx-proxy#1047]
The latest release of docker-gen 0.7.4 is not available in docker hub. The latest version in docker hub is 0.7.3 that does not include important fixes, for example, for Amazon ECS.

Could you generate and push the latest releases?

**Comment by jwilder** [comment]
There is an PR here: https://github.com/jwilder/nginx-proxy/pull/1026.  Unfortunately, the tests are no longer passing and I have not had time to figure out what has broken.

**Comment by lagivan** [comment]
@jwilder actually I've realized that version 0.7.4 is also not sufficient. There are 3 additional commits that are also required to make Amazon ECS work - https://github.com/jwilder/docker-gen/compare/0.7.4...master
So when you publish new docker containers, please make sure to include those commits as well. So basically it will be next version 0.7.5 of docker-gen. So far I've built everything myself.

**Comment by easybe** [comment]
@jwilder let me know if I can help with this in some way.

**Comment by buchdag** [comment]
Closed by #1601
