### ISSUE TITLE
Disable HTTP/2 http2 option

### ISSUE THREAD

**Issue by deed02392** [nginx-proxy/nginx-proxy#1055]
Some of the applications behind `nginx-proxy` do not handle SPDY protocol errors well, for example by resetting the DOM and requiring a force reload of the pages. When these pages are supposed to be automatically refreshed so they can be monitored, this is a nuisance.

I cannot find much detail on how SPDY protocol errors occur but in my use case, I will not miss the usage of HTTP/2 anyway - can we get an ENVAR that allows us to disable HTTP/2 on the nginx installation?

**Comment by jalbstmeijer** [comment]
Hi, needed to hack nginx.tmpl to disable http/2. It was causing issues with setting up a websocket.
So this feature would be appreciated.
