### ISSUE TITLE
Connection Error when using https

### ISSUE THREAD

**Issue by LucaNerlich** [nginx-proxy/nginx-proxy#1171]
Hello,

ive setup the docker with the following command:

`docker run -d --name nginx-proxy-alpine \
--restart always \
-e ENABLE_IPV6=true \
-p 80:80 \
-v /data/jwilder/certs:/etc/nginx/certs:ro \
-v /etc/nginx/vhost.d \
-v /usr/share/nginx/html \
-v /var/run/docker.sock:/tmp/docker.sock:ro \
--label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
jwilder/nginx-proxy:alpine
`

and ive started my firefly iii docker like this:

`docker run -d --name firefly --restart always \
-v /data/firefly_iii/export:/var/www/firefly-iii/storage/export \
-v /datafirefly_iii/upload:/var/www/firefly-iii/storage/upload \
-p 90:80 \
-e FF_APP_ENV=local \
-e FF_APP_KEY=xxxx\
-e FF_DB_HOST=62.xxx.xxx.xxx:3306 \
-e FF_DB_NAME=xxx\
-e FF_DB_USER=xxx \
-e FF_DB_PASSWORD=xxx \
-e VIRTUAL_HOST=firefly.mydomain.de \
-e VIRTUAL_PORT=90 \
-e LETSENCRYPT_HOST=firefly.mydomain.de \
-e LETSENCRYPT_EMAIL=xxx@xxxx \
jc5x/firefly-iii:latest`

**that worked fine for http.**
Ive then installed the letsencrypt companion docker as such:

`docker run -d --name nginx-proxy-letsencrypt \
--restart always \
-v /data/jwilder/certs:/etc/nginx/certs:rw \
-v /var/run/docker.sock:/var/run/docker.sock:ro \
--volumes-from nginx-proxy-alpine \
jrcs/letsencrypt-nginx-proxy-companion`

whenever I open firefly.mydomain.de I get **redirected to https and a connection error** straight in the browser. Using `docker exec  nginx-proxy-letsencrypt /app/cert_status` I can see, that the cert was created successfully. I am not getting anything in the logs for either  the nginx proxy or the letsencrypt companion.

Does anyone know, what I am doing wrong?
Thanks for the help :)
The http setup was straightforward and painless, I am impressed. Now im just trying to get it working for https.

**Comment by markussitzmann** [comment]
To me it looks like you forget to connect the proxy container also to 443, add -p 443:443 when starting nginx-proxy-alpine
