### ISSUE TITLE
Mozilla-Modern on :latest enables TLSv1.0

### ISSUE THREAD

**Issue by ruffy91** [nginx-proxy/nginx-proxy#1181]
I use the nginx-proxy:alpine build together with SSL_POLICY=Mozilla-Modern
This gives me only TLSv1.2 and an A+ on ssllabs.

I wanted to also support TLSv1.3 so i switched to nginx-proxy:latest which should support TLSv1.3
expected results: TLSv1.2 and TLSv1.3 enabled
real results: TLSv1.2 and TLSv1.0 enabled

**Comment by sehucke** [comment]
Same problem... very strange.

**Comment by ruffy91** [comment]
This now also happens lon nginx-proxy:alpine.
Any ideas how to fix this?

**Comment by guillaumedsde** [comment]
yep I'm also seeing this issue also on nginx-proxy:alpine

**Comment by NoahO** [comment]
I'm also seeing this issue.

**Comment by rakshazi** [comment]
Issue still here

**Comment by radoslav-stefanov** [comment]
I confirm Mozilla-Modern still keeps old protocols enabled.

**Comment by buchdag** [comment]
This should have been fixed by #2338
