### ISSUE TITLE
support both: http and https when valid SSL cert is available

### ISSUE THREAD

**Issue by Finkes** [nginx-proxy/nginx-proxy#121]
I'm using a self-signed SSL certificate and I want to support both: http and https to access my websites. The reason for that is that I have a jenkins server running inside a dicker container and it is not receiving any hook from github or bitbucket. Currently I always geht redirected to https when accesing my server. 
Maybe this could be done with a env variable (e.g. FORCE_HTTPS=FALSE) when starting nginx reverse proxy.

**Comment by Finkes** [comment]
For now I just use two reverse proxy: one is listening on port 80 and one only on port 443
>docker run --name reverseproxy_ssl -d -p 443:443 -v [...]
>docker run --name reverseproxy -d -p 80:80 -v [...]

**Comment by jakeslee** [comment]
Yes, I think this is very necessary. If I add a wildcard certificate to root domain, all subdomain will be forced to redirect to HTTPS. It is not my intent. Maybe setting a ENV to support two situations is better.

**Comment by atom2ueki** [comment]
@Finkes May I know how you let your new deployed container choose one of your reverse proxy ?

**Comment by Finkes** [comment]
I just serve all the containers via both proxies (http and https). I don't know how to achieve that only one reverseproxy will serve your container.

**Comment by ryneeverett** [comment]
Resolved #298's `HTTPS_METHOD=noredirect`?
