### ISSUE TITLE
Certificate Detection in Template closest Function mistaken another cert

### ISSUE THREAD

**Issue by kmtong** [nginx-proxy/nginx-proxy#1221]
I am very happy using nginx-proxy with letsencrypt-companion.

When we first created a service with hostname: "cmsbe.mydomain.com"
HTTPS obtained without any problem.

Then we have another service with hostname: "pcmsbe.mydomain.com"
HTTPS cannot be obtained in this case.
Having peek into the default.conf, the generated conf file uses the "cmsbe.mydomain.com" cert.

Looking at the source code, I suspect the closest function is the cupid which seems to try to use the certiciate file with the closest name, and in this case, it got "cmsbe.mydomain.com" obtained previously.

**Comment by buchdag** [comment]
This will be fixed by #2558
