### ISSUE TITLE
access via IP not host

### ISSUE THREAD

**Issue by mqliang** [nginx-proxy/nginx-proxy#1223]
Hi,  the docker-compose example need to access via host name:

```
$ docker-compose up
$ curl -H "Host: whoami.local" localhost
I'm 5b129ab83266
```

Is there anyway to configure so that I can access directly via IP, without specifying HOST?

**Comment by vietpharcom** [comment]
same with you.

**Comment by marknguyen85** [comment]
same with you.

**Comment by smcpeck** [comment]
@mqliang -- What is your use case?  You aren't guaranteed what the IP address will be for any given container, so hitting it directly sounds like an approach you'd want to rethink in your design.

**Comment by valmack** [comment]
@smcpeck This is what I am looking to do too. Currently running on a digital ocean droplet and don't want/need to register a domain name for this so I would like to be able to access this without a host header. I'm not a devops person (bear with me)--is it bad to assume my DO ip won't change?

**Comment by cocomice** [comment]
@mqliang   I guess then you don't need to use Nginx in that case...

**Comment by max-prtsr** [comment]
try`VIRTUAL_HOST=your_ip`
