### ISSUE TITLE
Issue with recent container update and SSL

### ISSUE THREAD

**Issue by samara8609** [nginx-proxy/nginx-proxy#1226]
I'm seeing the below error when recently updating the container (within the last 24-48 hours)

nginx.1    | 2019/01/30 02:25:16 [emerg] 33#33: PEM_read_bio_DHparams("/etc/nginx/dhparam/dhparam.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
nginx.1    | nginx: [emerg] PEM_read_bio_DHparams("/etc/nginx/dhparam/dhparam.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)

Nothing in my compose has changed in the last few weeks, i'm not sure whats causing this to break now.  I've gone thru and deleted the configs and let it try to recreate them with the same issue.  Attached is the compose i'm using.
[nginx-sample.txt](https://github.com/jwilder/nginx-proxy/files/2810666/nginx-sample.txt)

**Comment by pauldalewilliams** [comment]
I'm not sure if/how it may be related, but I had the same issue and upon digging into it came across this:  https://github.com/jwilder/nginx-proxy/pull/955

I ended up changing that line to point to the certs directory instead of dhparam since that's where my dhparam file exists.  Once I did that, everything was back to normal.  Not sure why it was only triggered with this newest image though.

**Comment by alaincao** [comment]
Hello, just to add my 2cents,
this problem seem to appear only in image "jwilder/nginx-proxy:latest" but not in "jwilder/nginx-proxy:alpine"

**Comment by flayks** [comment]
Same problem, it broke my nginx system after the update :/

**Comment by jakejarvis** [comment]
Switching to Alpine is the only way I could get back up and running too. Seems to be behaving exactly the same as the Debian version though (as it should!) so if you need to get back up ASAP then that's the image I'd recommend pulling in the meantime.

**Comment by flayks** [comment]
> Switching to Alpine is the only way I could get back up and running too. Seems to be behaving exactly the same as the Debian version though (as it should!) so if you need to get back up ASAP then that's the image I'd recommend pulling in the meantime.

I removed the 'dhparam.pem' I had and used the 'alpine' version of nginx-proxy, seems to get my sites back online. But this sounds definitely like a bug

**Comment by Jules-Baratoux** [comment]
Same issue. I could get `jwilder/nginx-proxy:0.6.0` to work :)

**Comment by JoshGlazebrook** [comment]
Still having this issue.

**Comment by maxguru** [comment]
Current version is still broken. :-1:

**Comment by coderdiaz** [comment]
The `latest` version isn't work!

**Comment by TroelsL** [comment]
Same issue. Switching to alpine was sufficient for me.

**Comment by mhlsf** [comment]
Hello guys I don't know if it's link but I had the same issue as you and I made a git init in the folder where my docker-compose file was. Then I made a git status and there was a lot file that seems link to the container (see following) but I couldn't see them with a ls -al but the file aren't there. I had no idea where they came from.

`root@vps613415:/srv/nginx-proxy# git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    Dockerfile.alpine
	deleted:    LICENSE
	deleted:    Makefile
	deleted:    Procfile
	deleted:    README.md
	deleted:    dhparam.pem.default
	deleted:    docker-compose-separate-containers.yml
	deleted:    docker-compose.yml
	deleted:    docker-entrypoint.sh
	deleted:    generate-dhparam.sh
	deleted:    network_internal.conf
	deleted:    nginx.tmpl
	deleted:    test/README.md
	deleted:    test/certs/README.md
	deleted:    test/certs/ca-root.crt
	deleted:    test/certs/ca-root.key
	deleted:    test/certs/create_server_certificate.sh
	deleted:    test/conftest.py
	deleted:    test/lib/ssl/dhparam.pem
	deleted:    test/pytest.ini
	deleted:    test/pytest.sh
	deleted:    test/requirements/Dockerfile-nginx-proxy-tester
	deleted:    test/requirements/README.md
	deleted:    test/requirements/build.sh
	deleted:    test/requirements/python-requirements.txt
	deleted:    test/requirements/web/Dockerfile
	deleted:    test/requirements/web/entrypoint.sh
	deleted:    test/requirements/web/webserver.py
	deleted:    test/stress_tests/README.md
	deleted:    test/stress_tests/test_deleted_cert/README.md
	deleted:    test/stress_tests/test_deleted_cert/certs/web.nginx-proxy.crt
	deleted:    test/stress_tests/test_deleted_cert/certs/web.nginx-proxy.key
	deleted:    test/stress_tests/test_deleted_cert/docker-compose.yml
	deleted:    test/stress_tests/test_deleted_cert/test_restart_while_missing_cert.py
	deleted:    test/stress_tests/test_deleted_cert/tmp_certs/.gitignore
	deleted:    test/stress_tests/test_unreachable_network/README.md
	deleted:    test/stress_tests/test_unreachable_network/docker-compose.yml
	deleted:    test/stress_tests/test_unreachable_network/test_unreachable_net.py
	deleted:    test/test_DOCKER_HOST_unix_socket.py
	deleted:    test/test_DOCKER_HOST_unix_socket.yml
	deleted:    test/test_composev2.py
	deleted:    test/test_composev2.yml
	deleted:    test/test_custom/my_custom_proxy_settings.conf
	deleted:    test/test_custom/my_custom_proxy_settings_bar.conf
	deleted:    test/test_custom/test_defaults-location.py
	deleted:    test/test_custom/test_defaults-location.yml
	deleted:    test/test_custom/test_defaults.py
	deleted:    test/test_custom/test_defaults.yml
	deleted:    test/test_custom/test_location-per-vhost.py
	deleted:    test/test_custom/test_location-per-vhost.yml
	deleted:    test/test_custom/test_per-vhost.py
	deleted:    test/test_custom/test_per-vhost.yml
	deleted:    test/test_custom/test_proxy-wide.py
	deleted:    test/test_custom/test_proxy-wide.yml
	deleted:    test/test_default-host.py
	deleted:    test/test_default-host.yml
	deleted:    test/test_dockergen/.gitignore
	deleted:    test/test_dockergen/test_dockergen_v2.py
	deleted:    test/test_dockergen/test_dockergen_v2.yml
	deleted:    test/test_dockergen/test_dockergen_v3.py
	deleted:    test/test_dockergen/test_dockergen_v3.yml
	deleted:    test/test_events.py
	deleted:    test/test_events.yml
	deleted:    test/test_headers/certs/web.nginx-proxy.tld.crt
	deleted:    test/test_headers/certs/web.nginx-proxy.tld.key
	deleted:    test/test_headers/test_http.py
	deleted:    test/test_headers/test_http.yml
	deleted:    test/test_headers/test_https.py
	deleted:    test/test_headers/test_https.yml
	deleted:    test/test_ipv6.py
	deleted:    test/test_ipv6.yml
	deleted:    test/test_multiple-hosts.py
	deleted:    test/test_multiple-hosts.yml
	deleted:    test/test_multiple-networks.py
	deleted:    test/test_multiple-networks.yml
	deleted:    test/test_multiple-ports/test_VIRTUAL_PORT.py
	deleted:    test/test_multiple-ports/test_VIRTUAL_PORT.yml
	deleted:    test/test_multiple-ports/test_default-80.py
	deleted:    test/test_multiple-ports/test_default-80.yml
	deleted:    test/test_multiple-ports/test_single-port-not-80.py
	deleted:    test/test_multiple-ports/test_single-port-not-80.yml
	deleted:    test/test_nominal.py
	deleted:    test/test_nominal.yml
	deleted:    test/test_ssl/certs/nginx-proxy.tld.crt
	deleted:    test/test_ssl/certs/nginx-proxy.tld.key
	deleted:    test/test_ssl/certs/web2.nginx-proxy.tld.crt
	deleted:    test/test_ssl/certs/web2.nginx-proxy.tld.key
	deleted:    test/test_ssl/certs/web3.nginx-proxy.tld.crt
	deleted:    test/test_ssl/certs/web3.nginx-proxy.tld.key
	deleted:    test/test_ssl/test_dhparam.py
	deleted:    test/test_ssl/test_dhparam.yml
	deleted:    test/test_ssl/test_dhparam_generation.py
	deleted:    test/test_ssl/test_dhparam_generation.yml
	deleted:    test/test_ssl/test_hsts.py
	deleted:    test/test_ssl/test_hsts.yml
	deleted:    test/test_ssl/test_nohttp.py
	deleted:    test/test_ssl/test_nohttp.yml
	deleted:    test/test_ssl/test_nohttps.py
	deleted:    test/test_ssl/test_nohttps.yml
	deleted:    test/test_ssl/test_noredirect.py
	deleted:    test/test_ssl/test_noredirect.yml
	deleted:    test/test_ssl/test_wildcard.py
	deleted:    test/test_ssl/test_wildcard.yml
	deleted:    test/test_ssl/wildcard_cert_and_nohttps/README.md
	deleted:    test/test_ssl/wildcard_cert_and_nohttps/certs/default.crt
	deleted:    test/test_ssl/wildcard_cert_and_nohttps/certs/default.key
	deleted:    test/test_ssl/wildcard_cert_and_nohttps/certs/web.nginx-proxy.tld.crt
	deleted:    test/test_ssl/wildcard_cert_and_nohttps/certs/web.nginx-proxy.tld.key
	deleted:    test/test_ssl/wildcard_cert_and_nohttps/docker-compose.yml
	deleted:    test/test_ssl/wildcard_cert_and_nohttps/test_wildcard_cert_nohttps.py
	deleted:    test/test_wildcard_host.py
	deleted:    test/test_wildcard_host.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docker-compose.yaml
	docker-compose.yaml2
	html/

no changes added to commit (use "git add" and/or "git commit -a")
`

But then I copy my docker-compose file in a new unrelated folder and the bug disappear so I think it might be link but I don't have enough knowledge of linux filesystem to understand what the issue.

Anyway try to copy your docker-compose file in a new folder and make docker-compose up it might temporary solve the issue `here.

**Comment by buchdag** [comment]
This should have been fixed by #1213, but Dockerhub autobuild seems to be broken for this repository and `latest` currently appears to be stuck at 7dd97d4bc39357b167327ff2a5d1aec869634cf5

**Comment by buchdag** [comment]
This should finally be fixed in `latest` now that #1279 has been taken care of.

**Comment by jakejarvis** [comment]
> This should finally be fixed in `latest` now that #1279 has been taken care of.

Can also confirm! Thanks a lot, @buchdag!

**Comment by buchdag** [comment]
Render unto Caesar [etc], the actual fix was made by @seroron with #1213

**Comment by coderdiaz** [comment]
@gatero The issue has fixed 🚀

**Comment by buchdag** [comment]
fixed by #1213
