### ISSUE TITLE
Release more often

### ISSUE THREAD

**Issue by MarcusWichelmann** [nginx-proxy/nginx-proxy#1228]
Hi, and thank you for your awesome work.

Could you please think about a release schedule and create releases more often?
Especially for production environments it's important to target against stable releases instead of using the atest` tag which might break systems from one day to another.

Kind regards,
Marcus

**Comment by easybe** [comment]
@jwilder would it be possible to simply tag the current `latest` as `0.8.0`?

Same as @MarcusWichelmann we need to be able to reference a versioned tag in production. 
Unfortunately, I have wasted quite some time chasing a bug which is fixed now on master.
In general, I am really happy with this image, thanks for the great work.

Cheers,
Ezra.

**Comment by kaishin** [comment]
I second this. @jwilder Any plans to address this?

**Comment by schmunk42** [comment]
Ping @jwilder

**Comment by rodrigoaguilera** [comment]
I love that the project is getting new maintainers under an org namespace.
@buchdag Do you plan to make tagged releases?

**Comment by buchdag** [comment]
Yep.
