### ISSUE TITLE
missing location entry for /.well-known/acme-challenge

### ISSUE THREAD

**Issue by niondir** [nginx-proxy/nginx-proxy#1260]
Using the whoami container, the letsencrypt companion fails with the acme challenge with the following error:

`The key authorization file from the server did not match this challenge [fqvo7EMt3FproyHpaj1Px_8zCxRLWT1JIdLSOMf6BHs.NqYcW6akigWo7F0LafjZce7-dZburlUCXcaokbzQpog] != [I'm 48eb0e93ea6e]`

I had to add the following to my http server directive in nginx.tmpl
```
    location /.well-known/acme-challenge {
            root /usr/share/nginx/html/;
            break;
    }
```

Is this a bug, or did I miss something?

**Comment by buchdag** [comment]
This should have been fixed on `acme-companion`'s end a while ago.
