### ISSUE TITLE
OpenSSL version update, TLSv1.3 support

### ISSUE THREAD

**Issue by attilakis** [nginx-proxy/nginx-proxy#1267]
Hello

I'm using the `jwilder/nginx-proxy:alpine` docker image. When I check nginx version, I got this:

`
nginx version: nginx/1.14.1
built by gcc 6.4.0 (Alpine 6.4.0) 
built with OpenSSL 1.0.2p  14 Aug 2018
`

from nginx version 1.13, TLSv1.3 is supported, but related to OpenSSL, OpenSSL 1.1.1 release includes support for TLSv1.3.

In my understanding, TLSv1.3 can't be used properly without OpenSSL support. (handshake not supported) 

Is there a version update planned, or am I missing something related to TLSv1.3?

Thanks,
Attila

**Comment by Kiina** [comment]
If you build the proxy from a newer docker image, it uses alpine [3.9](https://github.com/nginxinc/docker-nginx/commit/2364fdc54af554d28ef95b7be381677d10987986) which ships with OpenSSL 1.1.1. You can cherry-pick this pull request and build the image and should get TLSv1.3:

https://github.com/jwilder/nginx-proxy/pull/1225
