### ISSUE TITLE
WebSocket (HTTPS with upstream HTTP)

### ISSUE THREAD

**Issue by andrefernandes** [nginx-proxy/nginx-proxy#128]
WebSocket connections are failing on me. :(

My scenario is the common case of HTTPS with a HTTP upstream. Browser sends requests with "wss:" protocol and gets a 400 error code.

I did mess around with the template, but I don't think I broke it. Should "ws:" and "wss:" protocols work with nginx-proxy?

**Comment by olivierpascal** [comment]
+1, same error, but with HTTP also.

```
WebSocket connection to 'ws://mydomain.com/sockjs/043/j65rsyux/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
```

**Comment by md5** [comment]
Can either of your provide logs from `docker logs` for your `nginx-proxy` container when this error occurs?

**Comment by simonpure** [comment]
@md5 I'm hitting the same error. There's no error in the logs and it looks like a regular GET request for me.

CloudFlare is handling the https portion and then terminates at the proxy.

Let me know if I can provide additional details.

Thanks!

Browser
```
WebSocket connection to 'wss://www.openitem.io/' failed: Error during WebSocket handshake: Unexpected response code: 200
```

nginx-proxy
```
nginx.1    | www.openitem.io 162.158.255.218 - - [12/Mar/2016:23:05:26 +0000] "GET / HTTP/1.1" 200 165 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36"
```

**Comment by BenHall** [comment]
I'm using my branch - https://github.com/benhall/nginx-proxy/tree/websockets - which has been working well for us. I'll send a pull request.

**Comment by simonpure** [comment]
@BenHall Thanks for the response. I'll give your image @ https://hub.docker.com/r/benhall/nginx-proxy/ a shot.

**Comment by simonpure** [comment]
FYI - No luck so far and experiencing the same issue. If I bypass CloudFlare and do http/ws, it works fine.

**Comment by BenHall** [comment]
Oh, yeah we also have to bypass CloudFlare. I split www. (via CF) and ws. (direct)

**Comment by calbertts** [comment]
I'm having this issue scaling a Socket.IO server, with a single node it works fine, but once I try to scale, I start to see this error (400 bad request) in the browser console.

**Comment by BenHall** [comment]
@calbertts Make sure you're using sticky sessions or have Socket.IO running in a distributed way, otherwise the session IDs may not match

**Comment by calbertts** [comment]
I'm using Nginx, Redis and Docker, the Nginx ¡is supposed to be configured to deal with websockets, once I run the services works fine as long as every one is one single node, when I scale the Socket.IO server it starts to fail.. do I have to use sticky sessions anyaway?

**Comment by calbertts** [comment]
Keep in mind I'm not using the cluster module in NodeJS.

**Comment by calbertts** [comment]
I was able to solve this by using these options from client:

`io('/', {secure: false, transports: ["websocket","flashsocket","polling"]})`

**Comment by rraj-gautam** [comment]
> I'm using Nginx, Redis and Docker, the Nginx is supposed to be configured to deal with websockets, once I run the services works fine as long as every one is in a single node, when I scale the Socket.IO server it starts to fail.. do I have to use sticky sessions anyaway?

Exactly I had the problem with sticky session, not on nginx, but on my nodejs server.

**Comment by tkw1536** [comment]
Looks like the same issue can be found [in discussions](https://github.com/nginx-proxy/nginx-proxy/discussions/1670). 
Closing this issue, if it is still relevant please reopen or post a question in the discussion.

>
