### ISSUE TITLE
Implement rules for location /

### ISSUE THREAD

**Issue by DominMuda** [nginx-proxy/nginx-proxy#1286]
I want to implement some custom nginx rules for location / but if I write this rule using vhost.de/domainname.conf I get that there are duplicate rules for / location, because this rule doesn't replace the existing rule in default.conf, but adds instead.

I have been looking into plenty of ways to do this. I have overwritten the rule in default.conf myself and it works if I run

`docker exec -it nginx-proxy nginx -s reload`

Restarting the container will make my change get just lost since docker-gen reconstructs this "default.conf". I think there is no current way to overwrite rules for / location. Is there any chance this gets implemented any time soon?

**Comment by linrong** [comment]
I also encountered this problem, I am looking for a way to override the automatically generated location / or can modify the automatically generated forwarded location prefix by configuration

**Comment by Brainscrewer** [comment]
+1. This would be great. It does not matter if you are using a vhost.d/VIRTUAL_HOST or a vhost.d/VIRTUAL_HOST_location file. I only want to change the proxy_pass value in location /. This currently does not work with both approaches described in the README.

**Comment by DominMuda** [comment]
Just saw that my feature was implemented as a merge request but haven't been merged so far.
#1179

**Comment by passerbythesun** [comment]
Now I understand why nextclould docker-compose examples use nginx-proxy plus another nginx to serve php-fpm, but I really dont want two nginx.

**Comment by cesc1802** [comment]
> +1. This would be great. It does not matter if you are using a vhost.d/VIRTUAL_HOST or a vhost.d/VIRTUAL_HOST_location file. I only want to change the proxy_pass value in location /. This currently does not work with both approaches described in the README.

do you have any file to config it, because i dont know how can i do this feature

**Comment by jacktheripper19** [comment]
Until they merge the pull request that allows overriding location / , I just generate the default conf once when my containers are all up, then I comment the line dockergen: docker-gen -watch -notify "nginx -s reload" /app/nginx.tmpl /etc/nginx/conf.d/default.conf in /app/Procfile. 
This line is the one telling dockergen to override default.conf every restart. Now any modification to default.conf will not be overridden.
