### ISSUE TITLE
Start the Container under a arm32v7 environment

### ISSUE THREAD

**Issue by BMWfan** [nginx-proxy/nginx-proxy#1317]
Hello,

i have docker running on my raspberry pi 4b with 4 GB RAM.

I want to use the nginx-proxy but there was not separate arm32v7 container thatswhy i was pulling it from the git repository and changing the docker-compose.yml to:
#####################
version: '2'
services:
  nginx-proxy:
    build: .
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
#####################

I started it with 'docker-compose up' and got the following message as latest:
`nginx-proxy    | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx-proxy    | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
nginx-proxy    | /app/docker-entrypoint.sh: line 34: /usr/local/bin/forego: cannot execute binary file: Exec format error
nginx-proxy    | /app/docker-entrypoint.sh: line 34: /usr/local/bin/forego: Success
nginx-proxy exited with code 1
`

Has someone a idea how i could fix this?

Greetings

Daniel

**Comment by ahmedabt** [comment]
It requires arm32v7 docker image. it would be really nice if they supported ARM variant.

**Comment by BMWfan** [comment]
@ahmedabt i totally agree it would be helpful i think not only for us. Many peoples are using a raspberry pi as a hardware plattform for example which requires a arm32v7 docker image. Do you know how we could proceed to get it?

**Comment by ahmedabt** [comment]
@BMWfan No I don't know how to proceed, but I just had a look on the docker file and found it depends on Nginx, forego, and docker-gen.

Nginx already has arm32v7 version while forego and docker-gen are based on golang so theoretically you build armv7 version for both of them too.

If it is really needed by others as well, I can fork and maintain an armv7 version. Do you know few other people who would like to join?

**Comment by BMWfan** [comment]
@ahmedabt here you find already opened issues which are mostly all depending on this behaviour:
[https://github.com/jwilder/nginx-proxy/issues?utf8=%E2%9C%93&q=raspberry](url)

**Comment by IoTPlay** [comment]
Hello @jwilder, will we have an ARM docker impage on hub soon?
Thank you for your work.

**Comment by valvanet** [comment]
bumb

o/

**Comment by buchdag** [comment]
Fixed as of #1470 + 4a1d5bfc58af35f5e90dcefb47b35a274c903150 + d120ce9fdebf09a6c7b90ecff7eda0b7d2760ef3
