### ISSUE TITLE
Custom Nginx Error Messages?

### ISSUE THREAD

**Issue by dm17** [nginx-proxy/nginx-proxy#1325]
It seems like most people use CDNs for this type of functionality these days, but is there some way to have "site will be back momentarily" sign until all of the nginx-proxy-fed docker services finish starting? This seems like a pretty common use case, so I figured someone here would have a good suggestion or extensions they've written to do this. So if visiting the domain while the services are still coming up - instead of seeing an nginx error (meaningless to most people) - it shows a "please check back in a few moments" message.

I had previous posted this in the wrong project:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/574

**Comment by hasnat** [comment]
in vhost.d nginx config for your container have something like
```
        error_page 503 = @custom_error;
        location @custom_error {
                internal;
                return 503 'please check back in a few moments';
        }
```
not 100% if its 503 or some other error you have to cover.

**Comment by dm17** [comment]
Great, very useful... But how do I get it so the error appears immediately in the browser. If the site isn't up and this gets triggered, then it seems the browser will always display this first:

Attackers might be trying to steal your information from [domain] (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID

Then you have to click twice to proceed.

**Comment by iNviNho** [comment]
@dm17 I dont think you can do anything with that. Browser remembers that site is being loaded over HTTPS and if your site is down/certificate is invalid, user will get this error from browser.

**Comment by sgabe** [comment]
Note that you might want to use the `proxy_intercept_errors on;` directive to intercept and redirect proxied error responses to nginx for processing with the `error_page` directive in order to prevent information exposure through error messages.
