### ISSUE TITLE
location file

### ISSUE THREAD

**Issue by sbcrumb** [nginx-proxy/nginx-proxy#1330]
I am trying to insert/use this in my location file

`location ~ /Videos/([A-Za-z0-9]+)/stream {
    proxy_pass http://127.0.0.1:9988/stream/ff5ffe05932e4f94991e91389a87168a/$1/8096/;
  }`

But when it is called I get
`nginx.1    | 2019/09/11 12:19:03 [error] 36#36: *265 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xxx.xxx, server: emby.whaleseal.com, request: "GET /emby/Videos/42161/stream?static=true&PlaySessionId=58bbd18e0200477498af173beef5bf10&MediaSourceId=510503db70f75ef766359fb3167d638c&api_key= HTTP/1.1", upstream: "http://127.0.0.1:9988/stream/ff5ffe05932e4f94991e91389a87168a/42161/8096/", host: "somedomain.com"`

**Comment by buchdag** [comment]
Closing due to issue's age, feel free to re-open if it's still relevant.
