### ISSUE TITLE
Google Group Not working?

### ISSUE THREAD

**Issue by thenetimp** [nginx-proxy/nginx-proxy#1341]
Tried the google group so I could ask my question, but I get this message

'This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.'

So where should I ask my question?

**Comment by tkw1536** [comment]
I think the google group has been deleted and the link should probably be deleted from the README.

**Comment by buchdag** [comment]
We're now using [GitHub Discussions](https://github.com/nginx-proxy/nginx-proxy/discussions).
