### ISSUE TITLE
Google Group does not exist?

### ISSUE THREAD

**Issue by leoc** [nginx-proxy/nginx-proxy#1349]
https://groups.google.com/forum/#!forum/nginx-proxy Does not seem to exist or is not public?

I get error messages following the link and cannot find the group by searching manually.

**Comment by tcarecolin** [comment]
I have the same issue here want to asks some questions without polluting issues -_-

**Comment by tkw1536** [comment]
Duplicate of #1378 and #1502.

**Comment by buchdag** [comment]
We're now using [GitHub Discussions](https://github.com/nginx-proxy/nginx-proxy/discussions).
