### ISSUE TITLE
Enabling gzip?

### ISSUE THREAD

**Issue by dm17** [nginx-proxy/nginx-proxy#1352]
I thought this would be default or super common, but I googled a bit and only saw non-docker nginx guides for enabling. So I wonder if there is any difference for enabling gzip for jwilder's nginx-proxy.
Thanks.

**Comment by dm17** [comment]
OK, this thread seems to have some answers: https://github.com/jwilder/nginx-proxy/issues/139
Is this something that needs to be passed per VHOST?

**Comment by tkw1536** [comment]
Closing in favor of #139
