### ISSUE TITLE
Need help, google group is down

### ISSUE THREAD

**Issue by artbred** [nginx-proxy/nginx-proxy#1378]
I have a docker container with a websocket inside. I need to have access to different container with websockets from one address. How do I do that? Many thanks

**Comment by hacker-h** [comment]
The google group is not down:
https://groups.google.com/forum/#!forum/nginx-proxy

**Comment by tkw1536** [comment]
I get this message when trying to access that link. 
<img width="556" alt="Screen Shot 2020-06-27 at 11 22 07" src="https://user-images.githubusercontent.com/2923242/85919077-85da3080-b868-11ea-9bce-79cd0bf6d26c.png">

**Comment by brian32768** [comment]
I get the same message. There is no group. 

Searching in Google Groups currently finds a different group, nginx-aws-auth
There is no "Join" button until you actually find an existing group. No group shows up, so no JOIN.

SUGGESTION: change the README to put a functioning link there or instructions on how to access the group.

**Comment by beechfuzz** [comment]
I can also confirm the group is down.  I get the same message as @tkw1536 .

**Comment by hacker-h** [comment]
now it is down for me as well

**Comment by buchdag** [comment]
We're now using [GitHub Discussions](https://github.com/nginx-proxy/nginx-proxy/discussions).
