### ISSUE TITLE
Pass-Through

### ISSUE THREAD

**Issue by johnjelinek** [nginx-proxy/nginx-proxy#138]
I have an internal DNS that round-robins requests to different servers with that service. Do I need a container to just point at the internal DNS so public traffic is served by one of my instances in the network?

Example:
I want to map gitlab.johnjelinek.com to gitlab.service.consul (3 instances respond to this) and have nginx-proxy hold the SSL cert.

**Comment by white-gecko** [comment]
Did you figure out, how to use the nginx-proxy to serve as proxy for services in the local network?

**Comment by tkw1536** [comment]
duplicate of #998
