### ISSUE TITLE
[Question] How to use nginx-proxy with many ports?

### ISSUE THREAD

**Issue by fco4** [nginx-proxy/nginx-proxy#1382]
Hi there,
Is it possible to use nginx-proxy with many ports? For example: I have a container with two exposed ports 80 and 8181.

I want to be able to access a container with two open ports like this:
http://somesubdomain.domain.com and http://somesubdomain.domain.com:8181

Is it possible?

**Comment by ja573** [comment]
Instead of opening a new question I'd like to expand on this one. how about being able to also specify the combination of domain and ports, e.g. api.test.com on port 9000 and test.com on port 8080

**Comment by RomanXT** [comment]
I also have a problem with port forwarding.
Example
container 1 at https://exmaple.com:2000
container 2 at https://exmaple.com:3000
container 3 at https://exmaple.com:4000
I do not know how to do this??

**I cannot make a subdomain**, I use with:
letsencrypt-nginx-proxy-companion

**Comment by JulesRenz** [comment]
Check out [pull request 259](https://github.com/nginx-proxy/nginx-proxy/pull/259)

It has been stale for a while but is still needed imho

**Comment by luzik** [comment]
Is it possible to achieve this using "Per-VIRTUAL_HOST" ? Can someone provide example conf ?
