### ISSUE TITLE
Support for Mail Proxy Server

### ISSUE THREAD

**Issue by kravemir** [nginx-proxy/nginx-proxy#1394]
I'm currently setting up SSL for [tomav/docker-mailserver](https://github.com/tomav/docker-mailserver) according to the [guide, which requires to expose all certificates to the mail server](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL).

I don't like to expose all certificates to anything else, than nginx-proxy and letsencrypt-companion. And, nginx supports to be configured also as [Mail Proxy Server](https://docs.nginx.com/nginx/admin-guide/mail-proxy/mail-proxy/). So, I am considering to setup nginx as SSL termination point for email/IMAP/SMTP server.

**Comment by jwilder** [comment]
This project does not support mail server proxying out of the box.  You could potentially do it via a custom template.
