### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by batesenergy** [nginx-proxy/nginx-proxy#1403]
I am using the 3 container setup to reverse proxy my docker stack. I need to support MQTT messaging and cannot figure out how to allow for communication on port 1883/9001 as per the standard. I tried adding 1883 to the open ports on the nginx service but it seems that there is something catching the requests that i'm unaware of. 

Does anyone have any experience with this?

I have been looking at this article but am not sure how i would change the nginx.tmpl file to make this work. 

[https://www.nginx.com/blog/nginx-plus-iot-load-balancing-mqtt/#mqtt-load-balance](url)

**Comment by guillermoprados** [comment]
I'm facing something similar.. I mean, I don't have problems communicating from outside the networ.., I can connect to my mqtt server using the dns, and the proxy does its job. 

My problem is when I want to connect from another container inside the docker network. The thing is that the container has an specific ip address that seems to be created on the fly (well is handled by nginx and is set as the upstream ip). Once I get that ip from the network, I can connect to it, but I would like to connect using "localhost" or some beforhand known ip :(

**Comment by PLCMercenary** [comment]
MQTT is not a TCP protocol. As it says right in the article that you are referencing, You have to add the streams module and the javascript engine. You will need to make a dockerfile that will add in the nginx streams, and build the javascript engine from source.

**Comment by batesenergy** [comment]
Great. I will look into this thanks for clarifying.
