### ISSUE TITLE
502 Bad Gateway, "default.conf" looks good but "docker logs" looks bad

### ISSUE THREAD

**Issue by SundialServices** [nginx-proxy/nginx-proxy#1411]
*(Topic title is based on an initial misunderstanding but apparently I can't change it now ...)*

I have what I think is exactly the setup prescribed in the documentation.  Easy peasy, development-only, no SSL ...  But I'm getting "Bad Gateway."

> `docker exec ... cat /etc/nginx/conf.d/default.conf` 

... seems to correctly identify the internal IP-address of the other-container of interest ... which means that scanning for `ENV VIRTUAL_HOST` obviously worked:

```
upstream my_site.local {
   [...]
   server 172.16.238.5:80    # CORRECT!
}
```

When I do `docker logs app_server` I see ... silence.  The web server isn't being contacted.

When I do `docker logs nginx_proxy` I see this:

```
failed (111: connection refused) while connecting to upstream, client 172.16.238.1; upstream "172.16.238.5:80/"
```

So, why isn't it connecting?  The target container does specify `EXPOSE 80` ...

**Comment by SundialServices** [comment]
Me bad.  I forgot this:

  - `VIRTUAL_PROTO=fastcgi`
  - `VIRTUAL_ROOT=/var/www/`

And also apparently important, in the `Dockerfile` for the PHP-FPM client:

  `EXPOSE 9000`

**Comment by Karamellwuerfel** [comment]
> Me bad. I forgot this:
> 
> * `VIRTUAL_PROTO=fastcgi`
> * `VIRTUAL_ROOT=/var/www/`
> 
> And also apparently important, in the `Dockerfile` for the PHP-FPM client:
> 
> `EXPOSE 9000`

After 5 hours of finding this issue **YOUR ANSWER WAS THE KEY!** Thank you so much!
