### ISSUE TITLE
How to Letsencrypt-companion to external server/ip? Possible in the first place?

### ISSUE THREAD

**Issue by damarges** [nginx-proxy/nginx-proxy#1433]
My VPS server is running wireguard! My computer at home is connected to this wireguard server. Both machines see and reach each other via their private LAN IPs assigned by wireguard.

On my home PC I have a webserver running. Now I want my VPS server, which runs nginx-proxy with letsencrypt-companion, to also SSLerize this IP from my homeserver.

So what I am actually looking for is something like:

`  wordpress:`
`    image: wordpress:4.7-apache`
`    environment:`
`      WORDPRESS_DB_PASSWORD: somepassword`
`      VIRTUAL_HOST: exampledomain.com`
`      VIRTUAL_SERVER: 10.10.10.2  `<<- which is the LAN IP from my private home pc connected via wireguard. is this possible?
`      LETSENCRYPT_HOST: exampledomain.com`
`      LETSENCRYPT_EMAIL: admin@exampledomain.com`

Is there an environment variable like the bold one above? 
I hope you understand what I want :)

Thanks in advance for any help

**Comment by buchdag** [comment]
> Is there an environment variable like the bold one above?

There isn't, so I doubt what you want to achieve is possible.

**Comment by damarges** [comment]
Solved it with a workaround:

[https://github.com/qoomon/docker-host/issues/34](url)

**Comment by sgabe** [comment]
@damarges If it has been resolved, please close this issue.
