### ISSUE TITLE
Implement a way to provide a custom list of ssl_ciphers

### ISSUE THREAD

**Issue by greenfoo** [nginx-proxy/nginx-proxy#1440]
In order to customize the list of ciphers nginx accepts, I created a new file ("custom.conf") with one single line:
```
ssl_ciphers 'ECDHE-ECDSA-AES128-CBC-SHA256';
```
...and then mounted it into the docker image with `-v custom.conf:/etc/nginx/conf.d/custom.conf`
However, because the `ssl_ciphers` option already exists in `default.conf`, the docker container fails to run with this error:
```
"ssl_ciphers" directive is duplicate in /etc/nginx/conf.d/custom.conf:1
```
On file [nginx.tmpl](https://github.com/nginx-proxy/nginx-proxy/blob/3cbc5417b7ac38037a9ec00fe80e0996d7da3d75/nginx.tmpl#L28) I see the different values `ssl_ciphers` can be initialized to depending on the value of environment variable `SSL_POLICY`.

It would be nice if `SSL_POLICY` also accepted the value `Custom` (or, maybe, `External`?), which would cause the `ssl_ciphers` line **not** to be included in `default.conf`, so that it can be provided in a custom configuration file.

PS: You might be wondering why would anyone want to provide a custom set of ciphers considering the current policies should cover all cases. Well... I also thought that until I tried to implement an Amazon Alexa endpoint behind nginx. It turns out that Amazon servers, when communicating with the endpoint, will send a `TLS Hello` message that only includes CBC ciphers, such as seen on the next screenshot, none of which are included in the default `SSL_POLICIES`.

![Screenshot from 2020-05-24 11-53-07](https://user-images.githubusercontent.com/42691086/82752754-95291280-9dc0-11ea-8617-24e60d24c5ba.png)

**Comment by greenfoo** [comment]
Hmmm... so maybe this is not needed after all (at least to solve the particular problem I was having with Alexa endpoints).

It turns out that `SSL_POLICY=AWS-TLS-1-2-2017-01` works with Alexa endpoints.

I never bothered to try this policy because the **naming** of the ciphers listed for `AWS-TLS-1-2-2017-01` on [nginx.temp](https://github.com/nginx-proxy/nginx-proxy/blob/3cbc5417b7ac38037a9ec00fe80e0996d7da3d75/nginx.tmpl#L44) did not match the naming inside the wireshark capture (screenshot from the previous post). In particular, there is no `CBC` substring on any of the `nginx.tmpl` ciphers... but it looks like `CBC mode` is implicit when `GCM` substring is not present and the following ciphers are actually the same:
```
nginx.tmpl                             wireshark capture equivalent
===============================================================================
ECDHE-ECDSA-AES128-GCM-SHA256          <none>
ECDHE-RSA-AES128-GCM-SHA256            <none>
ECDHE-ECDSA-AES128-SHA256              TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
ECDHE-RSA-AES128-SHA256                TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
ECDHE-ECDSA-AES256-GCM-SHA384          <none>
ECDHE-RSA-AES256-GCM-SHA384            <none>
ECDHE-ECDSA-AES256-SHA384              TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
ECDHE-RSA-AES256-SHA384                TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
AES128-GCM-SHA256                      <none>
AES128-SHA256                          TLS_RSA_WITH_AES_128_CBC_SHA256?
AES256-GCM-SHA384                      <none>
AES256-SHA256                          TLS_RSA_WITH_AES_256_CBC_SHA256?

```

So... maybe the selectable `SSL_POLICY`s are actually enough to cover all use cases and there is no need to provide a workaround to use a custom set of `ssl_ciphers`. If so, feel free to discard this ticket and sorry for having opened it in the first place.

**Comment by sgabe** [comment]
What you have discovered is that OpenSSL and IANA use different naming. The [testssl.sh](https://testssl.sh/) project provides a mapping [here](https://testssl.sh/openssl-iana.mapping.html). Can you please close this issue?
