### ISSUE TITLE
ASP.NET Core application not accessible through nginx-proxy

### ISSUE THREAD

**Issue by kobelobster** [nginx-proxy/nginx-proxy#1448]
# Context

I am using this docker image for my application which shall include a web site built with ASP.NET Core. However, when using in combination with this library, I cannot access my page.

# Actual

I have the following, simple `docker-compose.yaml`

```
version: '3'
services:
  nginx-proxy:
    privileged: true
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  staticcms:
    build:
      dockerfile: ./../../Docker/Dockerfile
      context: ./../StaticCMS/StaticCMS
    environment:
      - VIRTUAL_HOST=staticcms.local
```

The `Dockerfile` of the `staticcms` looks like this

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENV ASPNETCORE_URLS http://+:5000
EXPOSE 5000
ENTRYPOINT ["dotnet", "StaticCMS.dll"]
```

As you can see I have exposed port 5000. When I now start my docker-container by using `docker-compose up --remove-orphans --force-recreate --build` I would expect being able to navigate to this page in my browsesr by entering `staticcms.local`, however this is not happening. Instead I'm getting the default browser error page when a site cannot be found.

When I *manually* add the following line to my `staticcms` in the `docker-compose.yaml`

```
ports:
  - "5000:5000"
```

I can navigate to `http://localhost:5000` without any issues. So the services are up and running, but somehow nginx can't resolve it?! 

So, I went inside the `nginx` container and checked the contents of the `default.conf` which is

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# staticcms.local
upstream staticcms.local {
				## Can be connected with "docker_default" network
			# docker_staticcms_1
			server 172.18.0.2:5000;
}
server {
	server_name staticcms.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://staticcms.local;
	}
}
```

This also looks correctly configured. I also used another image `jwilder/whoami` and for this it works without any problems. Why are there problems here? Did anyone ever come across the same issue?

# Expected

 I would expect, that after starting the docker-container, I can access http://staticcms.local and see the same result as when adding port exposing to the `docker-compose` and navigate to http://localhost:5000

# Additional info

I'm successfully running a docker-compose file where I have

* `nginx`  
* `asp.net core application`   
* `sqlserver`  

all as separate containers running without any issues.

**Comment by 8jigarpatel** [comment]
I think I have found a work around for this issue, mate. Before you begin to read the work around solution, I just want to make it clear that I was trying to use `jwilder/nginx-proxy` and `jrcs/letsencrypt-nginx-proxy-companion` the same time (from a nice article: https://blog.harveydelaney.com/hosting-websites-using-docker-nginx/).
I am not sure if the issue I faced was caused by the combination of those or just one of them.

_Let's begin:_

Say your asp net core image is named `aspnetcoreapp`

**Step 1:** run a simple nginx container with `VIRTUAL_HOST` set to the URL you wish to use with your asp net core app (In your case, **staticcms.local**) (`LETSENCRYPT_HOST` and `LETSENCRYPT_EMAIL` are optional, if you wish to use those you will need to have **jrcs/letsencrypt-nginx-proxy-companion** running)

```
docker run -d \
--restart unless-stopped \
--name your-proxied-app \
--env "VIRTUAL_HOST=staticcms.local" \
--env "LETSENCRYPT_HOST=staticcms.local" \
--env "LETSENCRYPT_EMAIL=your@email.com" \
nginx
```


**Step 2**: run your asp net core container with same values for `VIRTUAL_HOST` (again, `LETSENCRYPT_HOST` and `LETSENCRYPT_EMAIL` are optional)

```
docker run -d \
--restart unless-stopped \
--name aspnetcoreapp \
--env "VIRTUAL_HOST=staticcms.local" \
--env "LETSENCRYPT_HOST=staticcms.local" \
--env "LETSENCRYPT_EMAIL=your@email.com" \
aspnetcoreapp
```

**Step 3**: remove the container that was created in step 1.

Let me know if this works for you :-)

**Comment by kobelobster** [comment]
Ok, so I found the error. The problem was, that there was no entry in my `/etc/hosts` file for my local urls. There was, however one for `whoami.local` so that's why that image worked, but not mine. Now I don't know if `whoami.local` is per default in fedora in the hosts file because if I understood this library correctly, this should all happen automatically right?

So two options

1. Yes, it should happen automatically -> Somehow my `/etc/hosts` file is not written to, even though i have `privilged: true`
2. I was too blind and didn't see the doc noting that I have to make those entries myself?

**Comment by 8jigarpatel** [comment]
honestly, I’m not too sure of those files you mentioned. I was just trying to get asp net core app proxied using this utility (along with ssl companion util), and while that worked for nginx stock docker image, it didn’t work for my asp net core 3.1 app. And that was when I figured something that I mentioned in my comment above works.

**Comment by AndrewTriesToCode** [comment]
I hit the same problem. I think the problem is the the default bridge network only connects containers based on IP address as shown here:
[https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge](https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge)

If you defined your own bridge network it should resolve by container name, so you could name your container `staticcms.local` or use an alias when starting the container.

This is only if you run nginx-proxy and your app on the same host. If they are on separate hosts then the overlay network should work similarly where it routes by container/service name.

**Comment by AndrewTriesToCode** [comment]
Update: no need to worry about container name. The trick was to attach both the proxy and the website containers to the custom network during the run command with the --network option. Apparently if either connects to the default bridge network something goes wrong.

I noticed the nginx conf file showed my upstream as down when I had the issue, but the one you pasted above shows it can connect--but it's still worth a try.

**Comment by kobelobster** [comment]
@AndrewTriesToCode - I will try that out this weekend and update! Thank you for your comment!

**Comment by kobelobster** [comment]
Okay, so a few notes

1.) I checked `/etc/hosts` on a freshly installed Fedora. There was no entry of `whoami.local` 
2.) When I added `xxx.local` manually to the `/etc/hosts` it instantly works

@AndrewTriesToCode Can you show a specific command that you run to make that work? I would try that as well and add it to my list.

**Comment by AndrewTriesToCode** [comment]
After more testing it appears the bridge network works fine -- I'm not sure if anything changed or I was doing anything wrong.

Regardless you shouldn't have to worry about the `hosts` file or anything. After you have nginx-proxy running and your website run this:
```
docker exec my-proxy cat /etc/nginx/conf.d/default.conf
```
To see how the proxy configured nginx. You should see the settings to redirect to your app and it should be using IP addresses. Can you post the output of that command?

**Comment by kobelobster** [comment]
```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# example.local
upstream example.local {
				## Can be connected with "example_default" network
			# example_example_1
			server 172.18.0.3:5000;
}
server {
	server_name example.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://example.local;
	}
}
```

It could also just be a Fedora related security thing. I whitelisted docker tho

```
sudo firewall-cmd --permanent --zone=trusted --add-interface=docker0
sudo firewall-cmd --permanent --zone=FedoraWorkstation --add-masquerade
```

but maybe that wasn't enough?

**Comment by AndrewTriesToCode** [comment]
Looks like it can see it ok. What happens when you run `curl --verbose --header "Host: example.local" http://localhost`? That should proxy the request to your app container.

**Comment by kobelobster** [comment]
```
* Could not resolve host: example.local
* Closing connection 0
curl: (6) Could not resolve host: example.local            
```

As soon as I add `127.0.0.1 example.local` to the `/etc/hosts` file I get, the exact same call gives me

```

*   Trying ::1:80...
* Connected to example.local (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: example.local
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: nginx/1.17.6
< Date: Mon, 06 Jul 2020 14:30:21 GMT
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host example.local left intact
```

So this seems to work. I can only imagine that this is something fedora security related

**Comment by AndrewTriesToCode** [comment]
Interesting, in your curl statement you used localhost and it gives you an error about example.local? I don’t use fedora so you are probably right but that’s an odd one.

**Comment by kobelobster** [comment]
Oh sorry, that was my bad. I didn't copy your code but instead typed it and didn't see that there's example.local and localhost. I just did a fresh install of Fedora (not related to this issue) and don't have the project files on my computer yet. I will try the exact same command again once I have everything set up again.

**Comment by AndrewTriesToCode** [comment]
Yeah in a real scenario the local host file is never used. A request gets routed to the box by IP externally and you can see from the nginx conf file it also forwards based on IP. So in theory at least the hosts file shouldn’t be in play.
