### ISSUE TITLE
Pushing new Images to DockerHub?

### ISSUE THREAD

**Issue by tkw1536** [nginx-proxy/nginx-proxy#1457]
I noticed that the last commit to master was on March 25, however the image version on [DockerHub](https://hub.docker.com/r/jwilder/nginx-proxy/tags) is from February 11th. 
As I want to make use of the new features, I was wondering when new images will be pushed?
Looking also at security patches (in particular those of `nginx` and other software in the images like `wget`) I am worried that they will not be applied to the images. 

Judging from other comments (e.g. https://github.com/nginx-proxy/nginx-proxy/pull/1402#issuecomment-609408046, https://github.com/nginx-proxy/nginx-proxy/pull/1113#issuecomment-633775844) as well as issues #1304 and #1427 it seems that people have similar concerns. As a workaround (that works for me, but might not solve it for others) I have scheduled automated nightly builds of the `master` branch on my server. I made an unofficial nginxproxy organization on DockerHub, and am pushing these images to [nginxproxy/nginx-proxy](https://hub.docker.com/r/nginxproxy/nginx-proxy). 

If there is interest, I am happy to donate my server time to push to the official DockerHub repo or give other people access to the `nginxproxy` organization.

**Comment by dromer** [comment]
nginx base containers have made some significant progress as well, so more up to date images are surely welcome!

**Comment by MarkErik** [comment]
@tkw1536 Thank you for raising the issue. I've been keenly following this Nginx-proxy project and hoping for updated Docker images too.

I'm still a novice with Docker, but as another workaround, would there be a drawback for me to manually pull the latest Dockerfile from this project, and include it as part of the build process in my docker-compose file?

**Comment by tkw1536** [comment]
@MarkErik yes, you could do that. You could clone this repository into a subfolder and then add

```yaml
# replace './nginx-proxy' with the name of the subfolder where the clone is
build: ./nginx-proxy
```
instead of 
```yaml
image: jwilder/nginx-proxy
```
in the docker-compose file. 

Some Caveats:
- You should either use ```docker-compose build``` or ```docker-compose up --build``` in that case. 
- If you're using the alpine variant, you probably want to add ```dockerfile: Dockerfile.alpine```. See also [the Compose File Reference](https://docs.docker.com/compose/compose-file/#build)

**Comment by MarkErik** [comment]
Thank you for responding.

I'm using the nice 3 container setup from: https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

That project provides a shell script to start everything, and so it is easy to add the extra build command.

**Comment by MarkErik** [comment]
@tkw1536 Thank you for your response. As I opened up my compose file I realised (oops!) that because I am using a 3 container setup from https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion I'm not directly using this container. But I have been following it to see what changes are being implemented. Thanks again, and I'll need to now do more reading to try to understand how the new changes in this project are related to my setup.

**Comment by DaleyKD** [comment]
I would love to see this project push a newer version... it looks like nginx is at 1.19.2?

**Comment by jwilder** [comment]
nginx-proxy:0.8.0 is on dockerhub now.

**Comment by DaleyKD** [comment]
Would I look a gift horse in the mouth to request the update for the alpine image, too?

**Comment by GunoH** [comment]
Is it me, or is alpine-0.8.0 missing from docker hub?
Earlier versions have alpine variants, but this one does not. I could probably use the _alpine_ tag instead and get the same results, but I like to rely on versions rather than latest.
