### ISSUE TITLE
dont work if started with docker-compose file.

### ISSUE THREAD

**Issue by ikilinc** [nginx-proxy/nginx-proxy#1460]
I have a weird bug, 

If i start the proxy via 
$ docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
its working, but if i use a docker-compose file to run the proxy i get a "no live upstreams while connecting to upstream,..." error.

version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

Between the switch a have let the jenkins service running, so there cannot be the error.

**Comment by tkw1536** [comment]
I suspect that is because your jenkins container isn't connected to the same docker network as nginx-proxy. 
How are you running jenkins?

**Comment by TheBlackDude** [comment]
I had the same issues today.

Just add these variables to the container you want to be proxied

```python 
      # Nginx-proxy & Letsentrypt
   environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_PORT: "${VIRTUAL_PORT}"
      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}
```

and set their values in your _.env file_ like:
```python
      VIRTUAL_HOST=some.example.com
      VIRTUAL_PORT=8000
      LETSENCRYPT_HOST=some.example.com
```

**Comment by ikilinc** [comment]
Hay,

thank you, but my problem was that run two separate compose files. If you dont specify a network explicity the services are run in different networks and cannot reach each other. 

either take the default network on both compose files via.

services:
   dummy:
       networks:
          -default


or just create a new network and use them.
