### ISSUE TITLE
No more Google Group

### ISSUE THREAD

**Issue by SturmB** [nginx-proxy/nginx-proxy#1461]
> If you have a question, DO NOT SUBMIT a new issue.  Please ask the question on the Q&A Group: https://groups.google.com/forum/#!forum/nginx-proxy

I have a question and I'm submitting an issue. Your Google Group does not exist anymore. I have nowhere else to turn. If there's a Slack group or Discord server where I can talk with someone about how to get FastCGI to work with this image, please direct me to it. Otherwise, I'll have no other choice than to post an "issue" about my question.

**Comment by tkw1536** [comment]
Duplicate of #1378.

**Comment by SturmB** [comment]
Thanks, tkw. I'll go ahead and close this issue, then.

**Comment by SturmB** [comment]
As it turns out, the Google Group does appear to still exist, despite the warning message that it doesn't. One just has to click on the "Join" button near the top-left of the screen.

**Comment by brian32768** [comment]
Searching in Google Groups currently finds a different group, nginx-aws-auth
There is no "Join" button until you actually find an existing group. No group shows up, so no JOIN.
