### ISSUE TITLE
how to configure multiple domain (virtual host) and multiple virtual port

### ISSUE THREAD

**Issue by jakata007** [nginx-proxy/nginx-proxy#1463]
I have run your image with command below.
```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro \
    --name my-nginx-proxy --network=mynetwork jwilder/nginx-proxy
```

my software run in single container and listen on port `81`,`82`

- port `81` designed for domain `a.mydomain`
- port `82` designed for domain `b.mydomain`

#### case 1, I have use these command. It's work.
`docker run -d  --network=mynetwork -e VIRTUAL_PORT=81 -e VIRTUAL_HOST=a.mydomain  myimage`

#### case 2, I have use these command. It's work.
`docker run -d  --network=mynetwork -e VIRTUAL_PORT=82 -e VIRTUAL_HOST=b.mydomain  myimage`

#### Question, how to configure for the following situation?
I would like to use port `81` with domain `a.mydomain` and port `82` with domain `b.mydomain` in single container.

I have tried with the following command. It 's not work.
`docker run -d --network=mynetwork -e VIRTUAL_PORT=81,82 -e VIRTUAL_HOST=a.mydomain,b.mydomain  myimage`

Please help.
Thanks you.

**Comment by tkw1536** [comment]
I don't think multiple services in the same container are supported at the moment. 

A workaround might be to have "dummy" containers for each additional port, that do nothing but forward all connections to the second port.

**Comment by first087** [comment]
> I don't think multiple services in the same container are supported at the moment.
> 
> A workaround might be to have "dummy" containers for each additional port, that do nothing but forward all connections to the second port.

I have the same problem for this issue.

My container run Nexus Repository in first port. It enable docker private repository in second port. I can't assign 2 domain by nexus-proxy.

Some app listen multiple port

Ex:

- RabbitMQ listen second port for monitoring.
- nginx listen 80, 443 for http and https

I think, one container running one service but listen single port is not always correct.

**Comment by jakata007** [comment]
@jwilder please help.

**Comment by tkw1536** [comment]
@jakata007 @first087:
Here is a workaround until a new feature is implemented. 

```bash
# start the nginx proxy
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro \
    --name my-nginx-proxy --network=mynetwork jwilder/nginx-proxy

# start the application container, take note that:
# - it is named (so that the proxies below can see it)
# - it does not have anything exposed
docker run -d --network=mynetwork --name myapp application-with-two-ports

# For each port that you want to expose, configure a pseudo container. 
# These only forward to the 'myapp' container above.
# They are additionally labeled for 'nginx-proxy' to pick up on. 
docker run -d --network=mynetwork -e VIRTUAL_PORT=80 -e VIRTUAL_HOST=a.mydomain -e REMOTE_HOST=myapp -e REMOTE_PORT=81 marcnuri/port-forward
docker run -d --network=mynetwork -e VIRTUAL_PORT=80 -e VIRTUAL_HOST=b.mydomain -e REMOTE_HOST=myapp -e REMOTE_PORT=82 marcnuri/port-forward
```

Disclaimer:
The image for proxying isn't mine, I haven't tested this. 
If for some reason you don't trust random images, you can always build it from the [Dockerfile](https://github.com/manusa/docker-images/blob/master/port-forward/Dockerfile) or make your own image. It should contain something like:

```Dockerfile
CMD socat tcp-listen:$LOCAL_PORT,reuseaddr,fork tcp:$REMOTE_HOST:$REMOTE_PORT
```

Also, I doubt @jwilder is currently developing new features, see https://github.com/nginx-proxy/nginx-proxy/issues/1304#issuecomment-535290685. 
So someone would have to make a PR and hope it gets merged.

**Comment by zahaim** [comment]
Many thanks for that workaround @tkw1536 , I was about to setup another registry / nexus just for 1 customer to achieve this.
