### ISSUE TITLE
How to redirect Nginx non-www to www domain over SSL

### ISSUE THREAD

**Issue by netlander** [nginx-proxy/nginx-proxy#1517]
Sorry but tried and **Group not available**

As the title implies I'm stuck on trying to have https://example.com redirect to https://www.example.com.

Should be straight forward right? But I've been scouring the entire web and tried a whole myriad of snippets to put inside `nginx.conf` but none worked.

Any ideas on how to do this in an environment where `nginx-proxy` is used with `letsencrypt-nginx-proxy-companion`?

Thanks

**Comment by shiz0** [comment]
@netlander 
nginx.conf is auto generated from nginx.tpl
Please see this https://github.com/nginx-proxy/nginx-proxy/pull/1369 and this https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/691 for hints on how to achieve this with a three container setup and a customized nginx.tpl which I linked in those two.

**Comment by netlander** [comment]
@shiz0 Thanks for the reply.

Just tried using three container setup plus your [nginx.tmpl](https://github.com/shiz0/nginx-proxy/blob/virtual_host_alias/nginx.tmpl) and hooked it up to  the `docker-gen` container (see the content of docker-compose.yml bellow).

Can you give a brief description of how to use this `nginx.tmpl` file and whether we need to change it in any way or would work right out of the gate? I have notice the extra setup you've put under **VIRTUAL_HOST_ALIAS** section but it seems pretty generic and has no information about specific domain names.

My specific use-case is to have `example.com` redirect to `www.example.com` (or vice versa).

Note that the `docker-compose.yml` content contains some extra stuff related to Docker Swarm but it shouldn't get in the way as the stack is starting correctly and there are no errors in the logs.

```
version: "3.8"

services:

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

#
#
#

  docker-gen:
    image: jwilder/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html      
      - ./conf/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
#
#
#
      
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: admin@example.com
      DEBUG: "true"
      NGINX_DOCKER_GEN_CONTAINER: docker-gen
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

#
#
#

  web:
    image: nginx:alpine
    container_name: example-webapp
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=www.example.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.example.com
      - LETSENCRYPT_EMAIL=mail@example.com
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
#
#
#

volumes:
  conf:
  certs:
  vhost:
  html:
```

**Comment by shiz0** [comment]
Being generic is actually the point of the template file. :-)
docker-gen will use the template, as well as info set in environment variables of the container yout site runs in ("web:" in your case), to create a proxy nginx.conf file for your specific setup. 
When using my nginx.tpl you just have to add "VIRTUAL_HOST_ALIAS" to it and it should work.
Note that you need to include all URLs in "LETSENCRYPT_HOST" for all redirects to work properly.
See this comment for example: https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/691#issuecomment-705432994

**Comment by netlander** [comment]
@shiz0 Thanks so much and yes it works as prescribed.

However, it's not fulfilling my requirements in their entirety, that's why I hoped that your additions to `nginx.tmpl` would be a bit more specific as to what's redirecting to what. Let me explain.

What I have is a multi-tenancy server, meaning that it's a single Docker container that can serve up many websites. It's configured so that given a particular request it's happy to serve up content related to that URL. but it can't be configured to serve the same website given a different URL, i.e. a one to one mapping.

So I was hoping that my reverse proxy can handle the redirecting from `example.com` to `www.example.com`. Your solution would not work in such scenario, for example I have the following in 'letsencrypt' container:

```
VIRTUAL_HOST=example-001.com, www.example-001.com, example-02.com, www.example-002.com
```

What I really want is for `www.example-001.com` to redirect to `example-001.com` and `www.example-002.com` to redirect to `example-002.com`.

And here is where I am back to pulling my hair out, or what's left of it at least.

Any pointers to where I should look next would be much appreciated.

**Comment by shiz0** [comment]
@netlander 
Ah, I see... you have like a classic multi vhost webserver (but running in docker) you want to redirect to.
I'm not even sure nginx-proxy would be able to do so or if editing the template alone could achieve this, because I think it's designed for a separate container per backend site.
I am afraid I cannot help you with that... 
Best "advice" I can give is to split up your web container if possible and use "one container per service" approach, sorry.
