### ISSUE TITLE
Let's Encrypt Challenge fails (404)

### ISSUE THREAD

**Issue by regnete** [nginx-proxy/nginx-proxy#1521]
On a brand new setup the certificate generation challgen fails due to 404/403 errors.

I found a similar issue which was never resolved: https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/506

https://github.com/nginx-proxy/nginx-proxy/blob/20cc3527b49f49fcb7eb182d88c3aba2021fa656/nginx.tmpl#L360

The following code should be inserted after line 360 in nginx.tmpl:

```
# Do not proxy Let'sEncrypt ACME challenge
location /.well-known/acme-challenge/ {
    auth_basic off;
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
```

While tracking donw this issue (as described in https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/wiki/Invalid-authorizations) it was hard to test if the files in /.well-known/acme-challenge/ where accessible from outside, as if there is not any vhost, the challenge folder is not available. Would be helpfull to make the folder available even in that edgy case:

https://github.com/nginx-proxy/nginx-proxy/blob/20cc3527b49f49fcb7eb182d88c3aba2021fa656/nginx.tmpl#L393

The following code should be inserted after line 393 in nginx.tmpl:

```
# Allow access to ACME challenge folder for testing purposes
location /.well-known/acme-challenge/ {
    auth_basic off;
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
```

**Comment by wvengen** [comment]
I had this too.
It was somehow related to the `vhosts/default` file, which contained this, which I inadvertently deleted. At some point it appeared again, which may have solved the issue for me, but it remained buggy (until all certificates were there, which happened somehow - though I did add the line manually to the template at some point which also helped in one case).

**Comment by jdelamare** [comment]
For some reason `nginx.tmpl` isn't including that same chunk of code for me either. I have an identical site where it has been included, not sure what's going on.

**Comment by buchdag** [comment]
This has been considerably changed recently (#2468, #2473) and should no longer be an issue.
