### ISSUE TITLE
load_module" directive is not allowed here in /etc/nginx/proxy.conf:1

### ISSUE THREAD

**Issue by andreidiaconescu** [nginx-proxy/nginx-proxy#1535]
when i add
load_module modules/ngx_http_brotli_filter_module.so;
load_module modules/ngx_http_brotli_static_module.so;

to a config file mapped with volume to

./nginx_proxy_default.conf:/etc/nginx/proxy.conf:ro
i get error: load_module" directive is not allowed here in /etc/nginx/proxy.conf:1

Where could i write the load_module directive ?
Thank you.

**Comment by aduzsardi** [comment]
loading modules need to be outside of stanza definition like `server` , `http`, `mail` , etc
http://nginx.org/en/docs/ngx_core_module.html#load_module

**Comment by buchdag** [comment]
Inactive issue, closing.

**Comment by frnzhop** [comment]
Hi, so where should we put such configuration? Thank you.
