### ISSUE TITLE
nginx-proxy | dockergen.1 | 2020/12/08 20:01:25 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'

### ISSUE THREAD

**Issue by abhimal** [nginx-proxy/nginx-proxy#1540]
i am following this tutorial https://testdriven.io/blog/django-docker-https-aws/

$ docker-compose -f docker-compose.staging.yml build

when i build this code on production env i am getting error

nginx-proxy | dockergen.1 | 2020/12/08 20:01:25 Generated '/etc/nginx/conf.d/default.conf' from 3 containers nginx-proxy | dockergen.1 | 2020/12/08 20:01:25 Running 'nginx -s reload' nginx-proxy | dockergen.1 | 2020/12/08 20:01:25 Watching docker events nginx-proxy | dockergen.1 | 2020/12/08 20:01:25 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'

```
```
>     version: '3.7'
>     
>     services:
>       web:
>         build:
>           context: ./app
>           dockerfile: Dockerfile.prod
>         image: <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/django-ec2:web
>         command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
>         volumes:
>           - static_volume:/home/app/web/staticfiles
>           - media_volume:/home/app/web/mediafiles
>         expose:
>           - 8000
>         env_file:
>           - .env.staging
>       nginx-proxy:
>         container_name: nginx-proxy
>         build: nginx
>         image: <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/django-ec2:nginx-proxy
>         restart: always
>         ports:
>           - 443:443
>           - 80:80
>         volumes:
>           - static_volume:/home/app/web/staticfiles
>           - media_volume:/home/app/web/mediafiles
>           - certs:/etc/nginx/certs
>           - html:/usr/share/nginx/html
>           - vhost:/etc/nginx/vhost.d
>           - /var/run/docker.sock:/tmp/docker.sock:ro
>         depends_on:
>           - web
>       nginx-proxy-letsencrypt:
>         image: jrcs/letsencrypt-nginx-proxy-companion
>         env_file:
>           - .env.staging.proxy-companion
>         volumes:
>           - /var/run/docker.sock:/var/run/docker.sock:ro
>           - certs:/etc/nginx/certs
>           - html:/usr/share/nginx/html
>           - vhost:/etc/nginx/vhost.d
>         depends_on:
>           - nginx-proxy
>     
>     volumes:
>       static_volume:
>       media_volume:
>       certs:
>       html:
>       vhost:

```
MY NGINX

**default**
```
location /staticfiles/ {
  alias /home/app/web/staticfiles/;
  add_header Access-Control-Allow-Origin *;
}

location /mediafiles/ {
  alias /home/app/web/mediafiles/;
  add_header Access-Control-Allow-Origin *;
}
```
**Dockerfile**

```
FROM jwilder/nginx-proxy
COPY vhost.d/default /etc/nginx/vhost.d/default
COPY custom.conf /etc/nginx/conf.d/custom.conf
```
**custom.conf**

`client_max_body_size 10M;client_max_body_size 10M;`

└── nginx
    ├── Dockerfile
    ├── custom.conf
    └── vhost.d
        └── default

**Comment by m4ci3k2** [comment]
This is generally not an error, just a message that the newly-generated configuration file is identical to previous one.

**Comment by abhimal** [comment]
but why my getting 
`nginx-proxy                | nginx.1    | 2020/12/16 06:02:04 [error] 147#147: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 217.27.176.227, server: rkfootwear.in, request: "HEAD /.git/config HTTP/1.1", upstream: "http://192.168.64.2:8000/.git/config", host: "rkfootwear.in"`

and 502 Bad Gateway in browser

**Comment by abhimal** [comment]
i am new in docker and nginx.

**Comment by abhimal** [comment]
this is my logs

```
nginx-proxy                | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx-proxy                | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
nginx-proxy                | Generating DSA parameters, 4096 bit long prime
nginx-proxy                | forego     | starting dockergen.1 on port 5000
nginx-proxy                | forego     | starting nginx.1 on port 5100
nginx-proxy                | dockergen.1 | 2020/12/16 06:00:31 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
nginx-proxy                | dockergen.1 | 2020/12/16 06:00:31 Running 'nginx -s reload'
nginx-proxy                | dockergen.1 | 2020/12/16 06:00:31 Watching docker events
nginx-proxy                | dockergen.1 | 2020/12/16 06:00:31 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy                | 2020/12/16 06:00:41 [notice] 83#83: signal process started
nginx-proxy                | dhparam generation complete, reloading nginx
nginx-proxy                | nginx.1    | rkfootwear.in 52.58.118.98 - - [16/Dec/2020:06:00:51 +0000] "GET /.well-known/acme-challenge/81cIcn8bks1Kxfv21-QMUzABl5ipHXL51PHLfQpJnS0 HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx-proxy                | nginx.1    | rkfootwear.in 18.224.20.83 - - [16/Dec/2020:06:00:51 +0000] "GET /.well-known/acme-challenge/81cIcn8bks1Kxfv21-QMUzABl5ipHXL51PHLfQpJnS0 HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx-proxy                | nginx.1    | rkfootwear.in 34.211.60.134 - - [16/Dec/2020:06:00:51 +0000] "GET /.well-known/acme-challenge/81cIcn8bks1Kxfv21-QMUzABl5ipHXL51PHLfQpJnS0 HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx-proxy                | nginx.1    | rkfootwear.in 66.133.109.36 - - [16/Dec/2020:06:00:51 +0000] "GET /.well-known/acme-challenge/81cIcn8bks1Kxfv21-QMUzABl5ipHXL51PHLfQpJnS0 HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx-proxy                | nginx.1    | 2020/12/16 06:02:04 [error] 147#147: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 217.27.176.227, server: rkfootwear.in, request: "HEAD /.git/config HTTP/1.1", upstream: "http://192.168.64.2:8000/.git/config", host: "rkfootwear.in"
nginx-proxy                | nginx.1    | rkfootwear.in 217.27.176.227 - - [16/Dec/2020:06:02:04 +0000] "HEAD /.git/config HTTP/1.1" 502 0 "-" "python-requests/2.12.4"
nginx-proxy                | nginx.1    | 2020/12/16 06:02:04 [error] 147#147: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 217.27.176.227, server: rkfootwear.in, request: "HEAD /.git/config HTTP/1.1", upstream: "http://192.168.64.2:8000/.git/config", host: "rkfootwear.in"
```
