### ISSUE TITLE
nginx-gitlab proxy issue

### ISSUE THREAD

**Issue by Srinivasa381224** [nginx-proxy/nginx-proxy#1544]
Hi, we are using gitlab for production and we configured that in one of aws ec2 instance in gitlab we are not providing ssl(https) in gitlab server instead of that we are using one nginx machine to route all our application based on dns in nginx i installed letsencrypt using this i generated certificate for our gitlab in nginx conf file for gitlat am using proxy_pass http:// but in previously in chrome its working fine but in latest days when ever our developers trying to merge any code they are getting some warning saying that "The information your about to submit is not secure" please suggest me i need to change any conf in gitlab or nginx side i dont know how to resolve this issue please help me for this

**Comment by Pezhvak** [comment]
can you share your docker configuration (docker-compose.yml) or the commands you run?

**Comment by buchdag** [comment]
Inactive issue, closing.
