### ISSUE TITLE
nginx-proxy + apache2 real client ip

### ISSUE THREAD

**Issue by elclay7** [nginx-proxy/nginx-proxy#1549]
I would like to add this configuration to allow the real ip of the clients to be shown in the log of my apache and not that of the proxy
[documentation](https://gist.github.com/patrocle/43f688e8cfef1a48c66f22825e9e0678)

    location ~ \.php$ {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass   http://my.site;
    }

How can I insert this code in the nginx configuration?

**Comment by AjBreidenbach** [comment]
From his [blog](http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/) 
```nginx
{{ range $host, $containers := groupBy $ "Env.VIRTUAL_HOST" }}
upstream {{ $host }} {

{{ range $index, $value := $containers }}
    {{ with $address := index $value.Addresses 0 }}
    server {{ $address.IP }}:{{ $address.Port }};
    {{ end }}
{{ end }}

}

server {
    #ssl_certificate /etc/nginx/certs/demo.pem;
    #ssl_certificate_key /etc/nginx/certs/demo.key;

    gzip_types text/plain text/css application/json application/x-javascript
               text/xml application/xml application/xml+rss text/javascript;

    server_name {{ $host }};

    location / {
        proxy_pass http://{{ $host }};
        include /etc/nginx/proxy_params;
    }
}
{{ end }}
```
It looks like it goes in  /etc/nginx/proxy_params

**Comment by wilcorrea** [comment]
@elclay7 did you fixed it?

**Comment by elclay7** [comment]
> @elclay7 did you fix it?

no =(

**Comment by elclay7** [comment]
@wilcorrea 
I succeeded, just had to change in the apache2.conf configuration file
this:
**%h**
For this:
**% {X-Forwarded-For} i**
Here is the explanation (it is in Spanish)
https://www.sololinux.es/registrar-la-ip-real-del-cliente-en-apache/
