### ISSUE TITLE
Doesn't seem to find sites on worker nodes

### ISSUE THREAD

**Issue by markfaine** [nginx-proxy/nginx-proxy#1552]
I am running pihole on a different node and it doesn't seem to even know it's there.  It's running and is accessible but it's not being added to default.conf.  Any ideas?  Is this a known issue or am I doing something wrong and it should work.

**Comment by bizmate** [comment]
What have you done to configure it correctly? Have you followed the README ? Could you please describe the problem better ?

**Comment by buchdag** [comment]
Inactive issue, closing.
