### ISSUE TITLE
Docker Container restart everytime

### ISSUE THREAD

**Issue by BMWfan** [nginx-proxy/nginx-proxy#1556]
Hello,

i have a raspberry pi 4 on which i want to let run the nginx-proxy container.

i cloned the repo and used the following docker-compose file content:

`version: "2"
services:
nginx-proxy:
    build:
      context: ./nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    networks:
      - nginx
    extra_hosts:
      - "service1.mydomain.de:192.168.178.100"
      - "service2.mydomain.de:192.168.178.100"
      

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:

networks:
  nginx:
    driver: bridge`

These are the log entries:
`Custom dhparam.pem file found, generation skipped
/app/docker-entrypoint.sh: line 34: /usr/local/bin/forego: cannot execute binary file: Exec format error
/app/docker-entrypoint.sh: line 34: /usr/local/bin/forego: Success
`

How can is solve this?

Greetings

Daniel

**Comment by todeveni** [comment]
nginx-proxy isn't compatible with ARM processors out of the box

See https://github.com/nginx-proxy/nginx-proxy/pull/1470

**Comment by buchdag** [comment]
Fixed as of #1470 + 4a1d5bfc58af35f5e90dcefb47b35a274c903150 + d120ce9fdebf09a6c7b90ecff7eda0b7d2760ef3

`arm64` and `arm/v7` images are availables from `jwilder/nginx-proxy` or the new registry `nginxproxy/nginx-proxy`
