### ISSUE TITLE
Nginx-proxy not added ssl_trusted_certificate

### ISSUE THREAD

**Issue by spirit1086** [nginx-proxy/nginx-proxy#1559]
**wildcard ssl certificate**
**ssl_certificate  and  ssl_certificate_key  added in nginx-proxy conf, but ssl_trusted_certificate not**
**nginx-proxy 
docker-compose:**

`version: "3"

services:

    nginx-proxy:
        restart: always
        image: jwilder/nginx-proxy
        network_mode: bridge
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./cert/ssl:/etc/nginx/certs
           
 **api.domain.com docker-compose.yml**

version: "3.1"
services:
    www:
        build: .
        restart: always
        volumes:
            - ./www:/var/www/html/
            - ./conf/default.conf:/etc/apache2/sites-enabled/000-default.conf
        links:
             - db:db
        network_mode: bridge
        expose:
            - 80
        environment:
           VIRTUAL_HOST: api.domain.com
    db:
        image: mysql:8.0
        ports: 
            - "1111:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER:  myuser
            MYSQL_PASSWORD: myuser_pass
            MYSQL_ROOT_PASSWORD: myuser_pass
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        network_mode: bridge
volumes:
    persistent:

**when nginx-proxy started, in nginx-proxy container ssl:**
 - api.domain.com.chain.pem
 - domain.com.crt
 - domain.com.key

 **nginx-proxy container generate conf:**

 `
`
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}

map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}

map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
server_names_hash_bucket_size 128;
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
                ssl_prefer_server_ciphers off;
resolver XX.XX.XX.XX(server ip address) 172.22.140.200;

proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;

proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}

upstream api.domain.com {
                        server 172.17.0.4:80;
}
server {
        server_name api.domain.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;

        location /.well-known/acme-challenge/ {
                auth_basic off;
                allow all;
                root /usr/share/nginx/html;
                try_files $uri =404;
                break;
        }
        location / {
                return 301 https://$host$request_uri;
        }
}
server {
        server_name api.domain.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/domain.com.crt;
        ssl_certificate_key /etc/nginx/certs/domain.com.key;
        add_header Strict-Transport-Security "max-age=31536000" always;
        location / {
                proxy_pass http://api.domain.com;
        }
}`

**It opens in the browser secure connection is success, but when requesting on api, result SSL Error: Unable to verify the first certificate, why nginx-proxy not added my api.domain.chain.pem**
 
**openssl crl2pkcs7 -nocrl -certfile api.domain.chain.pem | openssl pkcs7 -print_certs -noout**
subject=CN = *.domain.com

issuer=C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA

**Comment by MarioProjects** [comment]
Hi @spirit1086 , how you solved the problem? When I use postman to call to my API 'unable to verify the first certificate' but when acess to the web no problems and 'connection is secure'...
