### ISSUE TITLE
set url proxy

### ISSUE THREAD

**Issue by Suika99** [nginx-proxy/nginx-proxy#1566]
How to use path to proxy containers instead of request headers.
Like this: localhost/demo

**Comment by tkw1536** [comment]
This is currently not possible, however there is a PR for supporting so-called 'VIRTUAL_PATH's. These would enable exactly what you want. See #1594.

**Comment by buchdag** [comment]
This features has been added to the `dev` branch with #1607 

It's available now on the `dev` images `nginxproxy/nginx-proxy:dev` and `nginxproxy/nginx-proxy:dev-alpine`. Testing and feedback are welcome, the docs for the feature is [here](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing) and there is [another PR](https://github.com/nginx-proxy/nginx-proxy/pull/1699) opened for additional improvements and comments.
