### ISSUE TITLE
SSL_POLICY per container can not set ssl_protocols correctly due to issue in nginx server

### ISSUE THREAD

**Issue by kleptox** [nginx-proxy/nginx-proxy#1568]
I have searched issues by SSL_POLICY template and do not find similar issue so create new.

The problem is next:

If SSL_POLICY defined for nginx container is set global ssl_protocols and ssl_ciphers variables.

If I set for my container for backward compatibility for example -e SSL_POLICY=AWS-2015-02
nginx container in generated config set per-server ssl_protocols and ssl_ciphers - thats ok.

The problem is that nginx server does not support ssl_protocols per-server configuration.
So if I do not define globally SSL_POLICY which allow Tlsv1.1 it do not be applied even it enabled in "server" block.

Nginx closed issue ticket.
https://trac.nginx.org/nginx/ticket/676

I think there is nothing to do but may be add few lines to docs about this feature - 
I spend some time to understand why it do not work as described till examine nginx behavior
and exaclty search for this problem nginx issue list.

**Comment by buchdag** [comment]
@kleptox would you like to make a PR for this doc update ?

**Comment by buchdag** [comment]
That might be a bigger issue than what I originally thought as it's related to #1237, #1181, #1177 and #765

**Comment by buchdag** [comment]
This should have been fixed by #2338
