### ISSUE TITLE
No Google Group - help, need to password protect single directory in container

### ISSUE THREAD

**Issue by plittlefield** [nginx-proxy/nginx-proxy#1573]
Hello,

I have tried to follow the instructions and done numerous searches elsewhere but I just cannot get a password protected location code block to appear inside a vhost container config.

I don't want to password protect the whole container, just a single directory running off the web server on the container.

e.g.

```
location /linux/ {
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/htpasswd/linux;
}
```

I have managed to bind the password file shown above inside the container from the host filesystem but cannot get the VIRTUAL_HOST / docker-gen to generate the required code block!

Hope anyone can help.

Thanks,

Paully

**Comment by tkw1536** [comment]
Nginx-proxy has built-in support for password protecting entire hosts. To protect a single directory custom nginx configuration is required. 

Please have a look at the [Per-Virtual Host Configuration](https://github.com/nginx-proxy/nginx-proxy#per-virtual_host) Section of the README. 

To e.g. protect the `/linux/` directory of the domain `protected.example.com` you would created a file `protected.example.com` with your custom configuration:

```
location /linux/ {
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/htpasswd/linux;
}
```

Then mount this file (alongside with `htpasswd`) under `/etc/nginx/vhost.d/protected.example.com` inside the nginx-proxy container. Afterwards you would restart the container for changes to take effect. 

If you instead want to protect an entire domain, just mount your htpasswd file under `/etc/nginx/htpasswd/protected.example.com` and nginx-proxy will take care of the rest.  See the [Basic Authentication Support](https://github.com/nginx-proxy/nginx-proxy#basic-authentication-support) Section of the README.

**Comment by plittlefield** [comment]
Thanks @tkw1536 for your reply, much appreciated.

I read that section of the README and followed your instructions but I must be doing something wrong.

The extra code block is not present in either the nginx-proxy or nginx-example.com

Here is my complete setup, and hope you can see where I have gone wrong.

Tree listing of files and folders...

```
|-- nginx
|   |-- docker-compose.yml
|   `-- example.com
|       |-- htpasswd
|       |   `-- linux
|       `-- vhost.d
|           `-- protected.example.com
|-- nginx-proxy
|   |-- docker-compose.yml
|   `-- example.com
|       |-- htpasswd
|       |   `-- linux
|       `-- vhost.d
|           `-- protected.example.com
```

Docker Compose file for nginx-proxy...

```
version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./example.com/htpasswd:/etc/nginx/htpasswd
      - ./example.com/vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    external:
      name: nginx-proxy
```


Extra code block for nginx-example.com...

```
    location /linux/ {
        auth_basic      "Restricted";
        auth_basic_user_file    /etc/nginx/htpasswd/linux;
    }
```


Listing of files inside nginx-proxy container...

```
/etc/nginx/
/etc/nginx/koi-win
/etc/nginx/win-utf
/etc/nginx/koi-utf
/etc/nginx/conf.d
/etc/nginx/conf.d/default.conf
/etc/nginx/uwsgi_params
/etc/nginx/mime.types
/etc/nginx/scgi_params
/etc/nginx/modules
/etc/nginx/fastcgi_params
/etc/nginx/nginx.conf
/etc/nginx/dhparam
/etc/nginx/dhparam/dhparam.pem
/etc/nginx/vhost.d
/etc/nginx/vhost.d/protected.example.com
/etc/nginx/htpasswd
/etc/nginx/htpasswd/linux
/etc/nginx/certs
/etc/nginx/network_internal.conf
```

Printout of bottom of /etc/nginx/conf.d/default.conf file inside nginx-proxy...

```
# example.com
upstream example.com {
                        ## Can be connected with "nginx-proxy" network
                        # nginx-example.com
                        server 172.22.0.4:80;
}
server {
        server_name example.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://example.com;
        }
}
```

Help! Where have I gone wrong?

**Comment by tkw1536** [comment]
It looks correct to me. 

However some of your code uses "example.com". Some uses "protected.example.com". The domain names must match exactly. 

Also you might have to restart the container after the files are in place. That should reapply the template.

**Comment by plittlefield** [comment]
Ah ha!

I have good news and bad news :-)

The good news = that was it, I changed protected.example.com to example.com on the filenames and now I have an htaccess box pop up on that /linux location and the credentials work.

The bad news = I now have an error "404 Not Found" page :-(

```
nginx-proxy    | nginx.1    | example.com [23/Mar/2021:10:49:53 +0000] "GET /linux/ HTTP/1.1" 401 179 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0"
nginx-proxy    | nginx.1    | 2021/03/23 10:49:58 [error] 55#55: *1 "/etc/nginx/html/linux/index.html" is not found (2: No such file or directory), client: 212.159.20.63, server: example.com, request: "GET /linux/ HTTP/1.1", host: "example.com"
```

So, it looks like we have a proxy pass issue?

The path there **/etc/nginx/html/linux/index.html** is the clue...

Help!

**Comment by plittlefield** [comment]
Perhaps it is this issue - 

How can I add extra proxy_set options to the nginx-proxy config?

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_set_header Host $host;
proxy_set_header  Authorization $http_authorization;
proxy_pass_header Authorization;
```

Thanks for your help.

**Comment by plittlefield** [comment]
OK, I think I may have solved the 'bad news' problem.

I am not sure if this is technically correct but I added an extra proxy_pass line to the extra /etc/nginx/vhost.d/example.com file, like so...

So, from this...

```
    location /linux/ {
        auth_basic      "Restricted";
        auth_basic_user_file    /etc/nginx/htpasswd/linux;
    }
```
To this...

```
    location /linux/ {
        auth_basic      "Restricted";
        auth_basic_user_file    /etc/nginx/htpasswd/linux;
        proxy_pass http://example.com;
    }
```

...and now the password protection works and it shows me the correct page at the correct location.

Does that look alright to everyone?

**Comment by plittlefield** [comment]
Great, problem solved and I am closing this issue.

Hope it helps someone else.

Keep up the great work.
