### ISSUE TITLE
How to set host/container name instead of ip of container

### ISSUE THREAD

**Issue by quangnv13** [nginx-proxy/nginx-proxy#1583]
I setup docker gen with nginx-proxy/acme-companion and nginx. It's work ok but after i restart my vps all container on my network are changed ip. And `docker gen` does'nt re generator new ip of them. Now i open default.conf to manual change the ip auto generate by docker gen to host name. Example: `server chatbox:3000` it's also working. How to docker gen auto generate `container name` instead of `container ip`

**Comment by tkw1536** [comment]
docker-gen should regenerate the configuration every time a container is removed or created. This should trigger in your case, if it doesn't I would consider it a bug. Do you have logs that you would be willing to share?

If you want to switch to container name you will have to modify the template used to generate the configuration file.The `upstream` blocks inside the nginx configuration are generated [here](https://github.com/nginx-proxy/nginx-proxy/blob/main/nginx.tmpl#L7-L24). If you want to use the `container name` instead, you could replace `{{ .Network.IP }}` with `{{ .Container.Name }}`. 

To use a custom template, you will either have to build the docker image locally, or use the [Separate Containers](https://github.com/nginx-proxy/nginx-proxy#separate-containers) setup.

**Comment by quangnv13** [comment]
> docker-gen should regenerate the configuration every time a container is removed or created. This should trigger in your case, if it doesn't I would consider it a bug. Do you have logs that you would be willing to share?
> 
> If you want to switch to container name you will have to modify the template used to generate the configuration file.The `upstream` blocks inside the nginx configuration are generated [here](https://github.com/nginx-proxy/nginx-proxy/blob/main/nginx.tmpl#L7-L24). If you want to use the `container name` instead, you could replace `{{ .Network.IP }}` with `{{ .Container.Name }}`.
> 
> To use a custom template, you will either have to build the docker image locally, or use the [Separate Containers](https://github.com/nginx-proxy/nginx-proxy#separate-containers) setup.

It's work! Thanks you
