### ISSUE TITLE
Generate certicate again same domain

### ISSUE THREAD

**Issue by RafaelHGBotelho** [nginx-proxy/nginx-proxy#1588]
Hello guys, I use this repository as a base, but the certificates are no longer available in certs/, is there a way to generate again for the same domain?

I have already installed and uninstalled a few times, removed containers, volumes, network, but nothing makes the certificate generate again.

**Comment by buchdag** [comment]
Hi.

Aren't you mixing up with [nginx-proxy/acme-companion](https://github.com/nginx-proxy/acme-companion) ?

nginx-proxy/nginx-proxy does not generate any certificates.

**Comment by RafaelHGBotelho** [comment]
@buchdag Actually the certificate has expired, I generated others and it worked perfectly.

About Let's Encrypt, you know some way to implement SSL on the Zabbix front with Docker. I'm using nginx-proxy, and the front always gives error 502 Bad Gateway.

Thanks!
