### ISSUE TITLE
Support customised local builds for container images

### ISSUE THREAD

**Issue by elfring** [nginx-proxy/nginx-proxy#1604]
The file format “docker-compose.yml” supports [the building of container images](https://github.com/compose-spec/compose-spec/blob/b7fb5b65fff19651ecdb2d4d3232b01fb6866f70/build.md#the-compose-specification---build-support "The Compose Specification - Build support") besides [referencing published images](https://github.com/compose-spec/compose-spec/blob/b7fb5b65fff19651ecdb2d4d3232b01fb6866f70/spec.md#image "Choosing container images").
Thus I suggest to select system configuration parameters occasionally.

[Software build generators](https://en.wikipedia.org/wiki/List_of_build_automation_software#Build_script_generation "Build script generation") can help then further for the selection of desirable key words and values.

**Comment by buchdag** [comment]
I'm sorry but I really have a hard time making sense of your message.

What is the issue or the requested feature ?

**Comment by elfring** [comment]
:thinking: This software is evolving in remarkable ways, isn't it?

Thus I would like to configure a software build system so that another container image will be locally built according to my system test needs.
(How are the chances to avoid accesses to public container repositories?)

**Comment by buchdag** [comment]
Wether you're using Docker Compose or not you're still ultimately building a Dockerfile, and ...

> How are the chances to avoid accesses to public container repositories?

... if you're building a Dockerfile, the only way is to [build a base image](https://docs.docker.com/develop/develop-images/baseimages/#create-a-simple-parent-image-using-scratch).

You'll probably get help more easily by stating clearly what your base intents and needs are. If I understood correctly in this case the underlying need is to build you own custom version of nginx-proxy (or an image based on it) with as little reliance on public image Registries and network access as possible ?

**Comment by elfring** [comment]
* I am looking for ways to switch between specifications for “`image:`” and “`build:`” in [the file “docker-compose.yml”](https://github.com/nginx-proxy/nginx-proxy/blob/6e17d6ff7beb82b0f250ab37eec930b43c20a269/docker-compose.yml#L4 "Update candidate") by systematic means.
* I would like to avoid network accesses for some system tests because of data processing speed considerations.

**Comment by buchdag** [comment]
Closing issue because we're not a generalist Docker Compose help / discussion board + [this warning](https://github.com/nginx-proxy/nginx-proxy/issues/1605#issuecomment-828238505).

**Comment by elfring** [comment]
I became curious if involved software build aspects can be clarified better.
