### ISSUE TITLE
Checking software dependencies according to “pytest.sh”

### ISSUE THREAD

**Issue by elfring** [nginx-proxy/nginx-proxy#1605]
I cloned the current development repository.
I stumbled on the following information then.

```
Markus_Elfring@localhost:~/…/frontproxy/lokal> ./test/pytest.sh
> Building nginx-proxy-tester image...
…
Step 5/5 : ENTRYPOINT ["pytest"]
 ---> Using cache
 ---> 49d8827ee821
Successfully built 49d8827ee821
Successfully tagged nginx-proxy-tester:latest
ImportError while loading conftest '/home/Markus_Elfring/…/frontproxy/lokal/test/conftest.py'.
conftest.py:472: in <module>
    pytest.exit("The docker image 'nginxproxy/nginx-proxy:test' is missing")
E   _pytest.outcomes.Exit: The docker image 'nginxproxy/nginx-proxy:test' is missing
```

:thinking: How do you think about to [improve this software situation](https://github.com/nginx-proxy/nginx-proxy/blob/aa9386129d7caee7165395e3c816171114416c0f/test/README.md#nginx-proxy-test-suite "Nginx proxy test suite")?

**Comment by tkw1536** [comment]
I don't understand your question. 

According to the documentation __you linked__ you first have to run
```
make build-nginx-proxy-test-debian
```
or
```
make build-nginx-proxy-test-alpine
```
for the tests to work.

**Comment by buchdag** [comment]
@tkw1536 you should take a look at https://github.com/obsproject/obs-studio/issues/4520#issuecomment-819923534 and https://github.com/obsproject/obs-studio/issues/4520#issuecomment-820326482

**Comment by elfring** [comment]
Would you find the case distinction from the sentence “If you can't install those requirements on your computer, you can alternatively use the _pytest.sh_ script which will run the tests from a Docker container which has those requirements.” still relevant?

**Comment by buchdag** [comment]
@elfring In light of [this discussion](https://github.com/obsproject/obs-studio/issues/4520#issuecomment-819923534) (and my own research on your GitHub activity that confirms what has been reported there), I'm going to ask you to stop purposefully wasting maintainers and contributors time by engaging them in long, contrived and sometime nonsensical discussion about somewhat trivial but technically valid points.

Yes the Docker container based tests aren't working yet, I've got someone working on it and he'll do a PR when this is ready. I'll edit the doc to remove the phrase alluding to those until they're fixed, issue closed.

**Comment by elfring** [comment]
>Yes the Docker container based tests aren't working yet,

Thanks for such information.


>I've got someone working on it …

I am curious how corresponding software developments will evolve further.
