### ISSUE TITLE
Checking data processing results for application example “whoami”

### ISSUE THREAD

**Issue by elfring** [nginx-proxy/nginx-proxy#1606]
[A software configuration suggestion is provided](https://github.com/nginx-proxy/nginx-proxy/blob/6e17d6ff7beb82b0f250ab37eec930b43c20a269/docker-compose.yml#L2 "Example for “Docker Compose”").
I adjusted it a bit for my system test needs.

```diff
   nginx-proxy:
-    image: nginxproxy/nginx-proxy
+#    image: nginxproxy/nginx-proxy
+    build:
+      context: nginx
+      dockerfile: nginx-alpine-my_test.docker
```

I got the impression that the following addition would be also required then (besides copying a few configuration files).

```diff
     volumes:
+      - .:/app
```

Otherwise:
I stumbled on the following message.

```
…
ERROR: for nginx-proxy  Cannot start service nginx-proxy: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/app/docker-entrypoint.sh": stat /app/docker-entrypoint.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

Another test run:

```
Markus_Elfring@localhost:~/…/frontproxy/lokal/my_test> docker-compose up -d && docker ps && LANG=C curl -H 'Host: whoami.local' localhost
Creating network "my_test_default" with the default driver
Creating my_test_whoami_1 ... done
Creating nginx-proxy      ... done
CONTAINER ID   IMAGE                 COMMAND                  CREATED        STATUS                  PORTS                               NAMES
cacb74e73daa   my_test_nginx-proxy   "/app/docker-entrypo…"   1 second ago   Up Less than a second   0.0.0.0:80->80/tcp, :::80->80/tcp   nginx-proxy
605bf64ae330   jwilder/whoami        "/app/http"              1 second ago   Up Less than a second   8000/tcp                            my_test_whoami_1
…
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>
…
<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

:thinking: Now I wonder also about this information because I would expect [an other data display according to the published documentation](https://github.com/nginx-proxy/nginx-proxy/blob/0d2efaee95f29099ea7d5036136e07c9994c73a2/README.md#docker-compose "Checking data processing results for “whoami”") for such an application example.

**Comment by tkw1536** [comment]
See https://github.com/nginx-proxy/nginx-proxy/issues/1605#issuecomment-828238505. 

@buchdag  please close this issue. 
Is there any way of preventing this user from creating new issues?

**Comment by buchdag** [comment]
Done, I just permanently blocked him from the nginx-proxy org.
