### ISSUE TITLE
Issue in proxy pass from nginx to angular application

### ISSUE THREAD

**Issue by sanikadjango** [nginx-proxy/nginx-proxy#1614]
I have created an angular application that displays a page with “Hello World” on ‘/hello’ route.
url for angular: http://localhost:4200/hello
When I make request from browser to nginx on ‘/greet’: http://localhost/greet
that should be redirected to /hello route of angular application so that the page with “Hello World” is displayed.
But if the request is http://localhost/hello , an err should appear

The nginx conf:
server {
listen 80;
server_name _;
location /greet {
proxy_pass http://localhost:4200/hello;
}
location /hello {
return 404;
}
}

The issue is that while redirecting, the route is not getting modified as ‘/hello’
And since there is no ‘/greet’ route in angular, we get a not found.

**Comment by tkw1536** [comment]
This looks like a general nginx issue. 
This repository is only for issues specific to the 'nginx-proxy' project, not general nginx questions.

**Comment by sanikadjango** [comment]
Could you please tell me where should I post this issue?

**Comment by buchdag** [comment]
@sanikadjango 

https://www.nginx.com/resources/wiki/community

https://forum.nginx.org
