### ISSUE TITLE
WSL: Trying to run the unit tests locally, many fail (very slowly) because connections time out.

### ISSUE THREAD

**Issue by dakotahawkins** [nginx-proxy/nginx-proxy#1615]
I'm using WSL2 (Ubuntu 20.04.2 LTS) and Docker Desktop in the recommended configuration (normal docker stuff I've tried so far seems to work ok).

An example from the first failing test and some output that may be relevant:

```python
test_composev2.py::test_unknown_virtual_host FAILED

...

_ _ _ _ _ _ ...

address = ('nginx-proxy', 80), timeout = None, source_address = None, socket_options = [(6, 1, 1)]

    def create_connection(
        address,
        timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
        source_address=None,
        socket_options=None,
    ):
...
address    = ('nginx-proxy', 80)
...
sa         = ('172.18.0.3', 80)
...

_ _ _ _ _ _ ...

...
E           requests.exceptions.ConnectionError: HTTPConnectionPool(host='nginx-proxy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0c4f176310>: Failed to establish a new connection: [Errno 110] Connection timed out'))
...

```

From this I gather that it's custom dns does resolve the IP address of the `nginx-proxy` container, ~~but I'm confused as to why the port is 80 when the container is apparently supposed to use 81~~ (edit: I'm a moron, that's what the proxy does). Some other tests using different ports work correctly, so I'm wondering if it's an issue with the custom dns fixture after all. I'm stumped, so any suggestions would be very welcome!

**Comment by alekna** [comment]
Have no problems running tests locally on Debian 10. So probably environment-specific problems.

**Comment by dakotahawkins** [comment]
Yeah I figure it must be something happening with WSL. I set up a proper VM in the mean time, though it's not as convenient to use.

**Comment by polarathene** [comment]
It's not WSL specific afaik, I have the same issue via Vultr VPS:

- Ubuntu 21.04
- Docker 20.10.8
- docker-compose 1.29.2, docker-py 5.0.3
- 5.11 kernel x86_64

The pytest container also crashes/exits if I try to run it with host networking mode (_presumably because of the network config pytest does?_) instead of bridge.

Could be that it doesn't like something on the host?

**Comment by buchdag** [comment]
@dakotahawkins when you have the occasion, could you test if #1856 fixed the issue for WSL ?
