### ISSUE TITLE
Problem while adding header

### ISSUE THREAD

**Issue by Tockra** [nginx-proxy/nginx-proxy#1668]
Hi,

I read this issue https://github.com/nginx-proxy/nginx-proxy/issues/804 and I did exactly what they wrote there. But my requests doesn't get the set headers:

So I added several of the above solutions. Currently I have 
```bash
add_header 'Access-Control-Allow-Origin' "*" always;
add_header 'Access-Control-Allow-Credentials' 'true' always;
add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;

# required to be able to read Authorization header in frontend
#add_header 'Access-Control-Expose-Headers' 'Authorization' always;

if ($request_method = 'OPTIONS') {
        # Tell client that this pre-flight info is valid for 20 days
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
}
```

I added a Dockerfile
```
FROM jwilder/nginx-proxy:alpine
COPY ./build/default_locations /etc/nginx/vhost.d/

```

But if I call an existing endpoint at OPTIONS subdomain.localhost there are just these headers and response code is 200:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/1353859/122442122-83ec0e80-cf9e-11eb-9528-faa934d0056c.png">

Can somebody help?

**Comment by tkw1536** [comment]
Per https://github.com/nginx-proxy/nginx-proxy#per-virtual_host-location-default-configuration, it is `/etc/nginx/vhost.d/default_location` (no `s` as in your snippet). So the Dockerfile should be:

```Dockerfile
FROM jwilder/nginx-proxy:alpine
COPY ./build/default_location /etc/nginx/vhost.d/default_location
```

Please also make sure not to mount anything else under `/etc/nginx/vhost.d/` when running the image, otherwise you might overwrite the file.

**Comment by Tockra** [comment]
Okay thank you. Clearly it was such a problem ;)

Can you tell me, why the OPTIONS call don't get the header information but the POST call?:
OPTIONS:
![image](https://user-images.githubusercontent.com/1353859/122518931-272a3b80-d012-11eb-8402-6cfbc99e8aee.png)

POST:
![image](https://user-images.githubusercontent.com/1353859/122518992-390bde80-d012-11eb-883f-ad13ef3904c2.png)

**Comment by tkw1536** [comment]
I don't know, you might have to copy-paste the headers into the if block explicitly. `if` is weird, [I've always considered it evil](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/).
