### ISSUE TITLE
503 error when connect by external ip

### ISSUE THREAD

**Issue by CoDooku** [nginx-proxy/nginx-proxy#1681]
Hi!

When I try to connect by external ip I get 503 error. 

At the same time proxy container has volume proxy_html with index.html so it can be reached.

How it works?

**Comment by rene-gomez** [comment]
hello @CoDooku , can you share with us more information?

Please check my issue report https://github.com/nginx-proxy/nginx-proxy/issues/1675

If you have general questions about using this reverse proxy, pls check the README file https://github.com/nginx-proxy/nginx-proxy/blob/main/README.md

regards

**Comment by CoDooku** [comment]
Well, I have docker 20.10.6 and proxy compose:

**Docker-compose**

version: '2'

networks:
  default:
    external:
      name: network

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      -     networks:
      - default

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "/etc/timezone:/etc/timezone:ro"
       - "/etc/localtime:/etc/localtime:ro"
    networks:
      - default

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:


Host external  ip address is 77.41.191.97.
Local ip address is 192.168.x.x
So, when I type in browser 77.41.191.97 on remote PC (or 192.168.x.x on server) I get 301 error:
![2021-06-26_16-18-23](https://user-images.githubusercontent.com/12514604/123514185-45d7a480-d69a-11eb-9f50-05acdde42a5d.png)


**What is expected**

I expect proxy start page
![2021-06-26_16-22-18](https://user-images.githubusercontent.com/12514604/123514272-cbf3eb00-d69a-11eb-8061-7b677214ad5d.png)

**Comment by buchdag** [comment]
@CoDooku I think what you expect isn't the way this image works. When you try to reach the nginx-proxy host using its IP, you'll either get a 503 or the `DEFAULT_HOST` if you defined this environment variable and you have a running container with the corresponding `VIRTUAL_HOST`. You'll never get the default index.html of the nginx-proxy container itself.

**Comment by CoDooku** [comment]
@buchdag thank you, DEFAULT_HOST is what i need!
