### ISSUE TITLE
Raw Ipv6 `VIRTUAL_HOST` broken on 0.9.1

### ISSUE THREAD

**Issue by tkw1536** [nginx-proxy/nginx-proxy#1693]
As of updating to nginx-proxy version 0.9.1 it is no longer possible to set a `VIRTUAL_HOST` corresponding to a raw ipv6 address. 

When attempting this, the entire nginx proxy configuration errors out and falls back to the default error page:

```
Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working.
Further configuration is required.
```

The logs show the following error message:
```
nginx-proxy_1                        | 2021/07/14 15:02:32 [emerg] 52#52: invalid host in upstream "[2001:638:(rest of ipv6 address censored)]-upstream" in /etc/nginx/conf.d/default.conf:108
nginx-proxy_1                        | nginx: [emerg] invalid host in upstream "[2001:638:(rest of ipv6 censored)]-upstream" in /etc/nginx/conf.d/default.conf:108
```

I rolled back to 0.9.0 and confirmed the issue does not occur there. 

I suspect the culprit is https://github.com/nginx-proxy/nginx-proxy/pull/1163, as `[]`-bracketed ipv6 addresses do not seem to be valid upstream names when adding an `upstream` suffix.

**Comment by buchdag** [comment]
I'm curious, what would be the use case of doing this ?

**Comment by tkw1536** [comment]
I have several domains pointing to my server. I am using all of those with the acme companion and https. 

However my network administrators constantly "security scan" (to check for outdated php etc) the server for vulnerabilities, http ing the raw ip address as opposed to any specific domain. 

I don't think this scan is a good idea, but it is very hard to get hold of the network admins, or convince them to stop scanning. By having a VIRTUAL_HOST with the raw ip address I at least have control of the http response they get.

**Comment by buchdag** [comment]
Have you considered using / tried [`DEFAULT_HOST`](https://github.com/nginx-proxy/nginx-proxy#default-host) ?

**Comment by tkw1536** [comment]
Yes, but it's not a good solution in this case because I also have a wildcard CNAME pointing to the server (and I'd like the default host to actually be something sensible). 

I guess as a workaround I could probably just have a custom configuration for the default host (with an "if" in the nginx config that checks the host header or something). 
But that seems like a hack, and just looking over the readme I would have expected that VIRTUAL_HOST works for anything that is a valid nginx server_name. 

And this did work on previous versions, and only broke with the patch upgrade from 0.9.0->0.9.1.  Curiously, using a raw ipv4 address still works, it's just ipv6 that broke.

**Comment by buchdag** [comment]
I'm not entirely sure that #1163 is the culprit as nginx logs are complaining about an invalid **host** inside the upstream, not about the upstream name itself. Could you give me the output of `docker exec yournginxproxycontainer nginx -T` ?

**Comment by tkw1536** [comment]
```
$ docker exec web_nginx-proxy_1 nginx -T
2021/07/15 18:41:49 [emerg] 128#128: invalid port in upstream "2001:638:(rest of ipv6 censored)]-upstream" in /etc/nginx/conf.d/default.conf:104
nginx: [emerg] invalid port in upstream "2001:638:(rest of ipv6 censored)]-upstream" in /etc/nginx/conf.d/default.conf:104
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Relevant part of /etc/nginx/conf.d/default.conf:

```
upstream 2001:638:(rest of ipv6 censored)]-upstream {
	## Can be connected with "distillery" network
	# tarpit_httptarpit_1
	server 172.19.0.12:8080;
}
server {
	server_name 2001:638:(rest of ipv6 censored)];
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://2001:638:(rest of ipv6 censored)]-upstream;
	}
}
server {
	server_name 2001:638:(rest of ipv6 censored)];
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	return 500;
	ssl_certificate /etc/nginx/certs/default.crt;
	ssl_certificate_key /etc/nginx/certs/default.key;
}
```

On closer investigation it seems like all the `server_name`s are missing a leading "[" in their upstream names. Not sure why.

**Comment by buchdag** [comment]
My take on this is that #1163 is legit in the sense that the `upstream` name should be an alias and not a real FQDN (which might be a source of issue), but there is close to zero guidance or best practice around this on the nginx doc. I'm still not sure what would be the best way to fix your issue.

If you try to manually remove the closing `]` in your `upstream` name on the rendered `/etc/nginx/conf.d/default.conf`, does that fix the problem ?

**Comment by buchdag** [comment]
@tkw1536 any luck trying to remove the closing `]` ?

I'm thinking about either:
- Having the template strip identified incorrect characters in the context of an upstream name
- Replacing the `domain-upstream` name with a hash of the `VIRTUAL_HOST` in all case, not just if it's a regexp

The second option seems to be the simplest and safest solution against those kind of issues, but it would be at the expanse of people that relied on an easily predictable `upstream` name.

I've pushed an image that uses the second solution as `nginxproxy/nginx-proxy:1693`, if you want to give it a try.

**Comment by tkw1536** [comment]
Sorry, haven't gotten to this yet, especially because to achieve this I need to (intentionally) break my production setup. I don't have a separate playground machine with a public ipv6 for testing at the moment.

**Comment by akpircher** [comment]
> @tkw1536 any luck trying to remove the closing `]` ?
> 
> I'm thinking about either:
> 
> * Having the template strip identified incorrect characters in the context of an upstream name
> * Replacing the `domain-upstream` name with a hash of the `VIRTUAL_HOST` in all case, not just if it's a regexp
> 
> The second option seems to be the simplest and safest solution against those kind of issues, but it would be at the expanse of people that relied on an easily predictable `upstream` name.
> 
> I've pushed an image that uses the second solution as `nginxproxy/nginx-proxy:1693`, if you want to give it a try.

I am, unfortunately, one of the people who relied on a predictable `upstream` name. I noticed my setups suddenly not working yesterday 3 hours after this was merged. 

I wasn't planning on saying anything, because I'm okay with pinning to 0.9.1, but after sleeping on it, thought I should because I don't want to miss important security updates.

Is there a way to make this configurable? Something like `PREDICTABLE_UPSTREAM=true` meaning we get the predictable upstream  name, but by default we'll get the hash?

**Comment by buchdag** [comment]
@akpircher could you open a new issue so we can discuss and track this ?
