### ISSUE TITLE
Use labels instead of env variables

### ISSUE THREAD

**Issue by Nadrieril** [nginx-proxy/nginx-proxy#172]
With the new labels addition to docker 1.6 (https://docs.docker.com/userguide/labels-custom-metadata), it would be cleaner to use labels instead of environment variables.

For example, we could set the label 'com.jwilder.nginx-proxy.virtual-host' to the host we want, and so on.

It need not be a breaking change, you can handle both behaviours at the same time

**Comment by thaJeztah** [comment]
+1 thinking of this, I think I actually suggested this in https://github.com/jwilder/nginx-proxy/issues/36#issuecomment-98262304

Labels were already suggested in https://github.com/jwilder/docker-gen/issues/81 and implemented in https://github.com/jwilder/docker-gen/pull/82

So, it looks like this should be possible, with a modified template?

**Comment by md5** [comment]
@thaJeztah I think a new release of `docker-gen` still needs to be cut to include the latest changes.

**Comment by jwilder** [comment]
Yeah, env vars were initially used because labels didn't exist at the time.  I'm in favor of supporting labels.  though.

**Comment by jwilder** [comment]
docker-gen 0.4.0 has label support now.

**Comment by mathroc** [comment]
just a recommendation for when choosing the labels name "It's recommended that you use reverse-DNS notation to prevent your labels from conflicting with those used by other software." ( https://github.com/docker/compose/blob/master/docs/yml.md#labels )

also, it could replace #60

**Comment by thaJeztah** [comment]
> It's recommended that you use reverse-DNS notation

:+1: I mentioned that in my original https://github.com/jwilder/nginx-proxy/issues/36#issuecomment-98262304, but forgot to repeat it here. Thanks for the reminder!

**Comment by iBobik** [comment]
Sorry for dump question.

Does in mean that it will be possible to change e.g. host without restarting container?

**Comment by md5** [comment]
@iBobik Labels can only be set when a container is started (as far as I know), so supporting labels wouldn't help you change a hostname without restarting a container.

**Comment by Boran** [comment]
@iBobik : I think labels can only be set when creating (not starting) a container,  i.e. same limits as environment variables. It would be grate if a container could be stopped, labels changed and restarted.

**Comment by ibnesayeed** [comment]
What is stopping this from happening?

**Comment by iBobik** [comment]
Approve from the @jwilder :-)



Jan Pobořil
http://honza.poboril.cz

**Comment by mathroc** [comment]
@iBobik, @jwilder already said he is in favor of supporting labels. maybe what's needed is a PR

ps: I guess the image should still support env vars too, labels should probably have higher priority than env var

**Comment by ibnesayeed** [comment]
> @mathroc: guess the image should still support env vars too...

Absolutely! There is no reason to break the backward compatibility for such a popular image.

**Comment by ibnesayeed** [comment]
> @Boran: @iBobik : I think labels can only be set when creating (not starting) a container, i.e. same limits as environment variables. It would be grate if a container could be stopped, labels changed and restarted.

This doesn't seem to be true now (maybe it was the case when you posted, but I doubt).

```
$ docker run --rm -it -e FOO=bar ubuntu
root@07ff6061fec7:/# echo $FOO
bar
```

Similarly,

```
$ docker run -d -l foo=bar --name=label-test ubuntu
$ docker inspect label-test | grep foo
                "foo": "bar"
$ docker rm label-test
```

The following is indeed present.

```
"Config": {
    "Labels": {
        "foo": "bar"
    }
}
```

**Comment by thaJeztah** [comment]
@ibnesayeed what @Boran meant is that once a container is created, the labels cannot be updated, i.e. after `docker create` or `docker run` (which is `docker create` + `docker start`), you cannot update the labels without recreating the container.

t.b.h., I think that's ok, as container should be considered immutable, but there may be use cases that would like to do so without recreating the container.

**Comment by ibnesayeed** [comment]
@thaJeztah thanks for the clarification.

And yes, I too agree that containers are supposed to be immutable configuration wise and stateless when run so that other instances can be created from the corresponding image anytime and any number of times independently. This seems true for most of the practical cases where this image might be used. However, situations where keeping state is desired, how often those containers would switch domain names in their life time in any practical application? Having said that, if the env vars are there as a fallback then those niche cases can utilize that while rest of the community takes advantage of labels.

**Comment by ibnesayeed** [comment]
> @mathroc: ... maybe what's needed is a PR

What is the scope of changes in order to support this? I guess the template is where all the magic will happen. Is there any other place where the changes needs to go?

**Comment by bddenhartog** [comment]
If nobody has started working on this yet, I'd be happy to. I likely won't have time to complete it for another week or two, however.

**Comment by iBobik** [comment]
I use Rancher orchestrator and switched from nginx-proxy to Rancher active proxy (what seems like fork) what works with labels. Maybe useful inspiration.

https://gitlab.com/adi90x/rancher-active-proxy

Jan Pobořil
http://honza.poboril.cz/

22. 9. 2017 v 16:58, Benjamin Denhartog <notifications@github.com>:

**Comment by Nadrieril** [comment]
I have not used docker or this project in 5 years now, and this issue seems dead. I'll close this and someone else can open it again if they're interested.

**Comment by anLizard** [comment]
I'd be very interested in this feature, as label changes on containers do not require the container to be rebuilt.
Like mentioned before, support for both environment variables and labels seems like a good idea.

**Comment by sudoforge** [comment]
You might be interested in [traefik](https://github.com/traefik/traefik) for local use instead of this.

**Comment by anLizard** [comment]
> You might be interested in [traefik](https://github.com/traefik/traefik) for local use instead of this.

I've actually used both Traefik and [Caddy-Docker-Proxy](https://github.com/lucaslorentz/caddy-docker-proxy) before, which is how I know about labels in the first place.

Traefik ended up being too confusing and convoluted to set up, and Caddy-Docker-Proxy was lacking in features.

Nginx-proxy/dockergen with nginx is just the right level of versitility and simplicity, but that's the one feature I've been missing!

**Comment by buchdag** [comment]
@anLizard does the Docker daemon emit an event when there is a label change on a container ?
