### ISSUE TITLE
Can't reverse proxify Websocket with em-websocket

### ISSUE THREAD

**Issue by thypon** [nginx-proxy/nginx-proxy#175]
```
jukechat * 2015-06-06 01:14:43 - EventMachine::WebSocket::HandshakeError - Connection and Upgrade headers required:
```

This is the server side error. While client side chrome console returns this:

```
WebSocket connection to '...' failed: Error during WebSocket handshake: Unexpected response code: 500
polimi:19 Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
```

The application actually works without nginx reverse proxy behind or with heroku proxies.

I hope it'd be helpful. Nice work. :-)

**Comment by tkw1536** [comment]
This issue is several years old.

I believe websocket support was merged in #46, if this still does not work please reopen.
