### ISSUE TITLE
bad permissions:  nginx-proxy image on dockerhub has world writable files in /app

### ISSUE THREAD

**Issue by agmorey** [nginx-proxy/nginx-proxy#1769]
In secure environments where world writable files are not permitted on the docker host, the nginx-proxy container's volume create world writable (and world executable) files in /var/lib/docker... from the container's /app directory.

If you attach to a running container and ls -l in /app, you will see the files have permission 666, rw to owner, group and other, these should be something like 640, plus x as needed.

Building the image from the Dockerfile myself, the files are not world writable, perhaps the extra permissions are added during the GitHub Action nginx-proxy build?

One solution after COPY . /app in the Dockerfile may be RUN chmod -R o-rw ./app.

*bad permissions are also in the alpine image.

**Comment by buchdag** [comment]
@agmorey interesting, I don't get why / how the GitHub Actions build result in different permissions for those files, do you have any clue ?

**Comment by thaJeztah** [comment]
I saw this ticket in my notifications and asked @crazy-max to have a look, as he knows _waaaay_ more about the github actions builds than I do, and he _may_ have found something (see https://github.com/nginx-proxy/nginx-proxy/pull/1770)

**Comment by crazy-max** [comment]
Looks good now with the latest build:

```
$ docker run --rm -it --entrypoint '' jwilder/nginx-proxy:alpine sh -c "stat -c '%a %n' *"
644 Dockerfile
644 Dockerfile.alpine
644 LICENSE
644 Procfile
644 dhparam.pem.default
644 docker-compose-separate-containers.yml
644 docker-compose.yml
755 docker-entrypoint.sh
755 generate-dhparam.sh
644 network_internal.conf
644 nginx.tmpl
```

**Comment by thaJeztah** [comment]
> I also wonder why the Dockerfile is added to the image. Is it expected? If not I suggest to rely on a rootfs folder in the repo and use COPY rootfs/ / instead of COPY . /app/

Yes, I was also looking at that (either a subdirectory, or more specific `COPY` commands that copy what's needed); doing so would also make the `.dockerignore` redundant (likely)

**Comment by buchdag** [comment]
Given the low amount of stuff we're copying, we could also ignore everything then selectively allow what's needed.

**Comment by thaJeztah** [comment]
> we could also ignore everything then selectively allow what's needed.

If the Dockerfile is specific enough, a `.dockerignore` may not be needed at all. The "classic" builder blindly created a `.tar` of _all files_ in the build-context and sent that to the daemon before starting the build, even if none of those files would be used during the build. This was not very efficient (sending too much data, even if nothing that's used in the Dockerfile changed).

When using Buildkit (or buildx), docker uses a session to only copy what's needed by the Dockerfile. This means that if the Dockerfile (for example) contains `COPY one-file.txt /somewhere`, the daemon _requests_ that single file from the client during the build, and nothing else will be sent (and unrelated changes in other files will not invalidate the build-cache).

So if the Dockerfile is specific enough to specify only the files that are actually needed, the `.dockerignore` can be removed (making the Dockerfile itself describe what's needed without having to maintain both).

**Comment by buchdag** [comment]
@thaJeztah thanks for the info. Do you think maintaining a `.dockerignore` for people that build locally with a Docker version that does not use Buildkit is worth the hassle ? I'd say no.

**Comment by thaJeztah** [comment]
> Do you think maintaining a .dockerignore for people that build locally with a Docker version that does not use Buildkit is worth the hassle ? I'd say no.

If the Dockerfile is updated, I don't think there's a strict need to keep it. Users that don't use BuildKit _will_ get worse performance (because of the things I outlined), but it should generally still "work".

People using Docker Desktop would already have BuildKit enabled by default, but it would be good to update the README and/or other instructions that outline how to build the image. and update them to include `DOCKER_BUILDKIT=1`.

Overall, the recommendation is to use BuildKit (or buildx) for building; development on the "classic" builder is mostly frozen (except for the occasional bug fix and/or changes that help users to transition to BuildKit). We haven't changed the default on Linux (yet), but are planning to do so at some point.
