### ISSUE TITLE
Custom vhost config not applying on 400 response

### ISSUE THREAD

**Issue by zawwz** [nginx-proxy/nginx-proxy#1818]
I have custom configs in `vhost.d`, notably adding headers:
```
add_header Content-Security-Policy "frame-ancestors 'self' https://example.com";
```
This config applies as expected on 200 and 300 responses from the proxied server:
```
$ curl -I https://mysite.com/
HTTP/2 200 
date: Thu, 04 Nov 2021 13:30:18 GMT
content-type: text/html; charset=utf-8
server: Caddy
strict-transport-security: max-age=31536000
content-security-policy: frame-ancestors 'self' https://example.com
```
However when the proxied server sends a 400 response, this header config disappears:
```
$ curl -I https://mysite.com/doesntexist
HTTP/2 404 
date: Thu, 04 Nov 2021 13:26:11 GMT
server: Caddy
strict-transport-security: max-age=31536000
```

In my case, this causes issues when using iframes, and an action causes a 404 or 401 response. The response doesn't contain the CSP header anymore therefore the page gets blocked instead of redirecting properly.

Note: in my case the `server` header is not set to nginx because i have set the config `proxy_pass_header Server;`

**Comment by buchdag** [comment]
Hi @zawwz 

Have you tried this : https://ma.ttias.be/nginx-add_header-not-working-on-404 ?

**Comment by zawwz** [comment]
That was indeed the issue!
Thanks for your help
