### ISSUE TITLE
Shows 0 hosts but have 4 - most current version, today updated with "apt update && apt upgrade"

### ISSUE THREAD

**Issue by jayjupdhig** [nginx-proxy/nginx-proxy#1851]
![1](https://user-images.githubusercontent.com/42765391/147339928-88873d8f-6633-4791-83e1-fa1803c6ef7b.jpg)
![2](https://user-images.githubusercontent.com/42765391/147339935-5140126e-5cf8-4438-bcc3-87ca8808a720.jpg)

Regards, Jan

**Comment by buchdag** [comment]
Hi.

Wrong repository, you are looking for https://github.com/jc21/nginx-proxy-manager

This project is not related to nginx proxy manager.

**Comment by jayjupdhig** [comment]
ok thx

**Comment by jayjupdhig** [comment]
-> https://github.com/jc21/nginx-proxy-manager/issues/1679
