### ISSUE TITLE
Can't use SSL locally

### ISSUE THREAD

**Issue by patriceckhart** [nginx-proxy/nginx-proxy#1879]
I have now configured everything to reach my web container via https. Unfortunately, the proxy always throws the following error when accessing `http://dev.local`. With `https://` it doesn't work at all (browser error).

2022/01/29 16:03:43 [error] 418#418: *36 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.17.0.1, server: dev.local, request: "GET /favicon.ico HTTP/1.1", upstream: "https://172.22.0.5:80/favicon.ico", host: "dev.local", referrer: "http://dev.local/"

`docker run -d --name my_https_proxy -p 80:80 -p 443:443 -v /var/run/docker.sock:/tmp/docker.sock:ro -v ./certs:/etc/nginx/certs jwilder/nginx-proxy`

and the envvar `VIRTUAL_PROTO=https` in my web container

I'm on Apple silicon

**Comment by exussum12** [comment]
VIRTUAL_PROTO=https

Means access the internal version over https too. Which I assume you don't want to do ? Normally you terminate the TLS(SSL) at the web server

The error seems to suggest that your internal container is not responding with a hand shake.

I would get rid of that environment variable and try again

**Comment by buchdag** [comment]
@patriceckhart you should try @exussum12 suggestion.

**Comment by patriceckhart** [comment]
My container was running in http and that was exactly the problem. I removed VIRTUAL_PROTO and now it works.
