### ISSUE TITLE
Wordpress 504 Gateway Time-out

### ISSUE THREAD

**Issue by serge-jerkezian** [nginx-proxy/nginx-proxy#1880]
Running from readme both nginx-proxy with acme-companion [latest] (companion seems fine because i can see the SSL)

"NGINX_PROXY_VERSION=0.10.0-11-g42c8b0c"

```
$ docker run --detach \
    --name nginx-proxy \
    --publish 80:80 \
    --publish 443:443 \
    --volume certs:/etc/nginx/certs \
    --volume vhost:/etc/nginx/vhost.d \
    --volume html:/usr/share/nginx/html \
    --volume /var/run/docker.sock:/tmp/docker.sock:ro \
    nginxproxy/nginx-proxy
```

```
$ docker run --detach \
    --name nginx-proxy-acme \
    --volumes-from nginx-proxy \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    --volume acme:/etc/acme.sh \
    --env "DEFAULT_EMAIL=mail@yourdomain.tld" \
    nginxproxy/acme-companion
```

DockerFile for Wordpress:

```
FROM php:7.1.8-apache

EXPOSE 80 443

COPY . .

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

RUN chown -R www-data:www-data . \
    && a2enmod rewrite

```

And I run:
`docker build -t projectNameHere ./projectNameHere && docker run -e VIRTUAL_HOST=test.com -e LETSENCRYPT_EMAIL=test@gmail.com -e LETSENCRYPT_HOST=test.com -d --name projectNameHere  projectNameHere `

When I try to access their website I get:
504 Gateway Time-out
nginx/1.21.5

Checked the logs for the nginx-proxy and found:
`79 upstream timed out (110: Connection timed out) while reading response header from upstream`

**Comment by rjsteinert** [comment]
Just passing through seeing timeouts when using nginx-proxy as well. My guess right now is I need to set some config variables like...

```
  proxy_connect_timeout       600;
  proxy_send_timeout          600;
  proxy_read_timeout          600;
  send_timeout                600;
```

Just need to find the easy way to do it. Configuring according to the README sound difficult. https://github.com/nginx-proxy/nginx-proxy#custom-nginx-configuration

**Comment by serge-jerkezian** [comment]
@rjsteinert i would doubt its a timeout issue.  I would guess it's some underlying configuration that is not able to parse or reach something when its a Wordpress based or Apache behind the nginx-proxy.

Am using Debian 11 if that makes any difference.

Thank you for your input @rjsteinert

**Comment by buchdag** [comment]
@serge-jerkezian are you certain your wordpress container is working correctly when not behind nginx-proxy ?

**Comment by exussum12** [comment]
Run 

docker exec nginx-proxy cat /etc/nginx/conf.d/default.conf 

And paste the generated config. The generated config usually has some comments on reasons you can't connect

**Comment by serge-jerkezian** [comment]
@buchdag @exussum12  thank you for your help, I manually added docker network and added the apps to it and it seems to be working now.
