### ISSUE TITLE
Dynamic proxy_pass in nginx based on query string value

### ISSUE THREAD

**Issue by znyrraj** [nginx-proxy/nginx-proxy#1923]
How to dynamic proxy_pass in nginx based on query string
for example if user call **http://example.com/print?host=project1** this URL
I need to proxy pass this URL to **http://project1:3333**
project1 is available in my local network only
Now my nginx conf look like

`proxy_pass http://$arg_host:3333`

It won't work. Any suggestions to achieve this Thanks in advance.

**Comment by buchdag** [comment]
Hi.

This project uses Nginx but is distinct from it, and we don't provide support for Nginx.

Please check https://www.nginx.com/resources/wiki/community/
