### ISSUE TITLE
Forward requests transparently

### ISSUE THREAD

**Issue by steho** [nginx-proxy/nginx-proxy#195]
Hello,

I am trying to use tuleap (https://registry.hub.docker.com/u/enalean/tuleap-aio/) behind nginx-proxy and always get "The page isn't redirecting properly" in my browser. Running the image on its own works.

I am not able to analyse the issue, but assume that it is caused by nginx-proxy doing its own redirects from http to https.

Thus I am looking for a method to disable this feature and let nginx-proxy forward any request as it is.

Thanks for any advice.

Stephan

**Comment by taxilian** [comment]
Pull request #215 would let you customize these settings yourself

**Comment by buchdag** [comment]
No longer relevant (#215 and #298), closing.
