### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by jwilder** [nginx-proxy/nginx-proxy#197]
The functionality in this image is complicated enough that some unit tests would be useful to test PRs against.

Something simple where each test could start an `nginx-proxy` container and sub-containers in various configuration and issue curl commands to return to verify result would be nice.

**Comment by chaos95** [comment]
The unit and integration test suite over at [docker-compose](https://github.com/docker/compose) is pretty solid, and built around standing up test containers in various configurations. Might be worth looking to them for inspiration?

**Comment by dmp1ce** [comment]
Should this be closed? Tests are running. I did notice that the tests do not clean up containers they create. I'll create another issue for that.

**Comment by buchdag** [comment]
Closed by #197 and #655
