### ISSUE TITLE
Per-VIRTUAL_PATH location configuration inserted twice

### ISSUE THREAD

**Issue by darkopetreski** [nginx-proxy/nginx-proxy#1973]
I have created a VIRTUAL_PATH=/shop. Then I tried to add Per-VIRTUAL_PATH location configuration to add some basic authentication for the admin part of the shop. The file name with path hash is "www.testdomain.com_c2fc0d1d1467225434f5fef653fc84d17f2fe0d7_location"

Here is a part of the generated conf using ngxinx -T
```nginx
....

server {
        server_name www.testdomain.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://www.testdomain.com-42099b4af021e53fd8fd4e056c2568d7c2e3ffa8;
        }
        location /shop {
                proxy_pass http://www.testdomain.com-c2fc0d1d1467225434f5fef653fc84d17f2fe0d7;
                include /etc/nginx/vhost.d/www.testdomain.com_c2fc0d1d1467225434f5fef653fc84d17f2fe0d7_location;
        }
}

# configuration file /etc/nginx/vhost.d/www.testdomain.com_c2fc0d1d1467225434f5fef653fc84d17f2fe0d7_location:
location /shop/wp-login {
   auth_basic "Login area";
   auth_basic_user_file /etc/nginx/vhost.d/passwords;
}

....

```
The file is included inside the "location /shop" as expected:
```nginx
include /etc/nginx/vhost.d/www.testdomain.com_c2fc0d1d1467225434f5fef653fc84d17f2fe0d7_location;
```

But the content of the file is included one more time in the configuration file:
```nginx
# configuration file /etc/nginx/vhost.d/www.testdomain.com_c2fc0d1d1467225434f5fef653fc84d17f2fe0d7_location:
location /shop/wp-login {
   auth_basic "Login area";
   auth_basic_user_file /etc/nginx/vhost.d/passwords;
}
```

Expected behavior: The Per-Virtual_path file should be included only once.

The generated file /etc/nginx/conf.d/default.conf is correctly generated and does not contain the duplicate part.
But when I list what is loaded with "ngxinx -T" the extra part is shown.

Maybe everything is ok and "ngxinx -T" show it wrongly ?

I am using separate nginx and docker-gen.
Nginx: stable-alpine version 1.20.2
Docker gen version: 0.9.0

**Comment by darkopetreski** [comment]
The generated config file is correct. I will close this ticket.

**Comment by tkw1536** [comment]
Closing as requested
