### ISSUE TITLE
xip.io is no more.  nip.io

### ISSUE THREAD

**Issue by kwerle** [nginx-proxy/nginx-proxy#1983]
You make reference to xip.io in your README.  

xip.io is no more (at the very least, they no longer have a valid web presence).  nip.io does the same thing.

**Comment by amentors** [comment]
culd u make a new one the one you sent is blocked please i loved this what
went wrong

**Comment by kwerle** [comment]
> culd u make a new one the one you sent is blocked please i loved this what went wrong

If https://nip.io/ is blocked for you I don't know how I might help.

**Comment by buchdag** [comment]
@kwerle xip.io was replaced by nip.io in the repository docs last February.

If you're referring to nginxproxy/nginx-proxy README on Docker Hub, it's been fixed.

If you're referring to jwilder/nginx-proxy README on Docker Hub, we have no control over it and can't change this.
