### ISSUE TITLE
deluge Connection refused & 502 Bad Gateway"

### ISSUE THREAD

**Issue by valerebron** [nginx-proxy/nginx-proxy#2033]
first of all, thanks for nginx-proxy, it helped me a lot for building this: https://github.com/valerebron/pegaz
It's a cli for deploying services with multiple docker-compose.
I try ti add deluge to it (linuxserver/deluge).
all works fine expect the nginx-proxy part, here my docker-compose:
https://github.com/valerebron/pegaz/blob/master/services/deluge/docker-compose.yml

Generated code will be something like this:

`version: "3.7"
services:

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    restart: unless-stopped
    ports:
      - 7733:8112
    volumes:
      - config:/config
    environment:
      VIRTUAL_PORT: "7733"
      VIRTUAL_HOST: "deluge.domain.com"
      LETSENCRYPT_HOST: "deluge.domain.com"
      LETSENCRYPT_EMAIL: "user@domain.com"
      PUID: "1000"
      PGID: "1000"

  proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      HTTP_PORT: "80"
      HTTPS_PORT: "443"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: proxy-acme
    restart: unless-stopped
    depends_on:
      - proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: "proxy"
      DEFAULT_EMAIL: "user@domain.com"

volumes:
  config:

networks:
  default:
    external:
      name: pegaz
`

127.0.0.1:7732 works fine but deluge.domain.com return a "502 Bad Gateway"
Also proxy logs return a "Connection refused"

Do you have any idea ?

**Comment by DEvil0000** [comment]
see #750

**Comment by Glydric22** [comment]
for what i know internally it uses port 8000, so you can't define another port, also this is not usefull because it is only internal port

**Comment by valerebron** [comment]
Ok, with native port set to 8112, it works.
There might be seetings with this port hardcoded in dockerhub's linuxserver/deluge images ...

**Comment by biladina** [comment]
> Ok, with native port set to 8112, it works. There might be seetings with this port hardcoded in dockerhub's linuxserver/deluge image ...

hi, I have same problem, can I know how you solve the problem??

**Comment by valerebron** [comment]
I just set VIRTUAL_PORT: "8112".

You'll find config & docker-compose files here :
https://github.com/valerebron/pegaz/tree/master/services/deluge

**Comment by biladina** [comment]
> I just set VIRTUAL_PORT: "8112".
> 
> You'll find config & docker-compose files here : https://github.com/valerebron/pegaz/tree/master/services/deluge

ok, thank you, I will look into it..
