### ISSUE TITLE
Proxy two Ports instead of one using VIRTUAL_PORT

### ISSUE THREAD

**Issue by julianlaibach** [nginx-proxy/nginx-proxy#2050]
Thank you for this Docker Image!
I was wondering if its possible to expose multiple Ports and Proxy Pass them with different Domains from one Docker Image.
I currently need to Proxy Pass a Vite HMR on Port 8000 and also the normal HTTP Port 80, is this currently Possible?

VIRTUAL_HOST: "test.tld:80, hmr.test.tld:8000"

Or is there anything i can do except creating a custom.conf?

Thanks in advance,
Julian

**Comment by DjordyKoert** [comment]
Hey I'm messaging here to hopefully help some more people that share this problem.

This feature is not currently available on this docker image as can be read [here](https://github.com/nginx-proxy/nginx-proxy/issues/1463#issuecomment-652351459).
I also needed this for one of my own projects and have chosen to [use a fork of this project](https://github.com/pini-gh/nginx-proxy#virtual-ports). This is working perfectly for my setup.

**Comment by julianlaibach** [comment]
This i pretty helpful @DjordyKoert! Thank you a lot.

**Comment by matti** [comment]
also https://github.com/mesudip/nginx-proxy implements this
