### ISSUE TITLE
Nginx return 500 randomly (cache ? )

### ISSUE THREAD

**Issue by awerner25** [nginx-proxy/nginx-proxy#2052]
Hello,

I use the latest version of nginx-proxy.
For a service, nginx return 500 randomly. I think it's the cache because if I try to do the same requests directly to my application (without the nginx-proxy) it's work perfectly.
And when I got 500 error, I have a trace in nginx-proxy access log but not in my application access log.

I tried to add `proxy_cache                     off;` in `/etc/nginx/vhost.d/my_service_url` but without success.

**Comment by joker-777** [comment]
@awerner25 Hi, we are having the same problem. Were you able to fix it?
