### ISSUE TITLE
Update ULRs: jwilder -> nginxproxy

### ISSUE THREAD

**Issue by KES777** [nginx-proxy/nginx-proxy#2087]
Bug description
-----------------

Page https://hub.docker.com/r/nginxproxy/nginx-proxy refers to https://hub.docker.com/r/jwilder/docker-gen

But, it seems, it should refer to https://hub.docker.com/r/nginxproxy/docker-gen

**Comment by buchdag** [comment]
@KES777 last time I checked I was unable to edit the readme of https://hub.docker.com/r/nginxproxy/nginx-proxy due to what appeared like a bug on hub.docker.com's end. I contacted them but never got any answer. I'll try again soonish.

**Comment by buchdag** [comment]
Seems to have worked this time, let me know if you spot errors.

**Comment by KES777** [comment]
Seems no errors.
