### ISSUE TITLE
Inside a private network need to redirect a request via Another External proxy

### ISSUE THREAD

**Issue by AakarshitAgarwal** [nginx-proxy/nginx-proxy#2096]
### Discussed in https://github.com/nginx-proxy/nginx-proxy/discussions/2095

<div type='discussions-op-text'>

<sup>Originally posted by **AakarshitAgarwal** November 25, 2022</sup>
Hello,

Inside a private network, I want to redirect a request via another External proxy.

Brief -> 

I want my URL ( https://example1.com/ ) when having the path specified as ( https://example1.com/tunnel/portnumber ) it will redirect my request to another URL 
( https://example2/api/number1/xyz/ ) via an External proxy ( x.x.x.x )

I tried many nginx.conf but was not able to redirect my request.

example ->

```
    server {
    listen XXXXX;
    proxy_connect;
    proxy_connect_address X.X.X.X:port1;       #external proxy IP with port
    proxy_connect_allow   443 port1;
    add_header Strict-Transport-Security max-age=1209600;

    location ~ ^/tunnel/number1 {.                                       #path header in URL
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass https://example2/api/number1/xyz/;      #path where I want to forward the request inside a network
        error_page 301 302 307 =200 @redir;
    }

    location @redir {
         proxy_intercept_errors on;
         proxy_pass_request_headers on;
         proxy_set_header X-Forwarded-Proto https;
         proxy_ssl_server_name on;
         proxy_ssl_protocols TLSv1.1 TLSv1.2;
         set $orig_loc $upstream_http_location;
         add_header cross-origin-resource-policy "cross-origin";
         add_header xyz-location $orig_loc;
         proxy_pass $orig_loc;
        }
    }
```
    
Please help me know if it is possible, and if yes in what way?
</div>

**Comment by buchdag** [comment]
HI.

Please do not open issues for Discussion material.
