### ISSUE TITLE
Error "Bad gRPC response. HTTP status code: 500" when set $var in NGINX grpc_pass

### ISSUE THREAD

**Issue by Kotnstantin** [nginx-proxy/nginx-proxy#2114]
When i set $var in grpc_pass i can't connect grpc-client to server, I get the FAIL error

 `  [Microsoft.Extensions.Hosting.Internal.Host)
   [BackgroundServiceFaulted status   BackgroundServledGrpc.Co.RpcException
(StatusCode="Unknown", Detail="Bad gRPC response. HTTP status code: 500")`

The purpose of setting a variable is to bypass the situation where one of the services that proxies NGINX crashes, and when NGINX restarts, the other services continue to work. With proxy_pass directive all works and tests are successful, with grpc_pass - no

  `location / {
        resolver 127.0.0.11 valid=30s;
        set $webuidev https://dev_webuidev;
        proxy_pass $webuidev;

        #proxy_pass https://dev_webuidev;
        # Configuration for WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_cache off;
        # WebSockets were implemented after http/1.0
        proxy_http_version 1.1;
        # Configuration for ServerSentEvents
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;   
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-URL-SCHEME https;
    }
    location /App.Room.Api.Contract.ApiService/UpdateOpcDaTags {
        resolver 127.0.0.11 valid=30s;
        set $grpc_webuidev grpcs://dev_webuidev;
        grpc_pass $grpc_webuidev;

        #grpc_pass grpcs://dev_webuidev;
    }`
    
    how to setup nginx not to crash if grpc server`s hostname in upstream is not found?

**Comment by buchdag** [comment]
Please don't open an issue in addition to a discussion : https://github.com/nginx-proxy/nginx-proxy/discussions/2113
