### ISSUE TITLE
$DEBUG environment variable

### ISSUE THREAD

**Issue by GGORG0** [nginx-proxy/nginx-proxy#2139]
(version: `nginx-proxy:1.1`)

Hey. One of my containers (specifically [wg-easy](https://github.com/WeeJeWel/wg-easy/blob/bbd19b7a6f390d95d80aab75271a24b92f6c591e/Dockerfile#L46)) uses the `$DEBUG` variable from inside and nginx-proxy picks it up [here](https://github.com/nginx-proxy/nginx-proxy/blob/5d22134ee6d37f5f5712aadde6ee2eda85e25956/nginx.tmpl#L113) and spams the entire log with errors while not generating the config. Stopping wg-easy helps, but then I lose access to my home so that's not a good solution. Also, the variable should be named differently, like `NGINX_PROXY_DEBUG`, because other apps may just read it and trigger some internal debugging too.

Thanks

Edit: sorry if this is a duplicate, but the word "DEBUG" doesn't help much in the github's search engine

**Comment by rhansen** [comment]
> spams the entire log with errors

What are the errors?  Do they go away if you unset `DEBUG` for your container?

**Comment by buchdag** [comment]
@GGORG0 using a variable with a name as generic as `DEBUG` on proxied containers was a poor choice (on this project side) to begin with.

**Comment by GGORG0** [comment]
Well, for everyone here asking: `DEBUG` is being set **by the container itself from the inside**. I have no way to unset it at the moment.
Also, I **think** that it has something to do with wg-easy using [this package](https://www.npmjs.com/package/debug) - [search for "DEBUG" in the repo](https://github.com/WeeJeWel/wg-easy/search?q=DEBUG)

**Comment by rhansen** [comment]
> `DEBUG` is being set **by the container itself from the inside**.

Technically it is set by the Docker daemon during container start-up.

> I have no way to unset it at the moment.

You should be able to override the value from the image and set it to the empty string by passing `--env DEBUG=` to `docker run` or adding `DEBUG: ""` to the `environment` section in your Docker compose file.  Hopefully your application container treats empty and unset the same, and hopefully `nginx-proxy` does too.
