### ISSUE TITLE
QUIC and HTTP/3 Support

### ISSUE THREAD

**Issue by QuAzI** [nginx-proxy/nginx-proxy#2170]
Can you support it? Possible in different docker branch while not in mainline
https://www.nginx.com/blog/our-roadmap-quic-http-3-support-nginx/

**Comment by buchdag** [comment]
@QuAzI this won't be supported until QUIC and HTTP/3 are supported in a readily available nginx image maintained by nginx themselves. As noted [here](https://github.com/nginx-proxy/nginx-proxy/pull/1644#issuecomment-860997560) the aim of this project is to be based upon and usable with upstream nginx images. Unfortunately starting to maintain our own nginx images is out of scope.

**Comment by QuAzI** [comment]
What about v1.25 with option `--with-http_v3_module` ?

**Comment by buchdag** [comment]
Unfortunately version 1.25 does not change the fact that nginx has to be manually compiled with a non default option to make QUIC and HTTP/3 support available.

**Comment by buchdag** [comment]
Discussion about QUIC and HTTP/3 support : #2271
