### ISSUE TITLE
nginx-proxy broken in 1.2.3-11-gc353680, 1.2.3-13-g3039d85?

### ISSUE THREAD

**Issue by m-31** [nginx-proxy/nginx-proxy#2208]
nginx-proxy version : 1.2.3-11-gc353680
after upgrading the https-proxy stopped working
Any idea how to solve this?

we got the following results

    curl -kvvv https://localhost
    *   Trying 127.0.0.1:443...
    * Connected to localhost (127.0.0.1) port 443 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * successfully set certificate verify locations:
    *  CAfile: /etc/ssl/certs/ca-certificates.crt
    *  CApath: /etc/ssl/certs
    * TLSv1.3 (OUT), TLS handshake, Client hello (1):
    * TLSv1.3 (IN), TLS alert, internal error (592):
    * error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
    * Closing connection 0
    curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

    openssl s_client -connect localhost:443
    CONNECTED(00000003)
    139732842083648:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1543:SSL alert number 80
    ---
    no peer certificate available
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 7 bytes and written 283 bytes
    Verification: OK
    ---
    New, (NONE), Cipher is (NONE)
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    Early data was not sent
    Verify return code: 0 (ok)

**Comment by buchdag** [comment]
> ## Bugs
> 
> If you are logging a bug, please search the current open issues first to see if there is already a bug opened.
> 
> For bugs, the easier you make it to reproduce the issue you see and the more initial information you provide, the easier and faster the bug can be identified and can get fixed.
> 
> Please at least provide:
> - the exact nginx-proxy version you're using (if using `latest` please make sure it is up to date and provide the version number printed at container startup).
> - complete configuration (compose file, command line, etc) of both your nginx-proxy container(s) and proxied containers. You should redact sensitive info if needed but please provide **full** configurations.
> - generated nginx configuration obtained with `docker exec nameofyournginxproxycontainer nginx -T`
> 
> If you can provide a script or docker-compose file that reproduces the problems, that is very helpful.
> 
> ## General advice about `latest`
> 
> Do not use the `latest` tag for production setups.
> 
> `latest` is nothing more than a convenient default used by Docker if no specific tag is provided, there isn't any strict convention on what goes into this tag over different projects, and it does not carry any promise of stability.
> 
> Using `latest` will most certainly put you at risk of experiencing uncontrolled updates to non backward compatible versions (or versions with breaking changes) and makes it harder for maintainers to track which exact version of the container you are experiencing an issue with.
>

**Comment by m-31** [comment]
Thank you for your quick and competent answer. It's in fact a "latest" problem, with "1.2.3" it doesn't occur. Here the steps for reproduction:

    #!/bin/bash
    set -eox
    SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
    cd "${SCRIPT_DIR}"

    mkdir -p certs
    DNAME="CN=m-31,OU=Nginx Proxy,O=My Company,L=Hamburg,ST=HH,C=DE"
    openssl req -x509 \
      -nodes -days 365 \
      -newkey rsa:4096 \
      -keyout certs/m-31.com.key \
      -out certs/m-31.com.crt \
      -subj "/$DNAME"

    running=$(docker ps -a -q --filter="name=my-nginx-proxy")
    if [[ -n ${running} ]]; then
      docker stop "${running}"
      docker rm "${running}"
    fi

    docker run \
      -l debug \
      --name my-nginx-proxy \
      -d \
      -p 443:443 \
      -v "${SCRIPT_DIR}/certs:/etc/nginx/certs" \
      -v /var/run/docker.sock:/tmp/docker.sock:ro \
      jwilder/nginx-proxy

    docker run \
       --rm \
       -it \
       -e VIRTUAL_HOST="m-31.com" \
       -p 80:80 \
       strm/helloworld-http

Starting the script gives:

    Unable to find image 'jwilder/nginx-proxy:latest' locally
    latest: Pulling from jwilder/nginx-proxy
    f1f26f570256: Pull complete
    7f7f30930c6b: Pull complete
    2836b727df80: Pull complete
    e1eeb0f1c06b: Pull complete
    86b2457cc2b0: Pull complete
    9862f2ee2e8c: Pull complete
    d10c102e64e3: Pull complete
    f538c2d0bd89: Pull complete
    c8c6265b0dee: Pull complete
    e14c9802b1cb: Pull complete
    14a85a84361c: Pull complete
    f6faf0e93537: Pull complete
    4f4fb700ef54: Pull complete
    Digest: sha256:2c256e2ea669b01ee6c2a8a3e3450aced83f1170e3febda603ff9febf29dd5ff
    Status: Downloaded newer image for jwilder/nginx-proxy:latest
    bb13841281ea82ce0436e809c61f1ce4474562f074c4383c5b128fa1621c67a8
    + docker run --rm -it -e VIRTUAL_HOST=m-31.com -p 80:80 strm/helloworld-http
    Serving HTTP on 0.0.0.0 port 80 ...

Testing results:

    curl -vk https://localhost
    *   Trying 127.0.0.1:443...
    * Connected to localhost (127.0.0.1) port 443 (#0)
    * ALPN: offers h2
    * ALPN: offers http/1.1
    * [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
    * LibreSSL/3.3.6: error:1404B438:SSL routines:ST_CONNECT:tlsv1 alert internal error
    * Closing connection 0
    curl: (35) LibreSSL/3.3.6: error:1404B438:SSL routines:ST_CONNECT:tlsv1 alert internal error


    openssl s_client -connect localhost:443
    CONNECTED(00000005)
    140704280281920:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1556:SSL alert number 80
    ---
    no peer certificate available
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 7 bytes and written 293 bytes
    Verification: OK
    ---
    New, (NONE), Cipher is (NONE)
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    Early data was not sent
    Verify return code: 0 (ok)
    ---

**Comment by m-31** [comment]
+ docker run -l debug --name my-nginx-proxy -d -p 443:443 -v /Users/m31/Projects/otto2/quality_overview/application/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
    47b6f799b94fbaf2cf4a1b652ddb065bc7bce87ef9f67fcc586a0304d208e478
    + docker run --rm -it -e VIRTUAL_HOST=m-31.com -p 80:80 strm/helloworld-http
    Serving HTTP on 0.0.0.0 port 80 ...
    172.17.0.2 - - [31/Mar/2023 18:15:35] "GET / HTTP/1.1" 200 -
    
    ❯ curl -vk --resolve m-31.com:443:127.0.0.1 https://m-31.com
    * Added m-31.com:443:127.0.0.1 to DNS cache
    * Hostname m-31.com was found in DNS cache
    *   Trying 127.0.0.1:443...
    * Connected to m-31.com (127.0.0.1) port 443 (#0)
    * ALPN: offers h2
    * ALPN: offers http/1.1
    * [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
    * [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Server hello (2):
    * [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Unknown (8):
    * [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Certificate (11):
    * [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, CERT verify (15):
    * [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Finished (20):
    * [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Finished (20):
    * SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
    * ALPN: server accepted h2
    * Server certificate:
    *  subject: CN=m-31,OU=Nginx Proxy,O=My Company,L=Hamburg,ST=HH,C=DE
    *  start date: Mar 31 18:15:13 2023 GMT
    *  expire date: Mar 30 18:15:13 2024 GMT
    *  issuer: CN=m-31,OU=Nginx Proxy,O=My Company,L=Hamburg,ST=HH,C=DE
    *  SSL certificate verify result: self signed certificate (18), continuing anyway.
    * Using HTTP2, server supports multiplexing
    * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
    * h2h3 [:method: GET]
    * h2h3 [:path: /]
    * h2h3 [:scheme: https]
    * h2h3 [:authority: m-31.com]
    * h2h3 [user-agent: curl/7.87.0]
    * h2h3 [accept: */*]
    * Using Stream ID: 1 (easy handle 0x7fc71000da00)
    > GET / HTTP/2
    > Host: m-31.com
    > user-agent: curl/7.87.0
    > accept: */*
    >
    * Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
    < HTTP/2 200
    < server: nginx/1.23.4
    < date: Fri, 31 Mar 2023 18:15:35 GMT
    < content-type: text/html
    < content-length: 102
    < last-modified: Fri, 31 Mar 2023 18:15:15 GMT
    < strict-transport-security: max-age=31536000
    <
    <html><head><title>HTTP Hello World</title></head><body><h1>Hello from e37649b510af</h1></body></html
    * Connection #0 to host m-31.com left intact

**Comment by buchdag** [comment]
What are we supposed to infer from the previous message ?

**Comment by m-31** [comment]
Yes. It is working. Thank you for your support.
