### ISSUE TITLE
Link to Q&A Group on https://hub.docker.com/r/jwilder/nginx-proxy seems broken

### ISSUE THREAD

**Issue by alberto56** [nginx-proxy/nginx-proxy#2215]
To reproduce:

* Go to https://hub.docker.com/r/jwilder/nginx-proxy
* Click on [Q&A Group](https://groups.google.com/forum/#!forum/nginx-proxy) at the very bottom of the text
* This leads (for me at least) to a broken link

Perhaps this can be updated to https://github.com/nginx-proxy/nginx-proxy/discussions

**Comment by buchdag** [comment]
@alberto56 unfortunately we don't have editing rights on https://hub.docker.com/r/jwilder/nginx-proxy
