### ISSUE TITLE
When using split containers htpasswd should be mapped in both containers

### ISSUE THREAD

**Issue by txomon** [nginx-proxy/nginx-proxy#222]
Hi! I have found from the template that the htpasswd needs to be in both containers (then nginx and the docker-gen one. Maybe update the docs? Or is there any workaround?

**Comment by tkw1536** [comment]
There is documentation for this.

In the [Separate Containers](https://github.com/nginx-proxy/nginx-proxy#separate-containers) section from the README it says:

```
docker run --volumes-from nginx \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    -v $(pwd):/etc/docker-gen/templates \
    -t nginxproxy/docker-gen -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
```
Notice the `--volumes-from` option.
