### ISSUE TITLE
nginx proxy/nginx-proxy and nginx proxy/nginx-proxy with docker swam support

### ISSUE THREAD

**Issue by tdba2599** [nginx-proxy/nginx-proxy#2286]
Up until now, do nginx proxy/nginx-proxy and nginx proxy/nginx-proxy support running on docker swam with multiple replicas.

**Comment by buchdag** [comment]
Hi.

Nope, that's not supported yet.

**Comment by NilsBaumgartner1994** [comment]
Oh shit, this will now totally crash the usage of this :-/
