### ISSUE TITLE
Weird comments cripple default.conf

### ISSUE THREAD

**Issue by landshut-digital** [nginx-proxy/nginx-proxy#2288]
So I couldn't find any hint regarding my problem.
It appears to happen on every version of nginx-proxy from the last year. This makes me think if it's a nginx-proxy problem in general but I've no idea where it could come from...

So this happend:
After a serverrestart my page was not showing in browser anymore.
So I looked into the nginx-proxy container logs and found this (hundreds of lines, not stopping):

```
nginx.1     | 2023/08/22 07:48:07 [emerg] 17971#17971: directive "upstream" has no opening "{" in /etc/nginx/conf.d/default.conf:105
nginx.1     | nginx: [emerg] directive "upstream" has no opening "{" in /etc/nginx/conf.d/default.conf:105
forego      | starting nginx.1 on port 1797400
nginx.1     | 2023/08/22 07:48:07 [emerg] 17972#17972: directive "upstream" has no opening "{" in /etc/nginx/conf.d/default.conf:105
nginx.1     | nginx: [emerg] directive "upstream" has no opening "{" in /etc/nginx/conf.d/default.conf:105
forego      | starting nginx.1 on port 1797500
nginx.1     | 2023/08/22 07:48:07 [emerg] 17973#17973: directive "upstream" has no opening "{" in /etc/nginx/conf.d/default.conf:105
nginx.1     | nginx: [emerg] directive "upstream" has no opening "{" in /etc/nginx/conf.d/default.conf:105
```

I checked the default.conf that is generated every startup and found these german commands (this is only the important section of that file of course):

```
        proxy_pass http://km-test.la-stadt.de                                                   #Variable für NGINX;
        set $upstream_keepalive false;
    }
}
# krankm.la-stadt.de                                                    #Variable für NGINX/
upstream krankm.la-stadt.de                                                     #Variable für NGINX {
    # Container: call_in_sick_live
    #     networks:
    #         andis-custom-net (reachable)
    #     IP address: 172.21.0.2
    #     exposed ports: 3003/tcp
    #     default port: 3003
    #     using port: 3003
    #         /!\ WARNING: Virtual port published on host.  Clients
    #                      might be able to bypass nginx-proxy and
    #                      access the container's server directly.
    server 172.21.0.2:3003;
}
server {
    server_name krankm.la-stadt.de                                                      #Variable für NGINX;
    listen 80 ;
    access_log /var/log/nginx/access.log vhost;
```

One can clearly see that these comments destroy the file by commenting out some functional characters and I've no idea how to get rid of it since it gets created this way at every startup.

Do you know how to solve this?

P.S I work on following versions:
- nginxproxy/nginx-proxy v1.3.1
- nginxproxy/acme-companion v2.2.8

And (don't know if this matter) I use self-signed certs, that I put into the certs folder manually (https://github.com/nginx-proxy/acme-companion/issues/696). But these always worked till last restart.

**Comment by SchoNie** [comment]
Nginx-proxy is not adding that `#Variable für NGINX` comment by itself.
So you probably have overridden the template file yourself and have invalid syntax.
Check the mounts in your docker compose file.

**Comment by landshut-digital** [comment]
Found the problem...
As I already mentioned, the comments did not come from the nginx-projects source, but from my own.
For me it seems like a problem anyway.
I use .env files to store variables. 
I commented every variable after it in the same line using #<comment> which is totally fine for nodejs itself.
But it was not fine for being parsed by nginxproxy.

After removing the comments after both variables VIRTUAL_HOST and LETSENCRYPT_HOST and after restarting the nginxproxy container everything works fine again.

**Comment by buchdag** [comment]
> I commented every variable after it in the same line using # which is totally fine for nodejs itself.

Docker is not nodejs and unfortunately we can't alter the way it parses .env files. You'll probably encounter the same issue with any other image, not just nginx-proxy.
