### ISSUE TITLE
HTTP/2 Rapid Reset Attack

### ISSUE THREAD

**Issue by danil-smirnov** [nginx-proxy/nginx-proxy#2316]
Hi,

There are Steps for Mitigating Attack Exposure provided by the Nginx team:
https://www.nginx.com/blog/http-2-rapid-reset-attack-impacting-f5-nginx-products/

Could we add them into the default configuration, specifically:

- keepalive_requests should be kept at the default setting of 1000 requests
- http2_max_concurrent_streams should be kept at the default setting of 128 streams
- limit_conn enforces a limit on the number of connections allowed from a single client. This directive should be added with a reasonable setting balancing application performance and security.
- limit_req enforces a limit on the number of requests that will be processed within a given amount of time from a single client. This directive should be added with a reasonable setting balancing application performance and security.

Thanks

**Comment by danil-smirnov** [comment]
Nginx 1.25.3 has been released

**Comment by buchdag** [comment]
nginx has been updated to 1.25.3 in the image.
