### ISSUE TITLE
Unable to download python requirements for testing

### ISSUE THREAD

**Issue by dannycarrera** [nginx-proxy/nginx-proxy#2318]
When I run the command `pip install -r requirements/python-requirements.txt` the following error gets thrown:

```
     
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
     
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
     
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
```

Is this an issue with the repo or with my environment? I was looking to get #1369 tested and merged.

**Comment by buchdag** [comment]
Hi @dannycarrera, sorry for the very late reply. Since our CI tests are working properly and the mentioned `license_file` parameter can't be found anywhere in the repo except in this issue, I'd say it was an issue with your environment.

Feel free to re open if you think it isn't.
