### ISSUE TITLE
host header does not include port number

### ISSUE THREAD

**Issue by sinbino** [nginx-proxy/nginx-proxy#2386]
If the outgoing port of nginx-proxy is other than 80/443, prior to 1.3.1, the host header passed to the container included the port number.
Example: host: example.com:8080

However, since 1.4.0, the host header no longer includes the port number.
Example: host: example.com

This has caused applications that rely on the host header to stop working all together.
Am I missing something?

**Comment by buchdag** [comment]
Hi.

We where previously using the value of the variable `$http_host` for the Host header sent to the proxy, which did include port number for non default ports. [We had to switch to `$host` when adding HTTP/3 as `$http_host` is empty when using HTTP/3](https://github.com/nginx-proxy/nginx-proxy/discussions/2271#discussioncomment-6448072).

I tried to fix this yesterday with the following :

```diff
diff --git a/nginx.tmpl b/nginx.tmpl
index 08606b9..a0501dd 100644
--- a/nginx.tmpl
+++ b/nginx.tmpl
@@ -341,6 +341,12 @@ map $http_x_forwarded_port $proxy_x_forwarded_port {
     '' $server_port;
 }
 
+map $server_port $host_port {
+    default :$server_port;
+    80 '';
+    443 '';
+}
+
 # If the request from the downstream client has an "Upgrade:" header (set to any
 # non-empty value), pass "Connection: upgrade" to the upstream (backend) server.
 # Otherwise, the value for the "Connection" header depends on whether the user
@@ -402,7 +408,7 @@ include /etc/nginx/proxy.conf;
 {{- else }}
 # HTTP 1.1 support
 proxy_http_version 1.1;
-proxy_set_header Host $host;
+proxy_set_header Host $host$host_port;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection $proxy_connection;
 proxy_set_header X-Real-IP $remote_addr;
```

I've built and pushed `nginxproxy/nginx-proxy:2386` and `nginxproxy/nginx-proxy:2386-alpine` with this modification, could you try either of those @sinbino ?

**Comment by sinbino** [comment]
Thank you for your reply.

I tried nginxproxy/nginx-proxy:2386-alpine.
This version includes the port in the Host header of the request that the container receives.
It looks fine.
