### ISSUE TITLE
Trim hostnames of whitespace

### ISSUE THREAD

**Issue by mariusGundersen** [nginx-proxy/nginx-proxy#250]
I reported this in docker-gen (https://github.com/jwilder/docker-gen/issues/121), but it should probably be fixed here too, since there is a different template file here.

**Comment by md5** [comment]
Looks like the `strings.TrimSpace` function would need to be exposed through `docker-gen` to be able to do this. Currently, the only trim-related functions exposed are `strings.TrimPrefix` and `strings.TrimSuffix`.

**Comment by mariusGundersen** [comment]
Or just the plain `strings.Trim` function. I have never coded in Go before, but this seems like a simple thing to implement for a first-timer, so I can try to do it.

**Comment by mariusGundersen** [comment]
Ok, I've made a pull request to docker-gen: https://github.com/jwilder/docker-gen/pull/123

**Comment by buchdag** [comment]
fixed in #262
