### ISSUE TITLE
修改了默认端口，但是配置里面没有变

### ISSUE THREAD

**Issue by xiaomazz** [nginx-proxy/nginx-proxy#2500]
![image](https://github.com/user-attachments/assets/120286cb-9b69-4821-9c63-d9ba7e7b92af)
![image](https://github.com/user-attachments/assets/763af099-d0c7-4384-b269-49766319a224)
何解？

**Comment by buchdag** [comment]
Hi. English language only, please.

**Comment by xiaomazz** [comment]
The default port was modified, but the configuration did not change

**Comment by chusri** [comment]
@xiaomazz, the ports you configured in the docker-compose aren't related to the nginx port shown in the container configuration.

**Comment by buchdag** [comment]
@xiaomazz check the doc for [custom external HTTP / HTTPS ports](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#custom-external-httphttps-ports)

To change the ports nginx-proxy is listening on, you need to use two environment variable, `HTTP_PORT` and `HTTPS_PORT`.

**Comment by buchdag** [comment]
No answer from issue creator, closing.
