### ISSUE TITLE
Using Alpine as a base?

### ISSUE THREAD

**Issue by joshmanders** [nginx-proxy/nginx-proxy#292]
Before I attempt to port this to a smaller image using Alpine, is it possible, and have you guys thought about it?

I have an alpine image that has nginx installed and it's 6MB, so I don't think that forego and docker-gen make it 185MB.

**Comment by jwilder** [comment]
The image just extends the official nginx image to keep things simple.  It would be nice if they could use a smaller base image as well.

**Comment by killswitch** [comment]
@jwilder I'm going to attempt to get it working with Alpine, should be pretty straight forward, if it does, I'll submit a PR.

**Comment by cadesalaberry** [comment]
Any progress ?

**Comment by joshmanders** [comment]
I have not gotten time to do it unfortunately.

**Comment by matt-hh** [comment]
Hi, please check PR #558

**Comment by cadesalaberry** [comment]
Thanks @matt-hh !! Found it right after, exactly what I was looking for.

I think this issue can be either closed or marked as duplicate.

**Comment by buchdag** [comment]
Done in #558
