### ISSUE TITLE
Option to disable "SSL preference"

### ISSUE THREAD

**Issue by bluepuma77** [nginx-proxy/nginx-proxy#295]
For some tests I needed to reach a subdirectory via SSL. Now suddenly every access is redirected to SSL, which really breaks some things.

I found in the documentation "If a container has a usable cert, port 80 will redirect to 443 for that container so that HTTPS is always preferred when available".

In general it's a good idea to prefer the secure connection, but in some cases it's not. So it would be great to have an option to disable the preference and just stick with the original connection type.

**Comment by kamermans** [comment]
I second this request.  In my use case, I have several subdomains that are served, all of which are covered by a wildcard SSL cert, but only some of them should be served via SSL by default.  It would be nice to turn the auto-SSL redirect on or off via an environment variable.

**Comment by tkw1536** [comment]
Resolved by solved by [HTTPS_METHOD=noredirect](https://github.com/nginx-proxy/nginx-proxy#how-ssl-support-works), closing.
