### ISSUE TITLE
same ssl bind on 443 port with ldap image

### ISSUE THREAD

**Issue by reyman** [nginx-proxy/nginx-proxy#296]
Hi, this is a great project. 
i'm trying to use an openldap image + ldap webadmin image which also expose the 443 port to use a self certificates for Tls authentification. Is there a way to resolve this double bind on same port with nginxproxy and ssl configuration ?

**Comment by reyman** [comment]
You can see the docker image here: osixia/phpldapadmin

**Comment by md5** [comment]
If I understand your question correctly, it sounds like you could run the LDAP web admin image behind `jwilder/nginx-proxy` by removing the `-p 443:443` from that container and giving it a `-e VIRTUAL_HOST` and configuring SSL as detailed in the `README.md` for this image.

**Comment by reyman** [comment]
The question is, what happen with the TLS self signed certificate when nginx-proxy search the certificate in the folder i define ? I try this later, but i suppose the certificate is not found because it's located into the [osixia ldap image](https://github.com/osixia/docker-openldap) ?

**Comment by md5** [comment]
@reyman The SSL certificate generated inside the `osixia/openldap` image is used for LDAPS. I don't see any reason it needs to be the same certificate used for the HTTPS-based admin app.

Since the certificate is self-signed, however, you will need to make sure that the PHP admin app trusts that certificate somehow if it's going to talk to the OpenLDAP container over LDAPS.

**Comment by reyman** [comment]
Ok i understand, but I have this 403 error, dont understand why.

**Comment by md5** [comment]
A 403 error is going to be from your backend container, not from `nginx-proxy` itself.

**Comment by buyenne** [comment]
Had similar problems but I finalls fixed it with this command:

docker run --name phpLDAPadmin -e VIRTUAL_HOST=phpldapadmin.yourdomain.com -e VIRTUAL_PORT=443 -e VIRTUAL_PROTO=https -e PHPLDAPADMIN_LDAP_HOSTS=localhost -d osixia/phpldapadmin

**Comment by tkw1536** [comment]
Seems resolved, closing
