### ISSUE TITLE
Doesn't seem to work with new docker networking

### ISSUE THREAD

**Issue by xoredg** [nginx-proxy/nginx-proxy#305]
It doesn't seem to work with the new docker networking features. i.e. `--x-networking` for example on docker compose. I'm not really sure if it should to begin with, but it would be handy.
I'm running a SPA, API and DB under a new networked setup and nginx-proxy gives a 503 even when the LB has the `VIRTUAL_HOST` env var. Are you aware of this?

**Comment by thaJeztah** [comment]
possible duplicate of https://github.com/jwilder/nginx-proxy/issues/304?

**Comment by blackxored** [comment]
It might be. The only difference is that I'm talking local networking, but yes the lacking support for the new networking API definitely seems like the culprit.

**Comment by modius** [comment]
:+1: 

Trying to move from links to networking and this definitely appears to be an issue.

> While links are still supported in this limited capacity, you should avoid them in preference of Docker networks. The link feature is expected to be deprecated and removed in a future release.

https://docs.docker.com/engine/userguide/networking/dockernetworks/

**Comment by modius** [comment]
@schmunk42 did this commit make it into the Docker image? 

https://github.com/jwilder/docker-gen/commit/fdf292247a233d4775e258979b3fa5e6b1c187b9

**Comment by md5** [comment]
@modius No. But see https://github.com/jwilder/docker-gen/pull/144

**Comment by tkw1536** [comment]
Related issue is closed, closing.
