### ISSUE TITLE
Remove containers created from tests

### ISSUE THREAD

**Issue by dmp1ce** [nginx-proxy/nginx-proxy#316]
Running `make test` local leaves a lot of containers around. Some of them still running. Using `--rm` gets rid of many of them, but causes circleci to break. CircleCI can be made to work by checking for specific lines in output to avoid btrfs errors. The remaining containers can be removed with a manual `make test-clean`.

I've created a patch to address this issue. I have already used up my one fork of nginx-proxy so I'm linking to a commit. https://github.com/dmp1ce/nginx-proxy-circleci/compare/f4c0239918c4...7bc65330547b8c2292a44b5420258cc3e756b129

I have verified that circleci still works too. https://circleci.com/gh/dmp1ce/nginx-proxy-circleci

Ideally, all containers created by a test would be cleaned up in a teardown function in BATS. My patch doesn't do that.

**Comment by md5** [comment]
@dmp1ce Is the `-l 0` part what makes it ignore the `btrfs` errors on CircleCI? If so, it seems like that should be noted as comments in the test file, since it's otherwise unclear why the `-l 0` flags are there.

**Comment by dmp1ce** [comment]
That's right. It is too bad that there needs to be special code for circleci but I don't think it makes a difference in this case as the output should only be one line. I'll go ahead and add the comments.

**Comment by thomasleveil** [comment]
maybe it's time to give a try to TravisCI (See #312)

**Comment by schmunk42** [comment]
We're very happy with Gitlab CI btw. but I don't know if they offer a free service.

**Comment by buchdag** [comment]
No longer relevant.
