### ISSUE TITLE
Is it possible to proxy a path from a virtual host to a different container than all other paths?

### ISSUE THREAD

**Issue by stevenroose** [nginx-proxy/nginx-proxy#338]
I think the title speaks for itself.

I have a container serving example.com:80 and :443 while another container should serve example.com/websocket. Is this possible?

**Comment by md5** [comment]
See #254. In short, it's not currently possible, but there has been some work to support this feature that has been stalled for a while due to my like of time.

**Comment by buchdag** [comment]
This features has been added to the `dev` branch with #1607 

It's available now on the `dev` images `nginxproxy/nginx-proxy:dev` and `nginxproxy/nginx-proxy:dev-alpine`. Testing and feedback are welcome, the docs for the feature is [here](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing) and there is [another PR](https://github.com/nginx-proxy/nginx-proxy/pull/1699) opened for additional improvements and comments.
