### ISSUE TITLE
Reload network définitions on docker service restart

### ISSUE THREAD

**Issue by smalot** [nginx-proxy/nginx-proxy#348]
When I restart docker daemon some of my containers change their IP (with restart=always).

``` sh
service docker restart
```

However nginx-proxy is not aware of this change. So backends stills use the old IP address.

The only fix a found is to restart the nginx-proxy container:

``` sh
docker restart nginx_nginx_1
```

Any fix or workaround will be greatly appreciated.

Many thanks

**Comment by jwilder** [comment]
I think https://github.com/jwilder/docker-gen/pull/156 will need to get pulled into this image to fix this.

One workaround would be to send a `SIGHUP` signal tor your `nginx-proxy` container.  That should trigger a the template to regenerate and reload nginx.

**Comment by bradjones1** [comment]
> One workaround would be to send a SIGHUP signal tor your nginx-proxy container. That should trigger a the template to regenerate and reload nginx.

That's indeed what the letsencrypt "companion" container does... might be worth running, since it gives you free TLS, too. See https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/functions.lib#L71

**Comment by tseho** [comment]
@bradjones1 I don't think adding another container with letsencrypt should be the solution of this issue ...
Last time I checked, I didn't have the problem anymore. Is the issue still active ?

**Comment by buchdag** [comment]
Shouldn't be relevant anymore, closing.
