### ISSUE TITLE
consistent tags for docker images

### ISSUE THREAD

**Issue by sopitz** [nginx-proxy/nginx-proxy#355]
I know this has been spoken about in #162 (create tags for releases) but I want to readress the issue:
we created an image that is based on your awesome nginx-proxy that allows us to have ssl-certs generated from letsencrypt on the fly just as the conf-file.
Now it would be awesome to have a tagged image to use that keeps the same so we know our stuff won't break when we rebuild our image.

Even though it would create some more efforts to stay up-to-date with your development, we could ensure that our image won't break. @jwilder is there a chance that we get stable images?

I saw that you updated 0.1.0, 0.2.0 and latest 5 days ago, but it would be great to have those in a new tag so we can test appropriately.

**Comment by sopitz** [comment]
If you want to have a look, we published it on our github: https://hub.docker.com/r/eforce21/letsencrypt-nginx-proxy/

Maybe that helps to understand the problem a little more.

**Comment by jwilder** [comment]
I don't push images manually.  It's using automated builds with docker hub.  The latest stable release is the newest tag and I create new tags periodically, but not for every commit.  If you are building off master it will always be considered unstable.

**Comment by sopitz** [comment]
That makes sense.
But did you force-push lately? Because that's what we get form the docker hub info page:
![jwilder](https://cloud.githubusercontent.com/assets/1926344/12720809/c7ab324e-c8fc-11e5-8b4d-43143fb272f8.jpg)

So it seems like there was still some activity on the tags.
Using latest is always unstable - I agree on that!

**Comment by jwilder** [comment]
That might be due to the linked repos.  It will rebuild when the nginx repo is updated as well.

**Comment by sopitz** [comment]
Aaaah ok... I see. But why did you link that repo as you're actually using a fixed version number?
`FROM nginx:1.9.6`

It's very confusing to me to see that a stable release/image is being rebuilt due to changes on some other repo that should not affect that stable base image you're using.

**Comment by jwilder** [comment]
It was suggested on some issue so that security patches, etc.. get handled automatically.  I can't link a specific tag to a specific dependent repo's tag.  I can only specify `nginx-proxy` is linked to `nginx`. 

I don't have a strong opinion about keeping the repository links.

**Comment by sopitz** [comment]
So here's how I see it:
nginx tags 1.9.1, nginx-proxy uses this as a base image. Now they find some security issue in nginx, patch it up and release tag 1.9.2. Now you need to keep track of those things to update nginx-proxy manually, because you want to test that your image still works and their change doesn't break anything. So technically there shouldn't be any dependency between nginx and nginx-proxy. Just as there's none between nginx-proxy and letsencrypt-nginx-proxy. If you release a new tag, I will take a look, test and release a new version of my reverse-proxy.

Do I miss something along the way?

**Comment by tkw1536** [comment]
This is done by a GitHub workflow for every tag now, closing.
