### ISSUE TITLE
port mapping not working?

### ISSUE THREAD

**Issue by opichon** [nginx-proxy/nginx-proxy#362]
I have a bunch of docker containers, which obviously must each expose different ports.
I want to use the proxy so that each container is accessible via a different url, but all with port 80. That is the whole point, isn't it.

This used to work, but not anymore. 

Now each container works only on its original port.

For example, if I have defined a container with nginx on port 8001, and I map it to my.hostname.org, then I can only open it in a browser with this url: http://my.hostname.org:8001

http://my.hostname.org gives me a nginx "service unavailable error" message.

**Comment by wader** [comment]
Can you provide more information? how are the containers configured and started? using the new docker networking? how does the generated nginx config look?

**Comment by opichon** [comment]
The problem, as far as I can see, comes from using version 2.0 docker-compose files. The same file, written in version 1, works. When written in version 2.0, it doesn't. Theonly difference is that in version 2, the file starts with:

version: "2"
services:
 etc.

Using version 2, the proxy container's /et/nginx/confd.default.conf file shows entries without a host ip address, like this:
upstream www.frimus.org {
			# october_nginx_1
			server :80;
}


When using version 1, the entry shows an ip address:

upstream www.frimus.org {
			# october_nginx_1
			server 172.17.0.9:80;
}

**Comment by opichon** [comment]
Here are the versions of docker and docker-compose I use:
Docker version 1.10.1, build 9e83765
docker-compose version 1.6.0, build unknown

**Comment by wader** [comment]
Version 2 will use the new networks feature that nginx-proxy does not support yet. There are some efforts going on to support it #305 #337

**Comment by tkw1536** [comment]
Resolved by https://github.com/nginx-proxy/nginx-proxy/pull/337.
