### ISSUE TITLE
How to revise nginx.tmpl to redirect Homepage Url of example.com to www.example.com?

### ISSUE THREAD

**Issue by hyp530** [nginx-proxy/nginx-proxy#389]
Sorry for stupid previous question. Actually, I want to redirect my hompage example.com to www.example.com, but quite confused with the grammar with {{ }}  . Could you guide me how to revise nginx.tmpl to realize this redirection? Thank you so much.

**Comment by helderco** [comment]
Nginx doesn't support .htaccess files.

**Comment by hyp530** [comment]
Question updated.

**Comment by helderco** [comment]
If you look at `/etc/nginx/nginx.conf`, there's this line:

```
http {
  ...
  include /etc/nginx/conf.d/*.conf;
}
```

So you can add any file ending in `.conf` to that directory and it will be loaded. This is how I've done it, no need to edit `nginx.tmpl`. 

```
# /etc/nginx/conf.d/example.conf
server {
  server_name example.com;
  return 301 http://www.example.com$request_uri;
}
```

**Comment by hyp530** [comment]
I found /etc/nginx/conf.d/default.conf in the nginx-proxy container, which seems to be created automatically. It contains the following:
server {
        server_name example.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://www.$host$request_uri;   # www. is added by me.
}

I tried to amend the above code to redirect all non-www Urls to www Urls. But it seems that nginx should be restarted to work. However, every time I restart nginx, it seems to recreate a new default.conf that override the amended one.

**Comment by helderco** [comment]
@hyp530 Don't amend the default.conf file. You'll lose your changes. Do you have a problem with my advice above?

**Comment by helderco** [comment]
By the way, if www.example.com is your target domain, and not example.com, then you should have `VIRTUAL_HOST=www.example.com` (i.e., with www).

Then set up your redirections as I said above.

**Comment by tkw1536** [comment]
This is resolved by the comments above. 
please open a Discussion if the issue persists.
