### ISSUE TITLE
Multiple Vhosts

### ISSUE THREAD

**Issue by SergiuCip** [nginx-proxy/nginx-proxy#394]
Hi there, 

Great application! So, I have myexample.com which is the main domain / container (web app) and also I've got a GIT container which I would like to connect it to the main domain as: myexample.com/git is it possible or I have to have it as myexample.com and git.myexample.com? 

As I would like to not be using cnames when I am doing so.

Thanks

**Comment by pitkley** [comment]
This exact request is covered with PR #254, although that is stale right now, mainly because of time constraints.

**Comment by tkw1536** [comment]
Fixed by #1607.
