### ISSUE TITLE
Read per VIRTUAL_HOST conf files from inside running containers?

### ISSUE THREAD

**Issue by Gymnae** [nginx-proxy/nginx-proxy#427]
Hello,
I really like this image so far. And it's been pretty easy to setup, also in conjunction with the great let's encrypt [companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) 

Now, I've got a couple of webapps which demand nginx conf tuning: owncloud and koken.
For both I created images with pre-tuned config files, which are copied into these containers on runtime.

Does the local nginx inside such a container still read those custom conf files, or is only relevant what is added to /etc/nginx/conf.d/default of the nginx-proxy container? I hope this is a clear enough question.

If the latter, can I tell nginx-proxy to read the conf files inside a container it's proxying too? This could make it easier to try out new images and do the housekeeping: One source of truth for the vhost conf file of an webapp. 

Cheers

**Comment by shanoor** [comment]
nginx-proxy is a middleman, in the end, your web server works as usual and any config you have inside a proxified container is loaded as usual. Keep in mind that you can have any type of web server in the proxified container (nginx, apache, nodejs, python...) so nginx-proxy can't nullify their config just like that.
