### ISSUE TITLE
Improve Documentation for "env var to disable SSL redirect".

### ISSUE THREAD

**Issue by tobiashochguertel** [nginx-proxy/nginx-proxy#446]
I'm missing where to set this new environment variables.. It would be create to add this information to the `readme.md` file. It was for me not clear that this env-variable has to be defined in web-application container (exposes port 80 or port 443, or both).

**Comment by kamermans** [comment]
I've improved the docs on PR #462 - can you take a look and suggest improved wording if it is still not clear?
