### ISSUE TITLE
Don't enable 'Strict-Transport-Security' header when HTTPS_METHOD=noredirect

### ISSUE THREAD

**Issue by palamccc** [nginx-proxy/nginx-proxy#453]
When HTTPS_METHOD=noredirect is enabled, objective is to serve both 'http' and 'https' without  any conflict/redirect.

So in this case, if we enable 'Strict-Transport-Security' header, browser won't load http, after visiting https page. So  'Strict-Transport-Security' header should be disabled when HTTPS_METHOD=noredirect is used.

`add_header Strict-Transport-Security "max-age=31536000";`

related to PR #298 @kamermans

**Comment by kamermans** [comment]
Good point, I agree.  My main purpose was for machine-to-machine traffic, so it did not occur to me that HSTS should be disabled.  @jwilder what do you think?  @palamccc makes a good point that there's really no point in explicitly saying you don't want to auto-redirect to HTTPS just to have HSTS force your browser to auto-redirect to HTTPS :)

**Comment by kamermans** [comment]
@jwilder - this PR can be closed - I implemented the fix last year and now users can also use `HSTS=off`.
