### ISSUE TITLE
HTTP/2 in conjunction with SSL/TLS does not work properly

### ISSUE THREAD

**Issue by Giymo11** [nginx-proxy/nginx-proxy#458]
Thank you for your hard work!
I just installed your container, along with [letsencrypt-nginx-proxy-container](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion), and I was checking via Chrome if the proxy would serve HTTP/2. Interestingly, I found out that via Firefox it would, via Chrome it would not. I found the reason [here](https://serverfault.com/questions/732474/nginx-configured-with-http2-doesnt-deliver-http-2); basically the version of OpenSSL (I checked, it is `OpenSSL 1.0.1k 8 Jan 2015`) is too old to support the required Protocol. 
Is there any way you could update this, or even use something like [this](https://github.com/Ehekatl/docker-nginx-http2)?
Let me know if I can help you in any way!

**Comment by thaJeztah** [comment]
Basically, this is an issue in the official nginx image; see this discussion https://github.com/nginxinc/docker-nginx/issues/76. The alpine version of that image has a more recent version of OpenSSL.

IIRC, forego didnt run on alpine (https://github.com/ddollar/forego/issues/65), but now that a forked version is used (https://github.com/jwilder/nginx-proxy/pull/406), perhaps this becomes an option?

**Comment by Giymo11** [comment]
Thanks for pointing out that the alpine version has the newer version of OpenSSL!
A good workaround for my usecase was to simply run docker-gen in its own container, and using nginx:alpine instead of nginx.

**Comment by sandrodz** [comment]
it works for me on Mac on all browsers

**Comment by tkw1536** [comment]
As per last comment this seems to be working now. If the issue persists, please reopen.
