### ISSUE TITLE
Doesn't seem any network

### ISSUE THREAD

**Issue by zhangriyueming** [nginx-proxy/nginx-proxy#468]
Used it on Digital Ocean, Ubuntu 14.04.4 LTS, Docker version 1.6.2, build 7c8fca2

It didn't work. Then I checked /etc/nginx/conf.d/default.conf, there wasn't any thing in upstream context, looks like this:

`
upstream xxx.cn{
}
`

Then I cloned this project to the machine, and insert some commented codes into the loops of file nginx.tmpl
`
{{ define "upstream" }}
    {{ if .Address }}
        # if .Address
        {{/* If we got the containers from swarm and this container's port is published to host, use host IP:PORT */}}
        {{ if and .Container.Node.ID .Address.HostPort }}
            # {{ .Container.Node.Name }}/{{ .Container.Name }}
            server {{ .Container.Node.Address.IP }}:{{ .Address.HostPort }};
        {{/* If there is no swarm node or the port is not published on host, use container's IP:PORT */}}
        {{ else if .Network }}
            # {{ .Container.Name }}
            server {{ .Network.IP }}:{{ .Address.Port }};
        {{ end }}
    {{ else if .Network }}
        # {{ .Container.Name }}
        server {{ .Network.IP }} down;
    {{ else }}
        # Else
    {{ end }}
{{ end }}
`

`
upstream {{ $host }} {
{{ range $container := $containers }}
    {{ $addrLen := len $container.Addresses }}

```
# for CurrentContainer.Networks
{{ range $knownNetwork := $CurrentContainer.Networks }}
    # knownNetwork: {{ $knownNetwork.Name }}
    {{ range $containerNetwork := $container.Networks }}
        # containerNetwork: {{ $containerNetwork.Name }}
        {{ if eq $knownNetwork.Name $containerNetwork.Name }}
            ## Can be connect with "{{ $containerNetwork.Name }}" network

            {{/* If only 1 port exposed, use that */}}
            {{ if eq $addrLen 1 }}
                {{ $address := index $container.Addresses 0 }}
                {{ template "upstream" (dict "Container" $container "Address" $address "Network" $containerNetwork) }}
            {{/* If more than one port exposed, use the one matching VIRTUAL_PORT env var, falling back to standard web port 80 */}}
            {{ else }}
                {{ $port := coalesce $container.Env.VIRTUAL_PORT "80" }}
                {{ $address := where $container.Addresses "Port" $port | first }}
                {{ template "upstream" (dict "Container" $container "Address" $address "Network" $containerNetwork) }}
            {{ end }}
        {{ end }}
    {{ end }}
{{ end }}
```

{{ end }}
}
`

Then I checked the new default.conf, it was

`
upstream xxx.cn {
    # for CurrentContainer.Networks
}
`

**Comment by wader** [comment]
Can you give more information about your setup? using separate containers for nginx/docker-gen? docker running with inter container communication disabled?

**Comment by falcon15500** [comment]
Same.  The current nginx template file doesn't seem to output ANY text in between the curly braces after the word "upstream".  The result is just

upstream <hostname> {
}

Shouldn't there be a "server" directive between the braces?

For info, I am running split containers.  All containers on the same user-defined network.

**Comment by wader** [comment]
Can both of you check if it is the `-only-exposed` issue? see #438

**Comment by zhangriyueming** [comment]
To my situation, it maybe a problem with old docker version. There is even no `docker network` command in 1.6.2. I have fixed this by adding apt-source from official website of docker and then upgraded my docker to 1.11. Everything works fine then.

**Comment by falcon15500** [comment]
Sorry - yes, it's the `-only-exposed` issue.  When I expose an arbitrary port on the docker-gen container, the resulting nginx default.conf is fine.

**Comment by wader** [comment]
@zhangriyueming Close issue?
