### ISSUE TITLE
Virtual host with location

### ISSUE THREAD

**Issue by jrabary** [nginx-proxy/nginx-proxy#469]
Is it possible to create a configuration that serve different application under the same virtual host but with different path. Preciselly I'like to have : 

vhost.domain/app1 -> docker in localhost:5000
vhost.domain/app2 -> docker in localhost:6000

**Comment by wader** [comment]
Nope not at the moment. See #254

**Comment by buchdag** [comment]
This features has been added to the `dev` branch with #1607 

It's available now on the `dev` images `nginxproxy/nginx-proxy:dev` and `nginxproxy/nginx-proxy:dev-alpine`. Testing and feedback are welcome, the docs for the feature is [here](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing) and there is [another PR](https://github.com/nginx-proxy/nginx-proxy/pull/1699) opened for additional improvements and comments.
