### ISSUE TITLE
Using multiple path

### ISSUE THREAD

**Issue by munjalpatel** [nginx-proxy/nginx-proxy#47]
Hello,

I have modified your nginx template a bit so that I can use different docker containers for different paths of the same domain.

For example: 
    www.mysite.com with /        ---> web-main container
    www.mysite.com with /auth ---> web-auth container

But I am not sue how I can control order in which these values are registered in sites-emabled nginx config file.

Currently, config block for "/" gets defined before "/auth" block and so all of my requests ends up going to the "web-main" docker container.

Basically, it would need to sort the collection of the "path" in descending order before looping over it to generate the config file.

I would appreciate if anyone can point me into the right direction here.

Here is the modified nginx template:

```
server {
    listen 80 default_server;
    server_name _; # This is just an invalid value which will never trigger on a real hostname.
    error_log /proc/self/fd/2;
    access_log /proc/self/fd/1;
    return 503;
}

{{ range $host, $containers := groupByMulti $ "Env.VIRTUAL_HOST" "," }}
{{ range $path, $containers := groupByMulti $ "Env.VIRTUAL_PATH" "," }}
{{ range $index, $value := $containers }}

upstream {{ $value.Name }} {
    {{ $addrLen := len $value.Addresses }}
    {{/* If only 1 port exposed, use that */}}
    {{ if eq $addrLen 1 }}
        {{ with $address := index $value.Addresses 0 }}
           server {{ $address.IP }}:{{ $address.Port }};
        {{ end }}

    {{/* If more than one port exposed, use the one matching VIRTUAL_PORT env var */}}
    {{ else if $value.Env.VIRTUAL_PORT }}
        {{ range $i, $address := $value.Addresses }}
           {{ if eq $address.Port $value.Env.VIRTUAL_PORT }}
           server {{ $address.IP }}:{{ $address.Port }};
           {{ end }}
        {{ end }}

    {{/* Else default to standard web port 80 */}}
    {{ else }}
        {{ range $i, $address := $value.Addresses }}
            {{ if eq $address.Port "80" }}
            server {{ $address.IP }}:{{ $address.Port }};
            {{ end }}
        {{ end }}
    {{ end }}
}

server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;

    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    server_name {{ $host }};
    proxy_buffering off;
    error_log /proc/self/fd/2;
    access_log /proc/self/fd/1;

    location {{ $path }} {
        proxy_pass http://{{ $value.Name }};
        include /etc/nginx/proxy_params;

        # HTTP 1.1 support
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}

{{ end }}
{{ end }}
{{ end }}
```

**Comment by aseempatni** [comment]
Any updates on this? I think it's a great feature.

**Comment by guysoft** [comment]
Any workaround? Perhaps with a custom template for a specific container?

**Comment by KrzysztofMadejski** [comment]
PR in #254

**Comment by buchdag** [comment]
This features has been added to the `dev` branch with #1607 

It's available now on the `dev` images `nginxproxy/nginx-proxy:dev` and `nginxproxy/nginx-proxy:dev-alpine`. Testing and feedback are welcome, the docs for the feature is [here](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing) and there is [another PR](https://github.com/nginx-proxy/nginx-proxy/pull/1699) opened for additional improvements and comments.
