### ISSUE TITLE
Support SSLCACertificateFile

### ISSUE THREAD

**Issue by iBobik** [nginx-proxy/nginx-proxy#488]
Qualys SSL test capped grade to B because "Chain issues:    Incomplete"

It can be solved by adding CA chain file and SSLCACertificateFile in Nginx conf. Could you support autoload file named like: example.com.chain.crt?

**Comment by wader** [comment]
I have `Chain issues: None` using let's encrypt certificate with [simp_le](https://github.com/kuba/simp_le) but then i think it automatically bundles the chain. Is that possible in your case? but yeah maybe it would be nice if nginx-proxy looked for *.chain.crt etc.

**Comment by iBobik** [comment]
Yes, if I concat crt and intermediate certificate, it will work.

```
cat ca-intermediate.crt >> example.com.crt
```

**Comment by tkw1536** [comment]
Seems resolved, closing
