### ISSUE TITLE
Upgrade base-image to 1.10

### ISSUE THREAD

**Issue by crunchtime-ali** [nginx-proxy/nginx-proxy#500]
Why isn't a more recent image used as the base image?
1.10.1 contains a small security-fix. 

Also why don't you use the baseline (currently 1.11) image?

**Comment by BenHall** [comment]
FYI: This requires also updating Forego and Docker gen. I've done it in my branch https://github.com/BenHall/nginx-proxy/blob/sticky/Dockerfile

**Comment by dj-hedgehog** [comment]
Thank you but why don't you make a PR for it?

**Comment by tkw1536** [comment]
The update has been done by now, closing.
