### ISSUE TITLE
Can I add additional nginx settings?

### ISSUE THREAD

**Issue by afridlund85** [nginx-proxy/nginx-proxy#505]
I use one of the containers behind the reverse proxy for gitlab ce and would like to change the nginx setting: "client_max_body_size" from its default "1M" to allow larger commits. Since the nginx default.conf is managed by the reverse proxy, any changes I apply to the file manually can change if the container is rebuilt.

To change it I used docker exec to access the container, install a nano, open the file and add the line manually.

Is there any way to change nginx settings outside the container, using docker or additional configs?

**Comment by wader** [comment]
Search for "client_max_body_size" in README.md and you will see some examples about custom config

**Comment by afridlund85** [comment]
It was right there, now I feel stupid. Thanks alot

**Comment by wader** [comment]
Hi, close?

**Comment by tkw1536** [comment]
Closing issue. Please open a discussion of the problem still persists.
