### ISSUE TITLE
foo.com redirects to foo.com:8080

### ISSUE THREAD

**Issue by vertangelx** [nginx-proxy/nginx-proxy#521]
Hello,

I'm experiencing a strange problem were pointing my browser to `http://foo.com` redirects it to `http://foo.com:8080` and the site (Wordpress) loads fine.

Why can't it not redirect to port 8080? I want the browser to remain on `http://foo.com` if that is the address that I entered!

Here's how I start the containers
1. `docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock --name nginx-proxy jwilder/nginx-proxy`

```
    docker run -d \
    --link mysql:mysql \
    -p 8080:80 \
    -e ... \
    -v ... \
    -e VIRTUAL_HOST=www.foo.com,foo.com \
    --name foo-wordpress \
    wordpress:latest
```

Any ideas? Thanks!

**Comment by wader** [comment]
Try remove -p 8080:80, you dont need to publish any ports for nginx-proxy to work. Only needs expose hint and in your case it looks like wordpress image default exposes 80. But i dont know why it redirects, have you configured 8080 somewhere else?

**Comment by tkw1536** [comment]
Seems resolved in last comment. Also no updates since 2016, closing.
