### ISSUE TITLE
Adding a configuration for non-dockerized service?

### ISSUE THREAD

**Issue by zarbis** [nginx-proxy/nginx-proxy#522]
There is possibility for adding Per-VIRTUAL_HOST custom configs, but i wonder if there is a possibility to create config for a non docker-related virtual host?

On my docker server i want to expose containers as subdomains of mydockerserver.com using nginx-proxy.
The problem is: on my docker server i have Zabbix server installed and for stability reasons i want to keep it close to metal. It's default web server is Apache and it is served as /zabbix.
My idea is to run Apache on different port, and do proxy-pass on nginx-proxy to serve Zabbix as zabbix.mydockerserver.com or mydockerserver.com/zabbix, whichever is simplier to implement.

So can i achieve this goal? Thanks in advance.

**Comment by wader** [comment]
You mean like https://github.com/jwilder/nginx-proxy#proxy-wide? have /etc/nginx/conf.d/ as volume and up custom config there

**Comment by flexbrane** [comment]
@zarbis how is your `/etc/nginx/conf.d/my_proxy.conf`?

What is the right setting in order to use a subdomain throught a non dockerized service?

Thank you very much :-)

**Comment by zarbis** [comment]
@flexbrane I have 2 separated configs in conf.d:
```
$ ls
default.conf  zabbix.conf
```
The `default.conf` is generated by nginx-proxy and points to my containers.
`zabbix.conf` (Zabbix installed on docker host directly) is just a copy-paste of single container's server block with slight tweak:
```
$ cat zabbix.conf 
server {
	server_name zabbix.boincfast.ru;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;

	location /zabbix {
		proxy_pass http://192.168.1.104:8080/zabbix;
	}
}
```
I've only changed proxy_pass address to point to internal physical IP address of docker host (`192.168.1.104` in my case).
Pointing it to `docker0` interface's IP address might also work, if you want more portability.

**Comment by flexbrane** [comment]
Ok, it's that simple ;-)

Thanks, that really help.

**Comment by tkw1536** [comment]
Resolved in last comment
