### ISSUE TITLE
Proxy for MySQL ports?

### ISSUE THREAD

**Issue by meteorjs3000** [nginx-proxy/nginx-proxy#523]
Is it possible to setup `nginx-proxy` to do for multiple MySQL installations on a single server that it can do for multiple web server installations on a single server?

Eg: `mydomain.com:3306` redirects to `mydomain.com:3306`, `anotherdomain.com:3306` redirects to `anotherdomain.com:3307`

**Comment by wader** [comment]
Have look at #318
