### ISSUE TITLE
nginx on host is a must?

### ISSUE THREAD

**Issue by dirad** [nginx-proxy/nginx-proxy#529]
I am trying to setup a server with official nginx + reverse-proxy + multiple hosts with ssl.

My host does not have nginx installed, and only the images/containers do. 
Right now all i get is a 503 from nginx, what do i do with the nginx.tmpl file if i have no /etc/nginx || /usr/share/nginx || any nginx directories ?

**Comment by wader** [comment]
You don't need nginx on the host, you only need docker. The nginx-proxy runs it's own nginx instance inside the container. nginx.tmpl is the default config template included in the image, you don't need to provide your own on the host.

the nginx-proxy container proxies requests to other containers over the docker network.

**Comment by dirad** [comment]
thanks for the replay @wader 

In the README, where it states files like /etc/nginx/vhost.d for example, where is this referring to?  should i create the files on the host system, even without installing nginx?

**Comment by wader** [comment]
I think that refers to '/etc/nginx/vhost.d' in the nginx-proxy container. But you can create a volume on the host mapping some host directory to it.

**Comment by dirad** [comment]
Doesnt the container have its data purged everytime it comes up?

**Comment by wader** [comment]
Nope, unless the container start script does it somehow. Host volumes (`-v /host/path:/container/path`) are just bind mounts into the container, data volumes (`-v /container/path`) has at least the same life time as the container. docker-compose has some magic to move data volumes between container recreates.

**Comment by luckydonald** [comment]
data volumes always need to be deleted manually as far as I know
