### ISSUE TITLE
Documentation update: VIRTUAL_PROTO=https != VIRTUAL_PORT=443

### ISSUE THREAD

**Issue by danbo** [nginx-proxy/nginx-proxy#562]
Please update the documentation to state that if you select your virtual_proto to be https, the proxy doesn't automatically go to 443 but rather that it has to be specified explicitly.

**Comment by jwilder** [comment]
Would you mind submitting a PR to update it?

**Comment by kamermans** [comment]
How is it possible that this sat for 21 days, and both me and @r4j4h fixed it just seconds apart? :)

**Comment by italomaia** [comment]
I have VIRTUAL_PROTO set to https and VIRTUAL_PORT to 443, yet, default.conf still points proxies to port 80:

```
# bin.italomaia.com
upstream bin.italomaia.com {
}
server {
	server_name app.italomaia.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass https://app.italomaia.com;
	}
}
```

Is that really all there is to do?

**Comment by kamermans** [comment]
That's all that is needed, but please make sure you are setting these variables on your application's webserver container, not the nginx-proxy container.

**Comment by tkw1536** [comment]
Seems resolved, closing.
