### ISSUE TITLE
docker-compose syntax v1 only supported in 0.3.0, v2 only in 0.4.0

### ISSUE THREAD

**Issue by schmunk42** [nginx-proxy/nginx-proxy#565]
I just tried to run docker-compose v1 and v2 (with overlay network) stacks in parallel but without success.

I noticed that `upstreams` have correct IPs in 0.4.0, when using docker-compose v2 - docker-compose v1 (without networking) only works with 0.3.0 of this image.

Would be great if this image would support both.

Related https://github.com/jwilder/nginx-proxy/issues/502#issuecomment-246128426
#### Generated config 0.3.0

```
upstream ~doro\.drbin\.xx {
                        # dorodrbinde_web-blue_1
                        server :80;
                        # dorodrbinde_web_1
                        server :80;
}
server {
        server_name ~doro\.drbin\.xx;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://~doro\.drbin\.xx;
        }
}
upstream ~a-web-site.xx {
                        # sam-w36/wwwexamplede_appnginx_1
                        server 1.2.3.4:32806;
}
```
#### Generated config 0.4.0

```
upstream ~doro\.drbin\.xx {
                                ## Can be connect with "reverse_default" network
                        # dorodrbinde_web-blue_1
                        server 10.0.5.4:80;
                                ## Can be connect with "reverse_default" network
                        # dorodrbinde_web_1
                        server 10.0.5.3:80;
}
server {
        server_name ~doro\.drbin\.xx;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://~doro\.drbin\.xx;
        }
}
upstream ~a-web-site.xx {
}
server {
        server_name ~a-web-site.xx;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://~a-web-site.xx;
        }
}
```

CC: @handcode

**Comment by schmunk42** [comment]
Need to investigate further, but this looks related: https://github.com/jwilder/nginx-proxy/commit/658e20f661ebc0f119ac21407c817c02c0777629

**Comment by schmunk42** [comment]
So I dug a bit deeper by adding a comment line before the `if` [here](https://github.com/jwilder/nginx-proxy/blob/40d433ae802896312b44b141be2daa36b9ec59cd/nginx.tmpl#L86), just to see which networks are checked.

We're starting our reverse proxies with docker-compose v2 on a swarm. This usually creates a new **overlay network** by default.
In many other setups (eg. single local machine with Docker-for-Mac) this action creates a new **network with a bridge driver**.
This is also different from running it with docker-compose v1 syntax (or directly with docker) - which does not create a network (unless explicitly specified) at all - usually these containers are using the **predefined** bridge network. Just as a side note: There is a `network_mode: bridge` for v2, which seems to behave pretty similar. But running everything in `bridge` mode is only an alternative for single-host setups.

Regarding v2 syntax, using this is kinda state-of-the-art to me, but pretty error-prone with nginx-reverse-proxy at the moment.

If you start a container with `VIRTUAL_HOST` setting without connecting it to a network to which the reverse proxies are also connected, you'll end up with an invalid config, because `upstream` will be empty! This also applies for starting v1 stacks, when your proxy is running in a custom network.

**Comment by schmunk42** [comment]
Related https://github.com/jwilder/nginx-proxy/pull/569

**Comment by radmen** [comment]
I've found a different workaround for this issue:

1. add custom network

    ```
    docker network create service-proxy
    ```
1. connect it with running nginx-proxy

    ```
    docker network connect service-proxy nginx-proxy
    ```
1. add custom network to docker-compose:

    ```yml
    version: '2'
    services:
        www:
            image: nginx:latest
            networks:
                - default
                - service-proxy
    networks:
        service-proxy:
            external: true
    ```

Hints taken from http://staxmanade.com/2016/07/run-multiple-docker-environments--qa--beta--prod--from-the-same-docker-compose-file-/

**Comment by Glideh** [comment]
So for now, how can we get rid of this empty-stream issue ?
Do we have to specify a network in all our services ?

**Comment by schmunk42** [comment]
@Glideh You can either use public ports and bridge mode for **all** of your containers.

Or create a proxy network `reverse_default` like here: https://github.com/dmstr/docker-roj/blob/0.2.5-beta1/data/example/core/reverse/docker-compose.yml#L24-L30
I'd recommend specifying an `ipam` config, since we ran into problems with overlapping networks after a while.

And attach your web-facing/VITUAL_HOST containers to this network, like so (or like @radmen did):

```
services:
  web:
    ports:
      - 80
    networks:
      - proxy
      - default
[...]
networks:
  proxy:
    external:
      name: reverse_default
```

**Comment by Glideh** [comment]
Thank you @schmunk42, I excluded the dedicated public ports on bridge mode solution for all my containers so I tried to create this overlay network but it seems to need a k/v store that I don't have right now.
I just read docker >1.12 doesn't need it anymore with the integrated swarm mode.
But should we use the whole swarm concept just for serving several simple apps ?
And without swarm, do I need docker-machine to create the k/v store or is there a simpler way ?
Maybe dumb questions but I'm trying to understand and I'm a little confused throughout the docs.

**Comment by schmunk42** [comment]
I haven't really looked into swarm mode, honestly I do not exepect it to be production ready, from what I've saw from earlier *docker/swarm* versions.

You can take a look at some of our [docs here](https://github.com/dmstr/docker-roj#documentation); Feedback & PRs welcome.

**Comment by spheenik** [comment]
@schmunk42: 

> If you start a container with VIRTUAL_HOST setting without connecting it to a network to which the reverse proxies are also connected, you'll end up with an invalid config, because upstream will be empty!

This helped me find the problem. Thanks, mate!

**Comment by nooone** [comment]
Using `network_mode: bridge` for all containers does *not* work. See [my question on stackoverflow](https://stackoverflow.com/questions/43769816/docker-nginx-proxy-works-with-docker-compose-v1-but-not-v2).

Not network is created with this setting and they should be all on the default bridge network, but the proxy is not working...

**Comment by buchdag** [comment]
Eight year old issue, closing.
