### ISSUE TITLE
Cannot establish https connection (nextcloud+nginx+reverse-proxy+letsencrypt)

### ISSUE THREAD

**Issue by mareeba** [nginx-proxy/nginx-proxy#570]
Have recently been trying to get Nextcloud setup following this:
# https://help.nextcloud.com/t/nextcloud-nginx-reverse-proxy-letsencrypt-in-docker-containers/1687

After discovering there are some issues with the nginx template(s) I have managed to get it all working however I can only access the nextcloud docker container via http and not https (which is obviously what we need!)

Some related issues (esp with the template file etc) are:
# fatk/docker-letsencrypt-nginx-proxy-companion-examples#10

and
# fatk/docker-letsencrypt-nginx-proxy-companion-examples#6

Anyone got any suggestions as to how I might get the https connection to work?

**Comment by wader** [comment]
What happens when you access via https? some http error or port not open at all? see anything in logs?

**Comment by mareeba** [comment]
Won't connect at all.
Please scroll down to comments of the following page for logs:

https://help.nextcloud.com/t/nextcloud-nginx-reverse-proxy-letsencrypt-in-docker-containers/1687

**Comment by wader** [comment]
Ok your tk1 in the thread? so https works now? what was the issue?

**Comment by mareeba** [comment]
@wader 
Yeah, updated my GitHub username ....that was indeed me.

TBH I am not 100% sure what the issue was but you might like to talk to https://github.com/SnowMB as he has be kindly helping me to get this going!  See here --> https://help.nextcloud.com/t/nextcloud-nginx-reverse-proxy-letsencrypt-in-docker-containers/1687/28?u=tk1

**Comment by tkw1536** [comment]
Resolved as per last comment.
