### ISSUE TITLE
Subdomain without ssl certificate when domain ssl certificate

### ISSUE THREAD

**Issue by pvlg** [nginx-proxy/nginx-proxy#573]
I have domain mydomain.com with ssl certificate. I want to use the domain sub.mydomain.com without a certificate.

How can I do it?

I replaced the row

`
{{ $vhostCert := (closest (dir "/etc/nginx/certs") (printf "%s.crt" $host))}}
`

to

`
{{ $vhostCert := printf "%s.crt" $host}}
`

I think it would be a good idea to add a options to the configuration, but do not know how best to do it.

**Comment by wader** [comment]
Hi, so you want SSL for `mydomain.com` but not for `sub.mydomain.com`? I think you can do kind of a hack by settings `CERT_NAME=` (empty string) for the `sub.mydomain.com ` container.

**Comment by kamermans** [comment]
We have `HTTPS_METHOD=nohttp` to disable the HTTP site entirely, I could add `HTTPS_METHOD=nohttps` to disable HTTPS if this is a common need.

**Comment by wader** [comment]
@kamermans yes i think that would be nice

**Comment by tkw1536** [comment]
Seems resolved by the above, closing
