### ISSUE TITLE
Support multiple VIRTUAL_PORT alongside VIRTUAL_HOST

### ISSUE THREAD

**Issue by byrnedo** [nginx-proxy/nginx-proxy#59]
Maybe this is being addressed in some of the other open issues or perhaps I missed something when trying this but would be great if a virtual host was mapped to the corresponding port in a list of virtual ports. 

I.e. 
-e VIRTUAL_HOST=one.dev,two.dev -e VIRTUAL_PORT=80,81 

would get the proxy to send traffic  for one.dev to port 80, two.dev to port 81.

Maybe better if I just hack on the template?

**Comment by marmotz** [comment]
+1

**Comment by gabeos** [comment]
Would actually be nice to have a feature in the template for allowing the use of $server_port in the upstream configuration.

Something like VIRTUAL_PORT="all"
or in this model, VIRTUAL_HOST=foo.bar:*

Would be super useful for webapps (like seafile, or others that offer WebDAV), and in general anything that is required to expose multiple ports on the same hostname, e.g. Drupal+Etherpad-lite, etc.

**Comment by jmls** [comment]
how far did you get with this ? We need to expose 2 ports on the container, and have two different virtual hosts. For example a.foo.bar.com->80:80 and b.foo.bar.com->80:9090

**Comment by byrnedo** [comment]
I didn't have much in the line of go skills at the time. I could probably revisit it to finish this if I get time. 

As an alternative (though it was a breaking change so wouldn't be merged ) I catered for `-e VIRTUAL_HOST=foo.bar.com:8080`  ...
Here's the fork https://github.com/byrnedo/nginx-proxy
Check the readme there.

Works fine for us for exposing nonstandard ports via the proxy.

**Comment by jmls** [comment]
thanks for the link - I see that there are several (!) commits from the origin that haven't been merged in - is there a reason for this ?

**Comment by byrnedo** [comment]
Yeah, I just haven't updated it. Do you need this asap?

**Comment by jmls** [comment]
I do .. thanks !

**Comment by byrnedo** [comment]
I'll have a look, might be that too much has changed but we'll see, I'll 
have a go at rebasing.

**Comment by jmls** [comment]
thanks so much. really appreciate it.

**Comment by byrnedo** [comment]
Check it out now, should work. And no problem, actively using it here so I needed this too!

**Comment by jmls** [comment]
awesome! thanks!

**Comment by asthomasdk** [comment]
I did a test build of this in a docker container - and tried it out. Something is wrong though, as the proxying is not working at all now. 

I have tried starting a docker container using something like this: 
-e VIRTUAL_HOST=dev.foor.bar
-e VIRTUAL_PORT=8181

and 
-e VIRTUAL_HOST=dev.foor.bar:8181

and also 
-e VIRTUAL_HOST=dev.foor.bar:8181,preview-dev.foo.bar:3000

None of these work. AllI get is the nginx welcome page. 

The ports mentioned above are the ports the services inside the container are running. The container is being started with : 
-p 8181 -p 3000

**Comment by byrnedo** [comment]
I'll take a look

**Comment by asthomasdk** [comment]
Thanks!

**Comment by byrnedo** [comment]
whats your full 'run' command?

**Comment by byrnedo** [comment]
This seems to be working for me:

docker build -t byrnedos_nginx_proxy_fork .

docker run --rm -it -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock byrnedos_nginx_proxy_fork

docker run --rm -it -p "8080:8080" -p "9090:9090"  -e VIRTUAL_HOST="test.local:8080,test2.local:8090" <some web app which runs on 8080 and 8090>

**Comment by byrnedo** [comment]
can you check the output in the nginx_proxy log ( docker logs -f <container_id/name> ) when you make a request to the virtual host?

**Comment by asthomasdk** [comment]
I'll check. 

I can see you have things in quotes in your last run statement : 
docker run --rm -it -p "8080:8080" -p "9090:9090" -e VIRTUAL_HOST="test.local:8080,test2.local:8090"

Is that a requirement? Usually isn't.

**Comment by byrnedo** [comment]
no, shouldn't be, copy-pasta just. Is the web service in the docker 
container binding to 0.0.0.0 and not just 127.0.0.1?

**Comment by asthomasdk** [comment]
it is binding to 0.0.0.0

**Comment by byrnedo** [comment]
Also try, with the virtual host containers running:
    docker exec -it \<proxy container id/name\> cat /etc/nginx/conf.d/default.conf

That will show the generated template that the proxy is using.

**Comment by md5** [comment]
@byrnedo Any chance you'd want to rework that branch to be backwards compatible and still support `VIRTUAL_PORT` in addition to the colon syntax?

I can't speak for @jwilder and I don't want to endorse running multiple HTTP services in a single container, but it's clearly something that people are doing that can't be supported by `jwilder/nginx-proxy` as it now stands.

**Comment by byrnedo** [comment]
I can give it a go yeah, I have a bit more of a clue about go now so maybe it'd be quick..

**Comment by md5** [comment]
:+1: 

Also, it looks like if you want to make #60 mergeable, you're going to want to rebase out the merge commits at some point. Perhaps wait for some positive encouragement from @jwilder before doing that, though.

**Comment by byrnedo** [comment]
A bad habit I picked up.

**Comment by md5** [comment]
No worries. If you end up needing any enhancement to `docker-gen` or need to ask any question, I'm happy to help.

**Comment by byrnedo** [comment]
Thanks, will let you know.

**Comment by asthomasdk** [comment]
Here's a snippet of the output from default.conf: 

...
upstream dev.foobar.com {
                   # dev.foobar.com
                   server 172.17.0.89:8181;
}
server {
        server_name dev.foobar.com;
        location / {
                proxy_pass http://dev.foobar.com;
        }
}
...

Looks fine as far as I can tell.

**Comment by md5** [comment]
@asthomasdk You said you're getting the Nginx welcome page? That's not something that I've seen `jwilder/nginx-proxy` do (except when testing my branch for `VIRTUAL_PATH` when there was no `/` container defined). Normally, `jwilder/nginx-proxy` will give a 503 error if it doesn't recognize the virtual host. This sounds to me like you actually are reaching a backend container that's also running Nginx, but does not have its virtual hosts configured correctly.

**Comment by asthomasdk** [comment]
Yeah, that would make sense I guess. We usually see the 503 error if the container we are trying to reach is not running and the virtual host is therefore missing, From the snippet I posted earlier, the virtual host seems to be defined as it should. 

I have a number containers running that I have not restarted after I stopped the original jwilder/nginx-proxy cotainer and tried with the fork from @byrnedo . Could that cause problems?

**Comment by md5** [comment]
You shouldn't have to restart the backing containers when replacing the proxy container in front of them.

Looking at @byrnedo's fork, I don't see anything that would make it deviate from the 503 behavior.

**Comment by asthomasdk** [comment]
I ended up shutting down all the containers on the host and restarting the docker service. And guess what? Now it works! 

Thanks for your input - and apologies for a possible waste of your time..

**Comment by byrnedo** [comment]
I'm just happy it wasn't my fork :)

**Comment by asthomasdk** [comment]
Being able to set up multiple virtual hosts from different ports on the container is great. 

We have a development environment running on the first port and a preview of the application being developed on another - all from the same container with node inside. Being able to use virtual hosts in this way is very useful to us. 

Thanks again.

**Comment by md5** [comment]
@asthomasdk Why not just use multiple containers instead?

**Comment by asthomasdk** [comment]
@md5  It's complicated, but the preview is showing the results of the live development from the IDE in the main development container. So it doesn't really make sense to have a separate container for the preview right now. 

We already have multiple containers for the developers code, databases and database servers.

**Comment by crossdot** [comment]
+1

**Comment by adambiggs** [comment]
+1

This feature would enable me to embed `node-inspector` inside our Node.js app for local development.

This is needed because it's an SSL-only app, so both the app and node inspector need to have self-signed SSL certificates.

With this feature we could host the app at e.g. `https://myapp.dev`, and node inspector at `https://debug.myapp.dev`.

**Comment by mancvso** [comment]
Can a use-case like this be supported with this work?


Container 1:
```
docker run -e 'VIRTUAL_HOST=some.host.com' -e 'VIRTUAL_PORT=80' some/webserver
```

Container 2:
```
docker run -e 'VIRTUAL_HOST=some.host.com' -e 'VIRTUAL_PORT=22' some/sftp
```

Two containers sharing the host on different ports.

**Comment by md5** [comment]
@mancvso Nginx doesn't support the SSH/SFTP protocol, so that can't be supported by this image.

**Comment by mancvso** [comment]
The saddest thing I've read today :(

**Comment by md5** [comment]
:crying_cat_face:

**Comment by NickClark** [comment]
In development, a feature like this would be nice. I'm running a couchdb container and it would be nice to access the admin interface on a different virtual host.

**Comment by asthomasdk** [comment]
what is the status on this? 

Do we still need to use this from @byrnedo if we want multiple host & port support? It looks like fork there has a couple of branches now and is not up to date...

**Comment by byrnedo** [comment]
I can merge in if you want, it's out of date since I don't use this myself anymore.

**Comment by asthomasdk** [comment]
If you could, that would be great! 

No chance of this being included in the original project? Would save you the bother of updating if you are not using it ;-)

**Comment by byrnedo** [comment]
Just made a quick attempt and some swarm stuff has been added since I last merged, will have to take more time to do this.

**Comment by byrnedo** [comment]
@asthomasdk  Pushed and seems to be working. Merging to jwilder would be good (for me and you and whoever else uses this). @jwilder @md5, what would I need to do to the current code if it was possible for it to be merged in?

**Comment by md5** [comment]
If #60  were my PR, I'd support just the current functionality for `VIRTUAL_PORT` to avoid breaking existing users. LGTM otherwise.

Adding this is up to @jwilder, though, and he closed #60 a few weeks back.

One thing that does concern me about the complexity of this is that there's no good way to give the user any guidance in the case of a misconfiguration, but that was already the case with `VIRTUAL_PORT`.

**Comment by md5** [comment]
Nevermind. The diff in #60 was not up-to-date. Looking at [this diff](https://github.com/jwilder/nginx-proxy/compare/master...byrnedo:master), it seems fine.

**Comment by md5** [comment]
Actually, it looks like the Swarm support may need a little help with your new code.

Let's see what @jwilder has to say about the whole thing.

**Comment by s17t** [comment]
+1

**Comment by jgangemi** [comment]
is there any forward movement on this? this will be necessary for ppl who want to proxy the new version of sonatype's nexus repository manager and their implementation of docker registries.

**Comment by mikesir87** [comment]
I have the same use case, but with Gitlab.  A single container is exposing one port for the Git web interface and another port for the container registry.

I'm more than happy to help contribute code, but seeing the discussions, it's a little unclear what direction should be used.  Any input @jwilder ?

**Comment by s17t** [comment]
We started to use docker-gen and custom template script loosy inspired by nginx-proxy. Probably the user cases are just too much for a once-fit-all solution.

**Comment by jgangemi** [comment]
@s17t would you mind sharing your template and the steps used to achieve this? i'd be ok w/ using that approach, i'm just not entirely sure on how to get started.

**Comment by jgangemi** [comment]
is there any movement on this? the issue seems to be languishing and i can't proxy the docker functionality of sonatype's nexus 3 w/o this.

**Comment by wader** [comment]
@jgangemi don't think anyone is actively working on it. If you really eager i guess you could try to get the changes in #254 onto master and try

**Comment by jgangemi** [comment]
i'm not sure #254 will solve my problem as i want to point two different hostnames (`nexus.example.com` and `registry.example.com`) to a single docker container and have them be handled by different ports (8081 and 5000). i also don't have a lot of `g

what about the template solution? could someone explain how that works or point to a solid example? i'd be ok w/ that as a solution.

**Comment by wader** [comment]
@jgangemi ah sorry, i assumed this issue was about paths :)

**Comment by jgangemi** [comment]
bueller?

is there any movement on this issue?

**Comment by TheBlusky** [comment]
It does not seem that this issue is important for maintainers ...

However, there is clearly many use cases for it (nexus with repository / registry, seafile with frontend / backend, gitlab with frontend / regsitry, ...)

**Comment by jgangemi** [comment]
yeah - that's very, very unfortunate.

paging @s17t again in the hope he might respond with some information about his custom template.

**Comment by s17t** [comment]
Hi guys,
 the point is to bypass nginx-proxy and learn to use docker-gen and Go template. You can start from here [0]. We have something like this as template:

```
server {
        listen 80 default_server;
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        error_log /proc/self/fd/2;
        access_log /proc/self/fd/1;
        return 503;
}


{{ range $host, $containers := groupByMulti $ "Env.VIRTUAL_HOST" "," }}
{{/*
Original docker-gen nginx template [0] has the upstream section generation. In this
project is worthless as it would end to have one upstream entry per host/proxypass
combination.

Must be handled if one or more proxypass has to be balanced.

[0] https://raw.githubusercontent.com/jwilder/docker-gen/master/templates/nginx.tmpl
*/}}

server {
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        server_name {{ $host }};
        proxy_buffering off;
        error_log /proc/self/fd/2;
        access_log /proc/self/fd/1;

        {{range $s, $p := where $containers "Env.VIRTUAL_HOST" $host}}
                location /{{ $p.Env.VIRTUAL_HOST_PATH }} {

                {{ $addrLen := len $p.Addresses }}
                {{ $network := index $p.Networks 0 }}

                {{/* If only 1 port exposed, use that */}}
                {{ if eq $addrLen 1 }}
                        {{ with $address := index $p.Addresses 0 }}
                                proxy_pass http://{{ trim $address.IP }}:{{ $address.Port }}/{{ $p.Env.VIRTUAL_HOST_PATH }};
                        {{ end }}

                {{/* If more than one port exposed, use the one matching VIRTUAL_PORT env var */}}
                {{ else if $p.Env.VIRTUAL_PORT }}
                        {{ range $i, $address := $p.Addresses }}
                                {{ if eq $address.Port $p.Env.VIRTUAL_PORT }}
                                        proxy_pass http://{{ trim $address.IP  }}:{{ $address.Port }}/{{ $p.Env.VIRTUAL_HOST_PATH }};
                                {{ end }}
                        {{ end }}

                {{/* Else default to standard web port 80 */}}
                {{ else }}
                        {{ range $i, $address := $p.Addresses }}
                                {{ if eq $address.Port "80" }}
                                        proxy_pass http://{{ trim $address.IP }}:{{ $address.Port }}/{{ $p.Env.VIRTUAL_HOST_PATH }};
                                {{ end }}
                        {{ end }}
                {{ end }}

                        proxy_set_header Host $http_host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;

                        # HTTP 1.1 support
                        # proxy_http_version 1.1;
                        # proxy_set_header Connection "";
                }
        {{ end }}
}
{{ end }}
```

Then you will run docker-gen *and* a dockerized nginx:

`
$ docker run -d  --name nginx-gen --volumes-from nginx -v /var/run/docker.sock:/tmp/docker.sock:ro     -v /home/ibex/tmp/docker-gen/templates:/etc/docker-gen/templates -v /home/ibex/tmp/nginx:/etc/nginx/conf.d -t jwilder/docker-gen -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
$ docker run -d -p 80:80 --name nginx -v /home/ibex/tmp/nginx:/etc/nginx/conf.d -t nginx
`

From now on each time you will run a container with `VIRTUAL_HOST`, `VIRTUAL_PORT` and `VIRTUAL_HOST_PATH` environment variables docker-gen will generate new vhost and reload nginx:

`$ docker run --env VIRTUAL_HOST=app.com --env VIRTUAL_PORT=9292 --env VIRTUAL_HOST_PATH=/`
$ docker run --env VIRTUAL_HOST=app.com --env VIRTUAL_PORT=8080 --env VIRTUAL_HOST_PATH=/`

[0] https://github.com/jwilder/docker-gen/blob/master/templates/nginx.tmpl

**Comment by dbendelman** [comment]
B"H

I ran into this issue and tried the byrnedo fork, but found that it no longer builds and is quite behind this upstream atm. Seeing as @byrnedo said he no longer uses this himself, I forked `byrnedo/nginx-proxy`, merged in upstream and fixed the conflicts. We use this as a hub for serving per-branch staging sites, and so far it's been working perfectly for a few days under heavy use.

For anyone coming to this issue now and wants a quick solution, feel free to use this and let me know if you find issues.

* Repo: https://github.com/dbendelman/nginx-proxy
* Automated docker build: https://hub.docker.com/r/dbendelman/nginx-proxy/

**Comment by ronaldtse** [comment]
+1 Is it possible to get this merged? It would save many people hours of labor :-) Thanks!

**Comment by Laykou** [comment]
👍 Please get this merged.

**Comment by ebuildy** [comment]
Hello guys, if you really want multiple backend with a single container, what about using socat (as a simple proxy)?

I have post this solution: https://gist.github.com/ebuildy/c20fd9124730b535dddffa7b9e6946ca

**Comment by luisnabais** [comment]
I would really like this feature. I'm searching for alternatives at the moment... Thanks

**Comment by nodriza-io** [comment]
Hello guys, can someone tell me if the @dbendelman solution works?
https://hub.docker.com/r/dbendelman/nginx-proxy/

I'm trying to make the multi port per container working by adding this:
-e VIRTUAL_HOST=foo.myapp.io:80,foo.nodriza.io:443,foo.myapp.io:3000

But is not working, what can be wrong?

**Comment by dbendelman** [comment]
@nodriza-io check that your container is actually exposing those ports and that they can be reached with `curl` from inside the nginx-proxy container. If that works fine, inspect the `nginx.conf` that was generated inside the nginx-proxy container for any issues.

**Comment by kevrat** [comment]
+1

**Comment by lost-carrier** [comment]
+1

**Comment by codemaker219** [comment]
+1

**Comment by grikomsn** [comment]
Sorry to bring this up here, just wanted to say that @dbendelman's fork works, but I have no idea how to write the `LETSENCRYPT_HOST` for multiple hosts. Here's my `docker-compose.yml`:

```yaml
version: '2'

services:
  server:
    image: sourcegraph/server:3.1.1
    environment:
      - "VIRTUAL_HOST=sourcegraph.example.com:7080,console.sourcegraph.example.com:2633"
      - LETSENCRYPT_HOST=sourcegraph.example.com,console.sourcegraph.example.com
      - LETSENCRYPT_EMAIL=username@example.com
    network_mode: bridge
    ports:
      - 2633:2633
      - 7080:7080
    volumes:
      - server_data:/etc/sourcegraph
      - server_data:/var/opt/sourcegraph

volumes:
  server_data:
```

Anyone got their multiple host work with HTTPS?

**Comment by lon9man** [comment]
+1

**Comment by pnbecker** [comment]
+1

**Comment by nickbozentko** [comment]
+1

**Comment by byrnedo** [comment]
This is 6 years old. I'm gonna close this.

**Comment by justin8** [comment]
Oh cool. Is this fixed then?

**Comment by byrnedo** [comment]
Don't think so actually.

**Comment by nickbozentko** [comment]
Don't think it is fixed. I tried to route two virtual hosts to the same container with no success. Oddly, the documentation says this is supported.

> If you need to support multiple virtual hosts for a container, you can separate each entry with commas. For example, foo.bar.com,baz.bar.com,bar.com and each host will be setup the same.

This did not work for me. 

Is there a good work around for this besides just running a separate container?

**Comment by byrnedo** [comment]
@nickbozentko That's a different thing, multiple vhosts. This issue was to do with routing the vhosts to separate ports.

**Comment by nickbozentko** [comment]
Oops. I was under the impression that they were related.

**Comment by daghb** [comment]
If someone else finds this post: Use VIRTUAL_HOST_MULTIPORT described [here](https://github.com/nginx-proxy/nginx-proxy/blob/main/docs/README.md#multiple-ports-routed-to-different-hostnames)
