### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alizowghi** [nginx-proxy/nginx-proxy#593]
Hello

When I hit the url on browser nginx-proxy container get below errors:

dockergen.1 | panic: runtime error: invalid memory address or nil pointer dereference
dockergen.1 | 58, 0xc82006c680, 0xc8200a5660)
forego     | starting dockergen.1 on port 5200
forego     | sending SIGTERM to dockergen.1
forego     | sending SIGTERM to nginx.1
-bash-4.2#

**Comment by wader** [comment]
Hi, is this with default template? i would guess the crash happens before your doing the request, docker-gen itself is not involved when the request is handled.

**Comment by alizowghi** [comment]
I use this method and everything works well:
`docker run -d --restart=always -p 80:80 --name nginx -v /tmp/nginx:/etc/nginx/conf.d -t nginx
mkdir -p /tmp/templates && cd /tmp/templates
curl -o nginx.tmpl https://raw.githubusercontent.com/jwilder/docker-gen/master/templates/nginx.tmpl
docker run -d --restart=always --name nginx-gen --volumes-from nginx \
   -v /var/run/docker.sock:/tmp/docker.sock:ro \
   -v /tmp/templates:/etc/docker-gen/templates \
   -t jwilder/docker-gen -notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
`

But when use:
`docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

and then use:
`docker run -d -e "VIRTUAL_HOST=domain.com" tutum/wordpress`

I encounter with mentioned error

Selinux is enabled on my vps

**Comment by wader** [comment]
Can you reproduce the crash with `docker run -v /var/run/docker.sock:/tmp/docker.sock:ro --entrypoint docker-gen jwilder/nginx-proxy /app/nginx.tmpl /etc/nginx/conf.d/default.conf`? make sure to have the tutum/wordpress container running.

**Comment by alizowghi** [comment]
With `docker run  -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy` and `setenforce 1`:

`docker run -v /var/run/docker.sock:/tmp/docker.sock:ro --entrypoint docker-gen jwilder/nginx-proxy /app/nginx.tmpl /etc/nginx/conf.d/default.conf` says:

`2016/10/03 15:48:15 Error retrieving docker server version info: Get http://unix.sock/version: dial unix /tmp/docker.sock: connect: permission denied
2016/10/03 15:48:15 Error retrieving docker server info: Get http://unix.sock/info: dial unix /tmp/docker.sock: connect: permission denied
2016/10/03 15:48:15 Error listing containers: Get http://unix.sock/containers/json?all=1: dial unix /tmp/docker.sock: connect: permission denied
`
and with setenforce 1:

everything works great and it says:
`2016/10/03 15:46:40 Generated '/etc/nginx/conf.d/default.conf' from 5 containers`

these are when the virtual host is ran, but if I want to start a new one, browser says:
`Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.`

and if I disable Selinux `docker run  -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy` get below error:

`dockergen.1 | 2016/10/03 15:53:00 Docker daemon connection interrupted
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:05 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:06 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:07 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:07 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:08 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:09 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:10 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
dockergen.1 | 2016/10/03 15:53:10 Watching docker events
dockergen.1 | panic: runtime error: invalid memory address or nil pointer dereference
dockergen.1 | 58, 0xc82006c680, 0xc8200a5660)
forego     | starting dockergen.1 on port 5200
forego     | sending SIGTERM to dockergen.1
forego     | sending SIGTERM to nginx.1
`

**Comment by jwilder** [comment]
Can you attach the full trace for the docker-gen logs?  There is not enough of the trace to know where the panic occurred in docker-gen.

**Comment by alizowghi** [comment]
-bash-4.2# docker run  -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2016/10/03 15:48:11 Error retrieving docker server version info: Get http://unix.sock/version: dial unix /tmp/docker.sock: connect: permission denied
dockergen.1 | 2016/10/03 15:48:11 Error listing containers: Get http://unix.sock/containers/json?all=1: dial unix /tmp/docker.sock: connect: permission denied
dockergen.1 | 2016/10/03 15:48:11 Watching docker events
dockergen.1 | 2016/10/03 15:48:11 Docker daemon connection interrupted
nginx.1    | 2016/10/03 15:48:18 [error] 21#21: *1 open() "/usr/share/nginx/html/wp-admin/install.php" failed (2: No such file or directory), client: 2.178.206.91, server: localhost, request: "GET /wp-admin/install.php HTTP/1.1", host: "junc.ir"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:48:18 +0000] "GET /wp-admin/install.php HTTP/1.1" 404 169 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2016/10/03 15:48:19 [error] 21#21: *1 open() "/usr/share/nginx/html/wp-admin/install.php" failed (2: No such file or directory), client: 2.178.206.91, server: localhost, request: "GET /wp-admin/install.php HTTP/1.1", host: "junc.ir"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:48:19 +0000] "GET /wp-admin/install.php HTTP/1.1" 404 169 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2016/10/03 15:48:19 [error] 21#21: *1 open() "/usr/share/nginx/html/wp-admin/install.php" failed (2: No such file or directory), client: 2.178.206.91, server: localhost, request: "GET /wp-admin/install.php HTTP/1.1", host: "junc.ir"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:48:19 +0000] "GET /wp-admin/install.php HTTP/1.1" 404 169 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2016/10/03 15:48:20 [error] 21#21: *1 open() "/usr/share/nginx/html/wp-admin/install.php" failed (2: No such file or directory), client: 2.178.206.91, server: localhost, request: "GET /wp-admin/install.php HTTP/1.1", host: "junc.ir"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:48:20 +0000] "GET /wp-admin/install.php HTTP/1.1" 404 169 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
dockergen.1 | 2016/10/03 15:48:21 Watching docker events
dockergen.1 | 2016/10/03 15:48:21 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:48:31 Watching docker events
dockergen.1 | 2016/10/03 15:48:31 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:48:41 Watching docker events
dockergen.1 | 2016/10/03 15:48:42 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:48:52 Watching docker events
dockergen.1 | 2016/10/03 15:48:52 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:49:02 Watching docker events
dockergen.1 | 2016/10/03 15:49:02 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:49:12 Watching docker events
dockergen.1 | 2016/10/03 15:49:13 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:49:23 Watching docker events
dockergen.1 | 2016/10/03 15:49:23 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:49:33 Watching docker events
dockergen.1 | 2016/10/03 15:49:33 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:49:43 Watching docker events
dockergen.1 | 2016/10/03 15:49:44 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:49:54 Watching docker events
dockergen.1 | 2016/10/03 15:49:54 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:50:04 Watching docker events
dockergen.1 | 2016/10/03 15:50:04 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:50:14 Watching docker events
dockergen.1 | 2016/10/03 15:50:15 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:50:25 Watching docker events
dockergen.1 | 2016/10/03 15:50:25 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:50:35 Watching docker events
dockergen.1 | 2016/10/03 15:50:35 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:50:45 Watching docker events
dockergen.1 | 2016/10/03 15:50:46 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:50:56 Watching docker events
dockergen.1 | 2016/10/03 15:50:56 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:51:06 Watching docker events
dockergen.1 | 2016/10/03 15:51:06 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:51:16 Watching docker events
dockergen.1 | 2016/10/03 15:51:17 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:51:27 Watching docker events
dockergen.1 | 2016/10/03 15:51:27 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:51:37 Watching docker events
dockergen.1 | 2016/10/03 15:51:37 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:51:47 Watching docker events
dockergen.1 | 2016/10/03 15:51:48 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:51:58 Watching docker events
dockergen.1 | 2016/10/03 15:51:58 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:52:08 Watching docker events
dockergen.1 | 2016/10/03 15:52:08 Docker daemon connection interrupted
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:52:16 +0000] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:52:18 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
dockergen.1 | 2016/10/03 15:52:18 Watching docker events
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:52:18 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
dockergen.1 | 2016/10/03 15:52:18 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:52:28 Watching docker events
dockergen.1 | 2016/10/03 15:52:29 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:52:39 Watching docker events
dockergen.1 | 2016/10/03 15:52:39 Error listing containers: Get http://unix.sock/containers/json?all=1: dial unix /tmp/docker.sock: connect: permission denied
dockergen.1 | 2016/10/03 15:52:39 Docker daemon connection interrupted
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:52:47 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:52:48 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
dockergen.1 | 2016/10/03 15:52:49 Watching docker events
dockergen.1 | 2016/10/03 15:52:49 Docker daemon connection interrupted
dockergen.1 | 2016/10/03 15:52:59 Watching docker events
dockergen.1 | 2016/10/03 15:53:00 Docker daemon connection interrupted
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:05 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:06 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:07 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:07 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:08 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:09 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
nginx.1    | 2.178.206.91 - - [03/Oct/2016:15:53:10 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" "-"
dockergen.1 | 2016/10/03 15:53:10 Watching docker events
dockergen.1 | panic: runtime error: invalid memory address or nil pointer dereference
dockergen.1 | 58, 0xc82006c680, 0xc8200a5660)
forego     | starting dockergen.1 on port 5200
forego     | sending SIGTERM to dockergen.1
forego     | sending SIGTERM to nginx.1
-bash-4.2#

**Comment by tkw1536** [comment]
This issue is very old, and no logs were provided that provide exact details of the error.
Closing, if this issue comes up again, please re-open.
