### ISSUE TITLE
Working on a Multi-node cluster?

### ISSUE THREAD

**Issue by andreykats** [nginx-proxy/nginx-proxy#595]
Is it possible to use jwilder/nginx-proxy on a cluster?

I currently have a multi node AWS ECS cluster and jwilder/nginx-proxy does not appear to see containers that are running on a different node of the same cluster. 

Any input is appreciated.

**Comment by pascalandy** [comment]
I guess you are talking about running under an orchestration system like Docker Swarm ?

Check this out: https://github.com/jwilder/nginx-proxy/issues/520

**Comment by tkw1536** [comment]
Duplicate of #97
