### ISSUE TITLE
url routing instead of subdomain

### ISSUE THREAD

**Issue by jim-bo** [nginx-proxy/nginx-proxy#598]
I have an application composed of two separate containers (html server exposing html:8080 and ES server exposing es:9200). Is it possible to use this to proxy example.com -> html:8080 and example.com/search -> es:9200

The examples seem to only allow to proxy to subdomains like es.example.com

Thanks for the help!

**Comment by wader** [comment]
HI, there is a long running PR trying to do it #254

**Comment by tkw1536** [comment]
Closed by #1607
