### ISSUE TITLE
How Do I Enable Keepalive connections

### ISSUE THREAD

**Issue by nzesalem** [nginx-proxy/nginx-proxy#609]
Please, what's the recommended way to enable `keepalive` connections.
I'm supposed to add something like
`keepalive 100;`
in the upstream directive, and 
`proxy_http_version 1.1;`
`proxy_set_header Connection "";`
in that of `location` correct?
But since the confs are generated, I can't seem to figure out a way to add these without breaking anything.

**Comment by wader** [comment]
Hi, you mean keepalive between nginx-proxy and upstream server (https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive)?

**Comment by JimsNK** [comment]
Yes @wader 
More like this https://ma.ttias.be/enable-keepalive-connections-in-nginx-upstream-proxy-configurations/ I think

**Comment by wader** [comment]
Hmm nginx docs says `Context: upstream` so I guess you have to run with a custom template to do that at the moment.

**Comment by mprokopov** [comment]
I believe you can create folder with VIRTUAL_HOST name and attach it to nginx container as volume, so nginx could find it at /etc/nginx/vhosts.d/VIRTUAL_HOST.

Then you settings will be applied to location section.

**Comment by nstahle** [comment]
Any luck with this?

**Comment by stephan2012** [comment]
According to http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive the keepalive directive needs to go to the `upstream` block. Like to see this feature, too, because it reduces overhead.

**Comment by hellojukay** [comment]
```txt
proxy_http_version 1.1;
```
it works good.

**Comment by tkw1536** [comment]
To achieve keepalive connections, you would have to modify https://github.com/nginx-proxy/nginx-proxy/blob/master/nginx.tmpl to edit the upstream blocks. They get generated around [Line 178](https://github.com/nginx-proxy/nginx-proxy/blob/master/nginx.tmpl#L178-L205), inserting a new line `keepalive 100;` should do the trick. 

To do that, you should probably copy your custom `nginx.tmpl` into a new directory and then make an image with something like:
```Dockerfile
FROM jwilder/nginx-proxy
ADD my-custom-nginx.tmpl /app/nginx.tmpl 

```
To modify the location blocks you probably want to make use of [Per-VIRTUAL_HOST location default configuration](https://github.com/nginx-proxy/nginx-proxy#per-virtual_host-location-default-configuration). See the README for details on that.

**Comment by JasonCeng** [comment]
if I'm https, how to config nginx？
