### ISSUE TITLE
behaviour wrong fullchain.pem privkey.pem combo

### ISSUE THREAD

**Issue by hkerssies** [nginx-proxy/nginx-proxy#615]
I had a weird behaviour on mij docker host.
When using servers with ssl en fullchain.pem privkey.pem for a domain
like domain.com.crt and domain.com.key I found that when this combo is wrong (I accidentally used and old version of fullchain.pem from this domain) the proxy did not host the right vhosts from than on.
So when creating a new vhost with domain2.com it was serving a random other vhost.
This took me a long time to debug with over 100 vhosts.

Is it possible to check the certs for this before using them with jwilder/nginx-proxy?

**Comment by buchdag** [comment]
I think this was a side effect of a behaviour that was fixed in #2186
