### ISSUE TITLE
Can it support to separat by url subpath?

### ISSUE THREAD

**Issue by qwIvan** [nginx-proxy/nginx-proxy#628]
like
```
location /blog {
    root /usr/share/blog;
}
```

separat by `location` path instead of `server_name`

**Comment by alesculek** [comment]
Hi, did you solve this somehow? I'm running into the similar problem where I need everything from `domain.tld/api/<some-container>`

**Comment by alesculek** [comment]
#254

**Comment by buchdag** [comment]
This features has been added to the `dev` branch with #1607 

It's available now on the `dev` images `nginxproxy/nginx-proxy:dev` and `nginxproxy/nginx-proxy:dev-alpine`. Testing and feedback are welcome, the docs for the feature is [here](https://github.com/nginx-proxy/nginx-proxy/tree/dev#path-based-routing) and there is [another PR](https://github.com/nginx-proxy/nginx-proxy/pull/1699) opened for additional improvements and comments.
