### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by orboan** [nginx-proxy/nginx-proxy#657]
Hello,

- if my container exposes only one port, that's the one gonna be used by the proxy,
- if my container exposes two ports, the one used will be by default the 80, or the one stated with VIRTUAL_PORT,
- if I want more than one subdomain pointing to my container, just add all of them separated by commas. All subdomains are gonna point to the only exposed port or the VIRTUAL_PORT, or 80, whatever but only to one port.

My question is how can I point two different subdomains to two different exposed ports from the same container, each subdomain pointing to only one port (one-to-one relation).
Thanks.

**Comment by orboan** [comment]
https://github.com/jwilder/nginx-proxy/issues/560
and
https://github.com/jwilder/nginx-proxy/issues/59

**Comment by cdaringe** [comment]
@orboan, i haven't read anything that infers that your use case is supported out-of-the-box, unfortunately.  you'd probably have to add a patch to this project

**Comment by buchdag** [comment]
This has since been implemented, see #2434 and [the corresponding documentation](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#multiple-ports).
