### ISSUE TITLE
Nginx server sets Server:nginx/1.11.8 header

### ISSUE THREAD

**Issue by natami** [nginx-proxy/nginx-proxy#674]
Please remove header telling it's a Nginx server and which version.

**Comment by matt-hh** [comment]
nginx-proxy uses nginx.conf from https://hub.docker.com/_/nginx/

You can create a Dockerfile and disable server tokens.

```
FROM jwilder/nginx-proxy
RUN echo 'server_tokens off;' > /etc/nginx/conf.d/server_tokens.conf
```

Hope this helps

**Comment by buchdag** [comment]
This wad made easily configurable in #1620
