### ISSUE TITLE
Do not make 443 required when a SSL key is available

### ISSUE THREAD

**Issue by titogarrido** [nginx-proxy/nginx-proxy#73]
Hi! Is it possible to do not make a rewrite for 443 when SSL is available? I would like to make it available on certain pages or when I use https on a link... How could I change this behavior?

Thanks in advance!

Tito

**Comment by hacker-h** [comment]
> To serve traffic in both SSL and non-SSL modes without redirecting to SSL, you can include the environment variable `HTTPS_METHOD=noredirect` (the default is `HTTPS_METHOD=redirect`).

**Comment by tkw1536** [comment]
Issue resolved, closing.
