### ISSUE TITLE
how to increase log level for debugging?

### ISSUE THREAD

**Issue by cdaringe** [nginx-proxy/nginx-proxy#746]
i regularly find that my containers are not being proxied.  is there a way to bump the logs s.t. it shows the proxy=>service info s.t. i can figure out why my app isnt being proxied?

**Comment by thomasleveil** [comment]
I had the same issue: figuring out what's going wrong and came up with PR #745. Give this template a try

**Comment by cdaringe** [comment]
hey @thomasleveil, thanks!  i see that you added some comments to the template.  there are, however, no runtime changes to the image, correct?  that is, your new template doesnt emit more log info, right?

**Comment by thomasleveil** [comment]
for the template, it just produces more comments into the generated default.conf file. It helps understanding  how the template logic was applied.

**Comment by cdaringe** [comment]
oh gotcha.  i get it now.  sorry, i wasnt registering that those comments show up in the dynamic config. thx!
