### ISSUE TITLE
Default SSL server

### ISSUE THREAD

**Issue by G-E-N-E** [nginx-proxy/nginx-proxy#765]
The default template creates a default server to catch "bad" server_names on port 80.
I'd like to see it also create one for port 443 (ssl) requests.

server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 443;
	{{ if $enable_ipv6 }}
	listen [::]:80;
	{{ end }}
	access_log /var/log/nginx/access.log vhost;
	return 503;
}

**Comment by buchdag** [comment]
This was fixed by #2186
