### ISSUE TITLE
HTTP_METHOD=nohttps requires CERT_NAME set to work in some cases

### ISSUE THREAD

**Issue by G-E-N-E** [nginx-proxy/nginx-proxy#766]
This might just be something to add to the documentation...

I have a wildcard certificate used by a couple virtual hosts which require https (redirect).
When I went to spin up a new virtual host which requires that only http be used (HTTP_METHOD=nohttps) I was surprised to find that I ended up getting a 503. The virtual host
I was attempting to spin up also matched the wildcard certificate which as far as I can tell is what
causes the issue.

The issue can be easily fixed by adding `CERT_NAME=<invalid cert name>` but it wasn't documented that this would work and it wasn't obvious.

I think it's a bug that a valid cert overrules the HTTP_METHOD=nohttps.

**Comment by thomasleveil** [comment]
You should provide the `/etc/nginx/certs/default.crt` and `/etc/nginx/certs/default.key` files. With those attempts to query that nohttps vhost will be answered with HTTP status code `500`.

The relevant part in the documentation is [§ How SSL Support Works](https://github.com/jwilder/nginx-proxy/blob/master/README.md#how-ssl-support-works):

> The default behavior for the proxy when port 80 and 443 are exposed is as follows:
> 
> - If a container has a usable cert, port 80 will redirect to 443 for that container so that HTTPS is always preferred when available.
> - If the container does not have a usable cert, a 503 will be returned.
> 
> Note that in the latter case, a browser may get an connection error as no certificate is available to establish a connection. A self-signed or generic cert named default.crt and default.key will allow a client browser to make a SSL connection (likely w/ a warning) and subsequently receive a 503.

_(and yes the README says `503`, but the actual code is `500` in the nginx conf - #767)_

**Comment by buchdag** [comment]
This should have been fixed by #2186
