### ISSUE TITLE
location in upstream ?

### ISSUE THREAD

**Issue by zerpex** [nginx-proxy/nginx-proxy#874]
Hi,

Didn't find if it's possible to redirect to a specific location INSIDE the container : I need to to proxypass sub.domain.tld to http://xx.xx.xx.xx:2385/locationX.

Is it possible ?
Wich env var do I have to use ?

Regards,
z.

**Comment by Pimmetje** [comment]
U can include a config inside the vhost see https://github.com/jwilder/nginx-proxy/#per-virtual_host

**Comment by buchdag** [comment]
This use case is now handled by the [`VIRTUAL_PATH`](https://github.com/nginx-proxy/nginx-proxy#path-based-routing) and [`VIRTUAL_DEST`](https://github.com/nginx-proxy/nginx-proxy#virtual_dest) features.
