### ISSUE TITLE
504 Timeout but App Working, Just Slow

### ISSUE THREAD

**Issue by deed02392** [nginx-proxy/nginx-proxy#889]
Some of my web services behind nginx-proxy are legitimately slow to respond to certain endpoints. In an ideal world I'd go and change their behaviour so they weren't, but whilst we're on Earth, is there a neat way of extending how long nginx waits for an upstream server before responding to clients with 504? An envar perhaps? Couldn't see reference in the readme docs if so. :-)

**Comment by shubhank008** [comment]
Having same issue, App (Ghost Blog) is up but dead slow (unless cached version) and times out 504 after some 60~ secs of waiting to load.  
Its working well in a closed isolated private mode (i.e. when only I test it) but when I make it public with some 50~ users online at once, it keeps loading forever dead slow.

**Comment by jpic** [comment]
Do you think it could be nginx or docker issue ?

**Comment by shubhank008** [comment]
In my case, looks like nginx_proxy as everything works when testing with 1-2 users but as soon as I go public with 100~ users it starts to slow up, 504 and stuff.   
I have some doubts on perhaps hitting server resources as well (2 Cores, 2GB Ram cloud) but it shouldn't be the case as I am hosting my site on another same droplet in normal nginx (non-docker, non-nginx_proxy).  Another reason for this statement is the CPU load is never high to think am maxing out my cores.

I will try to increase my server resources to see if it helps calm it down.

**Comment by deed02392** [comment]
The readme mentions you can give explicit directives on a per host basis. I need to check what the exact stanza is to increase the upstream proxy timeout value, and I think this will close this issue.

**Comment by NyxTrail** [comment]
Since this issue is still open in 2024, leaving this here for anyone else who stumbles onto this.

We can customize the nginx-conf as mentioned [here](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#custom-nginx-configuration) .

I added the following to a "proxy.conf" file and moved it to `/etc/nginx/conf.d` inside the proxy container:
```
proxy_connect_timeout       300;
proxy_send_timeout          300;
proxy_read_timeout          300;
send_timeout                300;
```

**Comment by buchdag** [comment]
@NyxTrail thanks for the tip, I think we can consider this solved.
