### ISSUE TITLE
nginx_proxy failed (21: Is a directory)

### ISSUE THREAD

**Issue by agustinvinao** [nginx-proxy/nginx-proxy#923]
I'm trying to override the .conf file for a subdomain (I've tried to do it with the domain too) and when I try to run my container I see this
```
proxy_1     | nginx.1    | 2017/09/10 20:38:16 [crit] 27#27: pread() "/etc/nginx/conf.d/demo.getdairyfarms.com.conf" failed (21: Is a directory)
proxy_1     | nginx.1    | nginx: [crit] pread() "/etc/nginx/conf.d/demo.getdairyfarms.com.conf" failed (21: Is a directory)
```
when my volumes are these:
```
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - app-public:/usr/share/nginx/html/dairyfarms/
      - "./containers/production/demo_getdairyfarms_com.conf:/etc/nginx/conf.d/demo.getdairyfarms.com.conf:ro"
```

Im not sending two files with the same name. Any idea?

**Comment by kevrat** [comment]
I have same issue. Did you resolve this?

**Comment by sirdiego** [comment]
Maybe it helps someone else. I had this same message and the container restarted again and again. For me the problem was that I had a typo in my local config file path and docker created it as a directory instead:

> -v /home/sirdiego/folder-with-typo/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf

**Comment by CaliforniaMountainSnake** [comment]
Make sure you use an absolute path when mounting a docker volume! I had the same value when I tried to mount a volume with a relative path.
