### ISSUE TITLE
Unable to get Json formatted logs through the nginx reverse proxy

### ISSUE THREAD

**Issue by AnkurJain10** [nginx-proxy/nginx-proxy#928]
Hey,
I am having an issue where Json logs are not getting read into the nginx reverse proxy from an external source.. What changes should I make in the nginx config to allow this? The server on which the nginx reverse proxy is running on only has ports 8080(http) and 443(https) exposed.
However Http and https request are going through.

**Comment by kamermans** [comment]
If the JSON logs are not inside HTTP or HTTPS requests, then how are they supposed to be "read into the nginx reverse proxy from an external source"?  You're probably not getting an answer because we are all confused :)
