### ISSUE TITLE
Replacing default proxy_pass URL

### ISSUE THREAD

**Issue by eroji** [nginx-proxy/nginx-proxy#980]
I have an application that has a context path for a single, specific virtual host that I want to bypass using the proxy_pass URL in the location block. For instance my.domain.com/app1 takes you to the app, but my.domain.com takes you to Tomcat. I don't want the proxy to route to Tomcat at all and that the base domain my.domain.com to take me directly to the app. Normally this is done by changing the URL in the proxy_pass value, but it seems like the default.conf is regenerated automatically and puts the value back if I edit it manually at all. Is there a way to get around this?

**Comment by eroji** [comment]
Using the documented method of vhost.d configuration only appends to the location block. For instance, if I created the container with the _location file created and vhost.d volume mounted, the block that is generated looks like this:

```
        location / {
                proxy_pass http://my.domain.com;
                include /etc/nginx/vhost.d/my.domain.com_location;
        }
```

Which doesn't work because the my.domain.com_location file also contains proxy_pass parameter, which conflicts.

**Comment by spakarl** [comment]
same problem here

**Comment by JosemyDuarte** [comment]
Any workaround on this?

**Comment by buchdag** [comment]
This use case is now handled by the [`VIRTUAL_PATH`](https://github.com/nginx-proxy/nginx-proxy#path-based-routing) and [`VIRTUAL_DEST`](https://github.com/nginx-proxy/nginx-proxy#virtual_dest) features.
